import type {
  KitConfig,
  SeedDataset,
} from "../../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../../ids";

/**
 * Imported purchasable kit rows from miniset kit content pages for black_templars.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const CombatPatrolBlackTemplars2025Kit: KitConfig = {
  id: kitId("combat_patrol_black_templars_2025"),
  kit_slug: "combat-patrol-black-templars-2025",
  kit_name: "Combat Patrol: Black Templars",
  display_name: "Combat Patrol: Black Templars",
  gw_slug: "combat-patrol-black-templars-2025",
  gw_short_slug: null,
  gw_year: 2025,
  model_count: 19,
  kit_type_id: kitTypeId("combat_patrol"),
  gw_product_url: "https://www.warhammer.com/en-WW/shop/combat-patrol-black-templars-2025",
  gw_image_url: null,
  gw_product_code: null,
  gw_short_code: null,
  product_gtin: null,
  tcgcsv_product_id: null,
  tcgcsv_product_url: null,
  release_date: new Date("2025-08-09"),
  discontinued_date: null,
};


export const kitContentImportedKitsMinisetBlackTemplarsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    CombatPatrolBlackTemplars2025Kit,
  ] satisfies KitConfig[],
};
