from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .models import NormalizedCountry


REPO_ROOT = Path(__file__).resolve().parents[2]
COUNTRIES_DATA_PATH = REPO_ROOT / "db/seed_config/seed/data/countries.data.ts"


def apply_normalized_countries(
    countries: list[NormalizedCountry],
    repo_root: Path = REPO_ROOT,
) -> None:
    path = repo_root / "db/seed_config/seed/data/countries.data.ts"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_countries_dataset(countries), encoding="utf-8")


def render_countries_dataset(countries: list[NormalizedCountry]) -> str:
    lines = [
        "import type {",
        "  CountryConfig,",
        "  SeedDataset,",
        '} from "../../types/_index.types";',
        "",
        "/**",
        " * Typed seed dataset for the `countries` table.",
        " *",
        " * Generated by `scripts/sync-countries.py` from REST Countries v4.",
        " * REST Countries v4 replaces `latlng` with `geolocation`; the",
        " * importer stores `[latitude, longitude]` in the existing `latlng`",
        " * seed field for compatibility with the current Prisma schema.",
        " */",
        'export const countriesDataset: SeedDataset<"countries"> = {',
        '  table: "countries",',
        "  records: [",
    ]

    for country in sorted(countries, key=lambda item: item.cca2):
        lines.extend(render_country_record(country))

    lines.extend(
        [
            "  ] satisfies CountryConfig[],",
            "};",
            "",
        ],
    )
    return "\n".join(lines)


def render_country_record(country: NormalizedCountry) -> list[str]:
    values: dict[str, Any] = {
        "id": country.id,
        "cca2": country.cca2,
        "cca3": country.cca3,
        "ccn3": country.ccn3,
        "name_common": country.name_common,
        "name_official": country.name_official,
        "name_native": country.name_native,
        "un_member": country.un_member,
        "region": country.region,
        "subregion": country.subregion,
        "continents": country.continents,
        "tld": country.tld,
        "timezones": country.timezones,
        "flag": country.flag,
        "population": country.population,
        "currencies": country.currencies,
        "languages": country.languages,
        "car": country.car,
        "postal_code": country.postal_code,
        "latlng": country.latlng,
        "government": country.government,
        "gdp": country.gdp,
        "hdi": country.hdi,
    }

    lines = ["    {"]
    for key, value in values.items():
        lines.append(f"      {key}: {ts_value(value)},")
    lines.append("    },")
    return lines


def ts_value(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=True, sort_keys=True)
