from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from .models import NormalizedKitContent


REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_ROOT = REPO_ROOT / "db/seed_config/seed/data"
KITS_ROOT_PATH = DATA_ROOT / "kits.data.ts"
KIT_UNITS_ROOT_PATH = DATA_ROOT / "kit_units.data.ts"
KITS_GENERATED_PATH = DATA_ROOT / "kits/kit_content_imported.data.ts"
KIT_UNITS_GENERATED_PATH = DATA_ROOT / "kit_units/kit_content_imported.data.ts"
GENERATED_IDS_PATH = REPO_ROOT / "db/seed_config/seed/ids/generated_game_data.ids.ts"

CROCKFORD_BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def apply_normalized_kit_contents(
    contents: list[NormalizedKitContent],
    repo_root: Path = REPO_ROOT,
) -> None:
    data_root = repo_root / "db/seed_config/seed/data"
    kits_path = data_root / "kits.data.ts"
    kit_units_path = data_root / "kit_units.data.ts"
    generated_kits_path = data_root / "kits/kit_content_imported.data.ts"
    generated_kit_units_path = data_root / "kit_units/kit_content_imported.data.ts"
    ids_path = repo_root / "db/seed_config/seed/ids/generated_game_data.ids.ts"

    generated_kits_path.parent.mkdir(parents=True, exist_ok=True)
    generated_kit_units_path.parent.mkdir(parents=True, exist_ok=True)

    generated_kits_path.write_text(render_kits_dataset(contents), encoding="utf-8")
    generated_kit_units_path.write_text(
        render_kit_units_dataset(contents),
        encoding="utf-8",
    )
    ensure_root_dataset_spread(
        path=kits_path,
        import_line='import { kitContentImportedKitsDataset } from "./kits/kit_content_imported.data";',
        spread_line="    ...kitContentImportedKitsDataset.records,",
        config_name="KitConfig",
    )
    ensure_root_dataset_spread(
        path=kit_units_path,
        import_line='import { kitContentImportedKitUnitsDataset } from "./kit_units/kit_content_imported.data";',
        spread_line="    ...kitContentImportedKitUnitsDataset.records,",
        config_name="KitUnitConfig",
    )
    update_generated_ids(ids_path, contents)


def render_kits_dataset(contents: list[NormalizedKitContent]) -> str:
    const_names = [f"{identifier_pascal_case(content.kit_seed_slug)}Kit" for content in contents]
    lines = [
        "import type {",
        "  KitConfig,",
        "  SeedDataset,",
        '} from "../../../types/_index.types";',
        'import { kitId, kitTypeId } from "../../ids";',
        "",
        "/**",
        " * Imported purchasable kit rows from source-backed kit content pages.",
        " * Generated by scripts/kit_content_importer/applyer.py.",
        " */",
        "",
    ]

    for content, const_name in zip(contents, const_names, strict=True):
        lines.extend(
            [
                f"export const {const_name}: KitConfig = {{",
                f'  id: kitId({ts_string(content.kit_seed_slug)}),',
                f'  kit_slug: {ts_string(content.kit_slug)},',
                f'  kit_name: {ts_string(content.kit_name)},',
                f'  display_name: {ts_string(content.display_name)},',
                f'  gw_slug: {ts_nullable_string(content.gw_slug)},',
                f'  gw_short_slug: {ts_nullable_string(content.gw_short_slug)},',
                f"  gw_year: {content.gw_year if content.gw_year is not None else 'null'},",
                f"  model_count: {content.model_count},",
                f'  kit_type_id: kitTypeId({ts_string(content.kit_type_slug)}),',
                f'  gw_product_url: {ts_nullable_string(content.gw_product_url)},',
                "  gw_image_url: null,",
                f"  release_date: {ts_nullable_date(content.release_date)},",
                "  discontinued_date: null,",
                "};",
                "",
                "",
            ],
        )

    lines.extend(render_dataset("kitContentImportedKitsDataset", "kits", const_names, "KitConfig"))
    return "\n".join(lines)


def render_kit_units_dataset(contents: list[NormalizedKitContent]) -> str:
    records = [unit for content in contents for unit in content.kit_units]
    const_names = [f"{identifier_pascal_case(record.seed_id_key)}KitUnit" for record in records]
    lines = [
        "import type {",
        "  KitUnitConfig,",
        "  SeedDataset,",
        '} from "../../../types/_index.types";',
        'import { kitId, kitUnitId, unitId } from "../../ids";',
        "",
        "/**",
        " * Imported kit-to-unit rows from source-backed kit content pages.",
        " * Generated by scripts/kit_content_importer/applyer.py.",
        " */",
        "",
    ]

    for record, const_name in zip(records, const_names, strict=True):
        lines.extend(
            [
                f"export const {const_name}: KitUnitConfig = {{",
                f'  id: kitUnitId({ts_string(record.seed_id_key)}),',
                f'  kit_id: kitId({ts_string(record.kit_seed_slug)}),',
                f'  unit_id: unitId({ts_string(record.unit_slug)}),',
                f"  unit_count: {record.unit_count},",
                f"  model_count: {record.model_count},",
                f'  component_type: {ts_string(record.component_type)},',
                "  effective_date: null,",
                "  superseded_date: null,",
                "};",
                "",
                "",
            ],
        )

    lines.extend(
        render_dataset(
            "kitContentImportedKitUnitsDataset",
            "kit_units",
            const_names,
            "KitUnitConfig",
        ),
    )
    return "\n".join(lines)


def render_dataset(
    dataset_name: str,
    table_name: str,
    const_names: list[str],
    config_name: str,
) -> list[str]:
    lines = [
        f'export const {dataset_name}: SeedDataset<"{table_name}"> = {{',
        f'  table: "{table_name}",',
        "  records: [",
    ]
    lines.extend(f"    {const_name}," for const_name in const_names)
    lines.extend(
        [
            f"  ] satisfies {config_name}[],",
            "};",
            "",
        ],
    )
    return lines


def ensure_root_dataset_spread(
    *,
    path: Path,
    import_line: str,
    spread_line: str,
    config_name: str,
) -> None:
    text = path.read_text(encoding="utf-8")

    if import_line not in text:
        import_matches = list(re.finditer(r'^import .+;\n', text, flags=re.MULTILINE))
        if import_matches:
            insert_at = import_matches[-1].end()
            text = f"{text[:insert_at]}{import_line}\n{text[insert_at:]}"
        else:
            text = f"{import_line}\n{text}"

    if spread_line not in text:
        text = text.replace(
            f"  ] satisfies {config_name}[],",
            f"{spread_line}\n  ] satisfies {config_name}[],",
        )

    path.write_text(text, encoding="utf-8")


def update_generated_ids(ids_path: Path, contents: list[NormalizedKitContent]) -> None:
    text = ids_path.read_text(encoding="utf-8")
    kit_keys = [content.kit_seed_slug for content in contents]
    kit_unit_keys = [unit.seed_id_key for content in contents for unit in content.kit_units]

    for key in kit_keys:
        text = ensure_union_member(text, "KitSeedSlug", key)
        text = ensure_record_entry(text, "kitSeedIds", key, deterministic_ulid("kit", key))

    for key in kit_unit_keys:
        text = ensure_union_member(text, "KitUnitSeedSlug", key)
        text = ensure_record_entry(text, "kitUnitSeedIds", key, deterministic_ulid("kit_unit", key))

    ids_path.write_text(text, encoding="utf-8")


def ensure_union_member(text: str, type_name: str, key: str) -> str:
    member = f'  | "{key}"'
    if member in text:
        return text

    pattern = re.compile(rf"type {type_name} =(?P<body>.*?);", flags=re.DOTALL)
    match = pattern.search(text)
    if not match:
        raise ValueError(f"Missing {type_name} union")

    replacement = f'type {type_name} ={match.group("body")}\n{member};'
    return text[: match.start()] + replacement + text[match.end() :]


def ensure_record_entry(text: str, const_name: str, key: str, value: str) -> str:
    pattern = re.compile(
        rf"const {const_name}: Record<[^>]+, string> = \{{(?P<body>.*?)\n\}};",
        flags=re.DOTALL,
    )
    match = pattern.search(text)
    if not match:
        raise ValueError(f"Missing {const_name} record")

    body = match.group("body")
    if re.search(rf'["\']?{re.escape(key)}["\']?:\s*"', body):
        return text

    entry = f'\n  "{key}": "{value}",'
    replacement = f"const {const_name}: Record<{record_type_name(const_name)}, string> = {{{body}{entry}\n}};"
    return text[: match.start()] + replacement + text[match.end() :]


def record_type_name(const_name: str) -> str:
    return {
        "kitSeedIds": "KitSeedSlug",
        "kitUnitSeedIds": "KitUnitSeedSlug",
    }[const_name]


def deterministic_ulid(namespace: str, seed: str) -> str:
    digest = hashlib.sha256(f"{namespace}:{seed}".encode("utf-8")).digest()
    value = int.from_bytes(digest, "big")
    chars: list[str] = []
    for _ in range(23):
        chars.append(CROCKFORD_BASE32[value & 31])
        value >>= 5
    return "01K" + "".join(reversed(chars))


def ts_string(value: str) -> str:
    return json.dumps(value)


def ts_nullable_string(value: str | None) -> str:
    return "null" if value is None else ts_string(value)


def ts_nullable_date(value: str | None) -> str:
    return "null" if value is None else f"new Date({ts_string(value)})"


def identifier_pascal_case(slug: str) -> str:
    parts = re.findall(r"[a-zA-Z0-9]+", slug)
    identifier = "".join(part[:1].upper() + part[1:] for part in parts)
    return f"Seed{identifier}" if not identifier or identifier[0].isdigit() else identifier
