import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { tcgCsvImportedKitsAdeptaSororitasDataset } from "./adepta_sororitas.data";
import { tcgCsvImportedKitsAdeptusCustodesDataset } from "./adeptus_custodes.data";
import { tcgCsvImportedKitsAdeptusMechanicusDataset } from "./adeptus_mechanicus.data";
import { tcgCsvImportedKitsAeldariDataset } from "./aeldari.data";
import { tcgCsvImportedKitsAstraMilitarumDataset } from "./astra_militarum.data";
import { tcgCsvImportedKitsBloodAngelsDataset } from "./blood_angels.data";
import { tcgCsvImportedKitsChaosDaemonsDataset } from "./chaos_daemons.data";
import { tcgCsvImportedKitsChaosKnightsDataset } from "./chaos_knights.data";
import { tcgCsvImportedKitsChaosSpaceMarinesDataset } from "./chaos_space_marines.data";
import { tcgCsvImportedKitsDarkAngelsDataset } from "./dark_angels.data";
import { tcgCsvImportedKitsDeathGuardDataset } from "./death_guard.data";
import { tcgCsvImportedKitsDeathwatchDataset } from "./deathwatch.data";
import { tcgCsvImportedKitsDrukhariDataset } from "./drukhari.data";
import { tcgCsvImportedKitsGenestealerCultsDataset } from "./genestealer_cults.data";
import { tcgCsvImportedKitsGreyKnightsDataset } from "./grey_knights.data";
import { tcgCsvImportedKitsImperialAgentsDataset } from "./imperial_agents.data";
import { tcgCsvImportedKitsImperialFistsDataset } from "./imperial_fists.data";
import { tcgCsvImportedKitsImperialKnightsDataset } from "./imperial_knights.data";
import { tcgCsvImportedKitsNecronsDataset } from "./necrons.data";
import { tcgCsvImportedKitsOrksDataset } from "./orks.data";
import { tcgCsvImportedKitsSpaceMarinesDataset } from "./space_marines.data";
import { tcgCsvImportedKitsSpaceWolvesDataset } from "./space_wolves.data";
import { tcgCsvImportedKitsTauEmpireDataset } from "./tau_empire.data";
import { tcgCsvImportedKitsThousandSonsDataset } from "./thousand_sons.data";
import { tcgCsvImportedKitsTyranidsDataset } from "./tyranids.data";
import { tcgCsvImportedKitsUltramarinesDataset } from "./ultramarines.data";
import { tcgCsvImportedKitsUnassignedDataset } from "./unassigned.data";
import { tcgCsvImportedKitsWhiteScarsDataset } from "./white_scars.data";

/**
 * Aggregates TCGCSV generated seed shards.
 * Generated by scripts/kit_content_importer/applyer.py.
 */
export const tcgCsvImportedKitsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    ...tcgCsvImportedKitsAdeptaSororitasDataset.records,
    ...tcgCsvImportedKitsAdeptusCustodesDataset.records,
    ...tcgCsvImportedKitsAdeptusMechanicusDataset.records,
    ...tcgCsvImportedKitsAeldariDataset.records,
    ...tcgCsvImportedKitsAstraMilitarumDataset.records,
    ...tcgCsvImportedKitsBloodAngelsDataset.records,
    ...tcgCsvImportedKitsChaosDaemonsDataset.records,
    ...tcgCsvImportedKitsChaosKnightsDataset.records,
    ...tcgCsvImportedKitsChaosSpaceMarinesDataset.records,
    ...tcgCsvImportedKitsDarkAngelsDataset.records,
    ...tcgCsvImportedKitsDeathGuardDataset.records,
    ...tcgCsvImportedKitsDeathwatchDataset.records,
    ...tcgCsvImportedKitsDrukhariDataset.records,
    ...tcgCsvImportedKitsGenestealerCultsDataset.records,
    ...tcgCsvImportedKitsGreyKnightsDataset.records,
    ...tcgCsvImportedKitsImperialAgentsDataset.records,
    ...tcgCsvImportedKitsImperialFistsDataset.records,
    ...tcgCsvImportedKitsImperialKnightsDataset.records,
    ...tcgCsvImportedKitsNecronsDataset.records,
    ...tcgCsvImportedKitsOrksDataset.records,
    ...tcgCsvImportedKitsSpaceMarinesDataset.records,
    ...tcgCsvImportedKitsSpaceWolvesDataset.records,
    ...tcgCsvImportedKitsTauEmpireDataset.records,
    ...tcgCsvImportedKitsThousandSonsDataset.records,
    ...tcgCsvImportedKitsTyranidsDataset.records,
    ...tcgCsvImportedKitsUltramarinesDataset.records,
    ...tcgCsvImportedKitsUnassignedDataset.records,
    ...tcgCsvImportedKitsWhiteScarsDataset.records,
  ] satisfies KitConfig[],
};
