import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for adeptus_custodes.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AdeptusCustodesCaptainGeneralTrajannValorisKit: KitConfig = {
  id: kitId("adeptus_custodes_captain_general_trajann_valoris"),
  kit_slug: "adeptus-custodes-captain-general-trajann-valoris",
  kit_name: "Adeptus Custodes: Captain-General Trajann Valoris",
  display_name: "Adeptus Custodes: Captain-General Trajann Valoris",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/158054_200w.jpg",
  gw_product_code: "99120108012",
  gw_short_code: "01-10",
  product_gtin: "5011921094219",
  tcgcsv_product_id: "158054",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/6fh2",
  release_date: null,
  discontinued_date: null,
};


export const AdeptusCustodesCustodianWardensKit: KitConfig = {
  id: kitId("adeptus_custodes_custodian_wardens"),
  kit_slug: "adeptus-custodes-custodian-wardens",
  kit_name: "Adeptus Custodes: Custodian Wardens",
  display_name: "Adeptus Custodes: Custodian Wardens",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/158445_200w.jpg",
  gw_product_code: "99120108013",
  gw_short_code: "01-11",
  product_gtin: "5011921094226",
  tcgcsv_product_id: "158445",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Wnh2",
  release_date: null,
  discontinued_date: null,
};


export const AdeptusCustodesVertusPraetorsKit: KitConfig = {
  id: kitId("adeptus_custodes_vertus_praetors"),
  kit_slug: "adeptus-custodes-vertus-praetors",
  kit_name: "Adeptus Custodes: Vertus Praetors",
  display_name: "Adeptus Custodes: Vertus Praetors",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/158444_200w.jpg",
  gw_product_code: "99120108014",
  gw_short_code: "01-12",
  product_gtin: "5011921094233",
  tcgcsv_product_id: "158444",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Vnh2",
  release_date: null,
  discontinued_date: null,
};


export const TalonsOfTheEmperorValerianAndAleyaKit: KitConfig = {
  id: kitId("talons_of_the_emperor_valerian_and_aleya"),
  kit_slug: "talons-of-the-emperor-valerian-and-aleya",
  kit_name: "Talons of the Emperor: Valerian and Aleya",
  display_name: "Talons of the Emperor: Valerian and Aleya",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279983_200w.jpg",
  gw_product_code: "99120108031",
  gw_short_code: "BL-02",
  product_gtin: "5011921129775",
  tcgcsv_product_id: "279983",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/H_f3",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsAdeptusCustodesDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    AdeptusCustodesCaptainGeneralTrajannValorisKit,
    AdeptusCustodesCustodianWardensKit,
    AdeptusCustodesVertusPraetorsKit,
    TalonsOfTheEmperorValerianAndAleyaKit,
  ] satisfies KitConfig[],
};
