import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for chaos_knights.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ChaosKnightsKnightDesecratorKit: KitConfig = {
  id: kitId("chaos_knights_knight_desecrator"),
  kit_slug: "chaos-knights-knight-desecrator",
  kit_name: "Chaos Knights Knight Desecrator",
  display_name: "Chaos Knights Knight Desecrator",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279701_200w.jpg",
  gw_product_code: null,
  gw_short_code: "43-66",
  product_gtin: null,
  tcgcsv_product_id: "279701",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/2Vf3",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsChaosKnightsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    ChaosKnightsKnightDesecratorKit,
  ] satisfies KitConfig[],
};
