import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for chaos_daemons.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AhrimanArchSorcererOfTzeentchKit: KitConfig = {
  id: kitId("ahriman_arch_sorcerer_of_tzeentch"),
  kit_slug: "ahriman-arch-sorcerer-of-tzeentch",
  kit_name: "Ahriman Arch-Sorcerer of Tzeentch",
  display_name: "Ahriman Arch-Sorcerer of Tzeentch",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140650_200w.jpg",
  gw_product_code: "99120102064",
  gw_short_code: "43-38",
  product_gtin: "5011921079506",
  tcgcsv_product_id: "140650",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/0h82",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsChaosDaemonsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    AhrimanArchSorcererOfTzeentchKit,
  ] satisfies KitConfig[],
};
