import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for dark_angels.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const DarkAngelsCompanyVeteransSquadKit: KitConfig = {
  id: kitId("dark_angels_company_veterans_squad"),
  kit_slug: "dark-angels-company-veterans-squad",
  kit_name: "Dark Angels Company Veterans Squad",
  display_name: "Dark Angels Company Veterans Squad",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140692_200w.jpg",
  gw_product_code: "99120101047",
  gw_short_code: "44-09",
  product_gtin: "5011921907137",
  tcgcsv_product_id: "140692",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Sh82",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsDeathwingCommandSquadKit: KitConfig = {
  id: kitId("dark_angels_deathwing_command_squad"),
  kit_slug: "dark-angels-deathwing-command-squad",
  kit_name: "Dark Angels Deathwing Command Squad",
  display_name: "Dark Angels Deathwing Command Squad",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140693_200w.jpg",
  gw_product_code: "99120101096",
  gw_short_code: "44-10",
  product_gtin: "5011921031627",
  tcgcsv_product_id: "140693",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Th82",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsGauntletTacticalSquadKit: KitConfig = {
  id: kitId("dark_angels_gauntlet_tactical_squad"),
  kit_slug: "dark-angels-gauntlet-tactical-squad",
  kit_name: "Dark Angels Gauntlet Tactical Squad",
  display_name: "Dark Angels Gauntlet Tactical Squad",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140694_200w.jpg",
  gw_product_code: "99120101174",
  gw_short_code: "44-15",
  product_gtin: "5011921080984",
  tcgcsv_product_id: "140694",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Vh82",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsInterrogatorChaplainKit: KitConfig = {
  id: kitId("dark_angels_interrogator_chaplain"),
  kit_slug: "dark-angels-interrogator-chaplain",
  kit_name: "Dark Angels Interrogator-Chaplain",
  display_name: "Dark Angels Interrogator-Chaplain",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141048_200w.jpg",
  gw_product_code: "99070101011",
  gw_short_code: "44-70",
  product_gtin: "5011921060139",
  tcgcsv_product_id: "141048",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/-q82",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsMasterLazarusKit: KitConfig = {
  id: kitId("dark_angels_master_lazarus"),
  kit_slug: "dark-angels-master-lazarus",
  kit_name: "Dark Angels Master Lazarus",
  display_name: "Dark Angels Master Lazarus",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279908_200w.jpg",
  gw_product_code: "99120101267",
  gw_short_code: "44-16",
  product_gtin: "5011921126392",
  tcgcsv_product_id: "279908",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/b-f3",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsPrimarisAggressorsKit: KitConfig = {
  id: kitId("dark_angels_primaris_aggressors"),
  kit_slug: "dark-angels-primaris-aggressors",
  kit_name: "Dark Angels - Primaris Aggressors",
  display_name: "Dark Angels - Primaris Aggressors",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/155096_200w.jpg",
  gw_product_code: "99120101202",
  gw_short_code: "44-74",
  product_gtin: "5011921090945",
  tcgcsv_product_id: "155096",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/X2g2",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsPrimarisHellblastersKit: KitConfig = {
  id: kitId("dark_angels_primaris_hellblasters"),
  kit_slug: "dark-angels-primaris-hellblasters",
  kit_name: "Dark Angels - Primaris Hellblasters",
  display_name: "Dark Angels - Primaris Hellblasters",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/155095_200w.jpg",
  gw_product_code: "99120101203",
  gw_short_code: "44-73",
  product_gtin: "5011921090952",
  tcgcsv_product_id: "155095",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/W2g2",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsPrimarisIntercessorsKit: KitConfig = {
  id: kitId("dark_angels_primaris_intercessors"),
  kit_slug: "dark-angels-primaris-intercessors",
  kit_name: "Dark Angels - Primaris Intercessors",
  display_name: "Dark Angels - Primaris Intercessors",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/155094_200w.jpg",
  gw_product_code: "99120101204",
  gw_short_code: "44-72",
  product_gtin: "5011921090938",
  tcgcsv_product_id: "155094",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/V2g2",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsPrimarisLieutenantZakariahKit: KitConfig = {
  id: kitId("dark_angels_primaris_lieutenant_zakariah"),
  kit_slug: "dark-angels-primaris-lieutenant-zakariah",
  kit_name: "Dark Angels - Primaris Lieutenant Zakariah",
  display_name: "Dark Angels - Primaris Lieutenant Zakariah",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/155092_200w.jpg",
  gw_product_code: "99070101028",
  gw_short_code: "44-71",
  product_gtin: "5011921090921",
  tcgcsv_product_id: "155092",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/S2g2",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsPrimarisUpgradesKit: KitConfig = {
  id: kitId("dark_angels_primaris_upgrades"),
  kit_slug: "dark-angels-primaris-upgrades",
  kit_name: "Dark Angels - Primaris Upgrades",
  display_name: "Dark Angels - Primaris Upgrades",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/155093_200w.jpg",
  gw_product_code: "99070101036",
  gw_short_code: "44-75",
  product_gtin: "5011921094943",
  tcgcsv_product_id: "155093",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/T2g2",
  release_date: null,
  discontinued_date: null,
};


export const DarkAngelsUpgradesKit: KitConfig = {
  id: kitId("dark_angels_upgrades"),
  kit_slug: "dark-angels-upgrades",
  kit_name: "Dark Angels Upgrades",
  display_name: "Dark Angels Upgrades",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141049_200w.jpg",
  gw_product_code: "99070101014",
  gw_short_code: "44-80",
  product_gtin: "5011921060160",
  tcgcsv_product_id: "141049",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/_q82",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsDarkAngelsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    DarkAngelsCompanyVeteransSquadKit,
    DarkAngelsDeathwingCommandSquadKit,
    DarkAngelsGauntletTacticalSquadKit,
    DarkAngelsInterrogatorChaplainKit,
    DarkAngelsMasterLazarusKit,
    DarkAngelsPrimarisAggressorsKit,
    DarkAngelsPrimarisHellblastersKit,
    DarkAngelsPrimarisIntercessorsKit,
    DarkAngelsPrimarisLieutenantZakariahKit,
    DarkAngelsPrimarisUpgradesKit,
    DarkAngelsUpgradesKit,
  ] satisfies KitConfig[],
};
