import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for death_guard.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceDeathGuardInfectionClusterKit: KitConfig = {
  id: kitId("battleforce_death_guard_infection_cluster"),
  kit_slug: "battleforce-death-guard-infection-cluster",
  kit_name: "Battleforce: Death Guard Infection Cluster",
  display_name: "Battleforce: Death Guard Infection Cluster",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/182576_200w.jpg",
  gw_product_code: "99120102085",
  gw_short_code: "71-54",
  product_gtin: "5011921105250",
  tcgcsv_product_id: "182576",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/x2t2",
  release_date: null,
  discontinued_date: null,
};


export const DeathGuardBiologusPutrifierKit: KitConfig = {
  id: kitId("death_guard_biologus_putrifier"),
  kit_slug: "death-guard-biologus-putrifier",
  kit_name: "Death Guard Biologus Putrifier",
  display_name: "Death Guard Biologus Putrifier",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167554_200w.jpg",
  gw_product_code: "99070102005",
  gw_short_code: "43-24",
  product_gtin: "5011921087624",
  tcgcsv_product_id: "167554",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/62m2",
  release_date: null,
  discontinued_date: null,
};


export const DeathGuardFoulBlightspawnKit: KitConfig = {
  id: kitId("death_guard_foul_blightspawn"),
  kit_slug: "death-guard-foul-blightspawn",
  kit_name: "Death Guard Foul Blightspawn",
  display_name: "Death Guard Foul Blightspawn",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167555_200w.jpg",
  gw_product_code: "99070102002",
  gw_short_code: "43-46",
  product_gtin: "5011921080755",
  tcgcsv_product_id: "167555",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/72m2",
  release_date: null,
  discontinued_date: null,
};


export const DeathGuardNauseousRotboneKit: KitConfig = {
  id: kitId("death_guard_nauseous_rotbone"),
  kit_slug: "death-guard-nauseous-rotbone",
  kit_name: "Death Guard Nauseous Rotbone",
  display_name: "Death Guard Nauseous Rotbone",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167556_200w.jpg",
  gw_product_code: "99070102004",
  gw_short_code: "43-29",
  product_gtin: "5011921087617",
  tcgcsv_product_id: "167556",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/82m2",
  release_date: null,
  discontinued_date: null,
};


export const DeathGuardPlagueMarineChampionKit: KitConfig = {
  id: kitId("death_guard_plague_marine_champion"),
  kit_slug: "death-guard-plague-marine-champion",
  kit_name: "Death Guard Plague Marine Champion",
  display_name: "Death Guard Plague Marine Champion",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167557_200w.jpg",
  gw_product_code: "99070102007",
  gw_short_code: "43-48",
  product_gtin: "5011921087648",
  tcgcsv_product_id: "167557",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/92m2",
  release_date: null,
  discontinued_date: null,
};


export const DeathGuardPlagueMarineIconBearerKit: KitConfig = {
  id: kitId("death_guard_plague_marine_icon_bearer"),
  kit_slug: "death-guard-plague-marine-icon-bearer",
  kit_name: "Death Guard Plague Marine Icon Bearer",
  display_name: "Death Guard Plague Marine Icon Bearer",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167558_200w.jpg",
  gw_product_code: "99070102006",
  gw_short_code: "43-47",
  product_gtin: "5011921087631",
  tcgcsv_product_id: "167558",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/b2m2",
  release_date: null,
  discontinued_date: null,
};


export const DeathGuardScribbusWretchTheTallymanKit: KitConfig = {
  id: kitId("death_guard_scribbus_wretch_the_tallyman"),
  kit_slug: "death-guard-scribbus-wretch-the-tallyman",
  kit_name: "Death Guard Scribbus Wretch The Tallyman",
  display_name: "Death Guard Scribbus Wretch The Tallyman",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167559_200w.jpg",
  gw_product_code: "99070102003",
  gw_short_code: "43-45",
  product_gtin: "5011921087600",
  tcgcsv_product_id: "167559",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/c2m2",
  release_date: null,
  discontinued_date: null,
};


export const EasyToBuildDeathGuardPlagueMarinesKit: KitConfig = {
  id: kitId("easy_to_build_death_guard_plague_marines"),
  kit_slug: "easy-to-build-death-guard-plague-marines",
  kit_name: "Easy To Build Death Guard Plague Marines",
  display_name: "Easy To Build Death Guard Plague Marines",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140707_200w.jpg",
  gw_product_code: "99120102070",
  gw_short_code: "43-30",
  product_gtin: "5011921085323",
  tcgcsv_product_id: "140707",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/9j82",
  release_date: null,
  discontinued_date: null,
};


export const EasyToBuildDeathGuardPoxwalkersKit: KitConfig = {
  id: kitId("easy_to_build_death_guard_poxwalkers"),
  kit_slug: "easy-to-build-death-guard-poxwalkers",
  kit_name: "Easy To Build Death Guard Poxwalkers",
  display_name: "Easy To Build Death Guard Poxwalkers",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140708_200w.jpg",
  gw_product_code: "99120102071",
  gw_short_code: "43-41",
  product_gtin: "5011921085330",
  tcgcsv_product_id: "140708",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/bj82",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsDeathGuardDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    BattleforceDeathGuardInfectionClusterKit,
    DeathGuardBiologusPutrifierKit,
    DeathGuardFoulBlightspawnKit,
    DeathGuardNauseousRotboneKit,
    DeathGuardPlagueMarineChampionKit,
    DeathGuardPlagueMarineIconBearerKit,
    DeathGuardScribbusWretchTheTallymanKit,
    EasyToBuildDeathGuardPlagueMarinesKit,
    EasyToBuildDeathGuardPoxwalkersKit,
  ] satisfies KitConfig[],
};
