import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for drukhari.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceDrukhariPoisonbladeRaidingPartyKit: KitConfig = {
  id: kitId("battleforce_drukhari_poisonblade_raiding_party"),
  kit_slug: "battleforce-drukhari-poisonblade-raiding-party",
  kit_name: "Battleforce: Drukhari Poisonblade Raiding Party",
  display_name: "Battleforce: Drukhari Poisonblade Raiding Party",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279510_200w.jpg",
  gw_product_code: "99120112039",
  gw_short_code: "71-89",
  product_gtin: "5011921121618",
  tcgcsv_product_id: "279510",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/dQf3",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarArchonKit: KitConfig = {
  id: kitId("dark_eldar_archon"),
  kit_slug: "dark-eldar-archon",
  kit_name: "Dark Eldar Archon",
  display_name: "Dark Eldar Archon",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141050_200w.jpg",
  gw_product_code: "99070112001",
  gw_short_code: "45-22",
  product_gtin: "5011921054541",
  tcgcsv_product_id: "141050",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/0r82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarHaemonculusKit: KitConfig = {
  id: kitId("dark_eldar_haemonculus"),
  kit_slug: "dark-eldar-haemonculus",
  kit_name: "Dark Eldar Haemonculus",
  display_name: "Dark Eldar Haemonculus",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141051_200w.jpg",
  gw_product_code: "99070112002",
  gw_short_code: "45-21",
  product_gtin: "5011921054558",
  tcgcsv_product_id: "141051",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/2r82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarKabaliteWarriorsKit: KitConfig = {
  id: kitId("dark_eldar_kabalite_warriors"),
  kit_slug: "dark-eldar-kabalite-warriors",
  kit_name: "Dark Eldar Kabalite Warriors",
  display_name: "Dark Eldar Kabalite Warriors",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140696_200w.jpg",
  gw_product_code: "99120112007",
  gw_short_code: "45-07",
  product_gtin: "5011921020225",
  tcgcsv_product_id: "140696",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Xh82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarRaiderKit: KitConfig = {
  id: kitId("dark_eldar_raider"),
  kit_slug: "dark-eldar-raider",
  kit_name: "Dark Eldar Raider",
  display_name: "Dark Eldar Raider",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140697_200w.jpg",
  gw_product_code: "99120112012",
  gw_short_code: "45-10",
  product_gtin: "5011921020393",
  tcgcsv_product_id: "140697",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Zh82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarScourgesKit: KitConfig = {
  id: kitId("dark_eldar_scourges"),
  kit_slug: "dark-eldar-scourges",
  kit_name: "Dark Eldar Scourges",
  display_name: "Dark Eldar Scourges",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140698_200w.jpg",
  gw_product_code: "99120112014",
  gw_short_code: "45-16",
  product_gtin: "5011921022885",
  tcgcsv_product_id: "140698",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/-h82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarTalosPainEngineKit: KitConfig = {
  id: kitId("dark_eldar_talos_pain_engine"),
  kit_slug: "dark-eldar-talos-pain-engine",
  kit_name: "Dark Eldar Talos Pain Engine",
  display_name: "Dark Eldar Talos Pain Engine",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140699_200w.jpg",
  gw_product_code: "99120112016",
  gw_short_code: "45-11",
  product_gtin: "5011921022984",
  tcgcsv_product_id: "140699",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/_h82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarVenomKit: KitConfig = {
  id: kitId("dark_eldar_venom"),
  kit_slug: "dark-eldar-venom",
  kit_name: "Dark Eldar Venom",
  display_name: "Dark Eldar Venom",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140700_200w.jpg",
  gw_product_code: "99120112013",
  gw_short_code: "45-18",
  product_gtin: "5011921022892",
  tcgcsv_product_id: "140700",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/0j82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarVoidravenBomberKit: KitConfig = {
  id: kitId("dark_eldar_voidraven_bomber"),
  kit_slug: "dark-eldar-voidraven-bomber",
  kit_name: "Dark Eldar Voidraven Bomber",
  display_name: "Dark Eldar Voidraven Bomber",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140701_200w.jpg",
  gw_product_code: "99120112020",
  gw_short_code: "45-19",
  product_gtin: "5011921054473",
  tcgcsv_product_id: "140701",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/2j82",
  release_date: null,
  discontinued_date: null,
};


export const DarkEldarWracksKit: KitConfig = {
  id: kitId("dark_eldar_wracks"),
  kit_slug: "dark-eldar-wracks",
  kit_name: "Dark Eldar Wracks",
  display_name: "Dark Eldar Wracks",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140702_200w.jpg",
  gw_product_code: "99120112021",
  gw_short_code: "45-20",
  product_gtin: "5011921054466",
  tcgcsv_product_id: "140702",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/3j82",
  release_date: null,
  discontinued_date: null,
};


export const DrukhariDrazharMasterOfBladesKit: KitConfig = {
  id: kitId("drukhari_drazhar_master_of_blades"),
  kit_slug: "drukhari-drazhar-master-of-blades",
  kit_name: "Drukhari Drazhar, Master of Blades",
  display_name: "Drukhari Drazhar, Master of Blades",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/281201_200w.jpg",
  gw_product_code: "99120112040",
  gw_short_code: "45-41",
  product_gtin: "5011921127504",
  tcgcsv_product_id: "281201",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/2vg3",
  release_date: null,
  discontinued_date: null,
};


export const DrukhariIncubiKit: KitConfig = {
  id: kitId("drukhari_incubi"),
  kit_slug: "drukhari-incubi",
  kit_name: "Drukhari Incubi",
  display_name: "Drukhari Incubi",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279985_200w.jpg",
  gw_product_code: "99120112041",
  gw_short_code: "45-40",
  product_gtin: "5011921127511",
  tcgcsv_product_id: "279985",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/K_f3",
  release_date: null,
  discontinued_date: null,
};


export const DrukhariSuccubusKit: KitConfig = {
  id: kitId("drukhari_succubus"),
  kit_slug: "drukhari-succubus",
  kit_name: "Drukhari Succubus",
  display_name: "Drukhari Succubus",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167560_200w.jpg",
  gw_product_code: "99070112006",
  gw_short_code: "45-23",
  product_gtin: "5011921087358",
  tcgcsv_product_id: "167560",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/d2m2",
  release_date: null,
  discontinued_date: null,
};


export const StartCollectingDarkEldarKit: KitConfig = {
  id: kitId("start_collecting_dark_eldar"),
  kit_slug: "start-collecting-dark-eldar",
  kit_name: "Start Collecting! Dark Eldar",
  display_name: "Start Collecting! Dark Eldar",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140835_200w.jpg",
  gw_product_code: "99120112024",
  gw_short_code: "70-45",
  product_gtin: "5011921075140",
  tcgcsv_product_id: "140835",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Kl82",
  release_date: null,
  discontinued_date: null,
};


export const StartCollectingDrukhariKit: KitConfig = {
  id: kitId("start_collecting_drukhari"),
  kit_slug: "start-collecting-drukhari",
  kit_name: "Start Collecting! Drukhari",
  display_name: "Start Collecting! Drukhari",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/164655_200w.jpg",
  gw_product_code: "99120112036",
  gw_short_code: "70-44",
  product_gtin: "5011921094271",
  tcgcsv_product_id: "164655",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/7Tk2",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsDrukhariDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    BattleforceDrukhariPoisonbladeRaidingPartyKit,
    DarkEldarArchonKit,
    DarkEldarHaemonculusKit,
    DarkEldarKabaliteWarriorsKit,
    DarkEldarRaiderKit,
    DarkEldarScourgesKit,
    DarkEldarTalosPainEngineKit,
    DarkEldarVenomKit,
    DarkEldarVoidravenBomberKit,
    DarkEldarWracksKit,
    DrukhariDrazharMasterOfBladesKit,
    DrukhariIncubiKit,
    DrukhariSuccubusKit,
    StartCollectingDarkEldarKit,
    StartCollectingDrukhariKit,
  ] satisfies KitConfig[],
};
