import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for grey_knights.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const GreyKnightsGrandMasterVoldusKit: KitConfig = {
  id: kitId("grey_knights_grand_master_voldus"),
  kit_slug: "grey-knights-grand-master-voldus",
  kit_name: "Grey Knights Grand Master Voldus",
  display_name: "Grey Knights Grand Master Voldus",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/167561_200w.jpg",
  gw_product_code: "99070107001",
  gw_short_code: "57-11",
  product_gtin: "5011921088591",
  tcgcsv_product_id: "167561",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/f2m2",
  release_date: null,
  discontinued_date: null,
};


export const GreyKnightsNemesisDreadknightKit: KitConfig = {
  id: kitId("grey_knights_nemesis_dreadknight"),
  kit_slug: "grey-knights-nemesis-dreadknight",
  kit_name: "Grey Knights Nemesis Dreadknight",
  display_name: "Grey Knights Nemesis Dreadknight",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140731_200w.jpg",
  gw_product_code: "99120107008",
  gw_short_code: "57-10",
  product_gtin: "5011921053582",
  tcgcsv_product_id: "140731",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Fj82",
  release_date: null,
  discontinued_date: null,
};


export const GreyKnightsPaladinSquadKit: KitConfig = {
  id: kitId("grey_knights_paladin_squad"),
  kit_slug: "grey-knights-paladin-squad",
  kit_name: "Grey Knights Paladin Squad",
  display_name: "Grey Knights Paladin Squad",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140732_200w.jpg",
  gw_product_code: "99120107009",
  gw_short_code: "57-09",
  product_gtin: "5011921053575",
  tcgcsv_product_id: "140732",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Gj82",
  release_date: null,
  discontinued_date: null,
};


export const GreyKnightsStrikeSquadKit: KitConfig = {
  id: kitId("grey_knights_strike_squad"),
  kit_slug: "grey-knights-strike-squad",
  kit_name: "Grey Knights Strike Squad",
  display_name: "Grey Knights Strike Squad",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/140733_200w.jpg",
  gw_product_code: "99120107006",
  gw_short_code: "57-08",
  product_gtin: "5011921053544",
  tcgcsv_product_id: "140733",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Hj82",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsGreyKnightsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    GreyKnightsGrandMasterVoldusKit,
    GreyKnightsNemesisDreadknightKit,
    GreyKnightsPaladinSquadKit,
    GreyKnightsStrikeSquadKit,
  ] satisfies KitConfig[],
};
