import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for imperial_knights.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseImperialKnightsSuperHeavyDetachmentKit: KitConfig = {
  id: kitId("apocalypse_imperial_knights_super_heavy_detachment"),
  kit_slug: "apocalypse-imperial-knights-super-heavy-detachment",
  kit_name: "Apocalypse: Imperial Knights Super Heavy Detachment",
  display_name: "Apocalypse: Imperial Knights Super Heavy Detachment",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279681_200w.jpg",
  gw_product_code: null,
  gw_short_code: "54-19",
  product_gtin: null,
  tcgcsv_product_id: "279681",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/FTf3",
  release_date: null,
  discontinued_date: null,
};


export const ImperialKnightsArmigerHelverinsKit: KitConfig = {
  id: kitId("imperial_knights_armiger_helverins"),
  kit_slug: "imperial-knights-armiger-helverins",
  kit_name: "Imperial Knights - Armiger Helverins",
  display_name: "Imperial Knights - Armiger Helverins",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/169622_200w.jpg",
  gw_product_code: "99120108015",
  gw_short_code: "54-13",
  product_gtin: "5011921095674",
  tcgcsv_product_id: "169622",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/sSm2",
  release_date: null,
  discontinued_date: null,
};


export const ImperialKnightsArmigerWarglaivesKit: KitConfig = {
  id: kitId("imperial_knights_armiger_warglaives"),
  kit_slug: "imperial-knights-armiger-warglaives",
  kit_name: "Imperial Knights - Armiger Warglaives",
  display_name: "Imperial Knights - Armiger Warglaives",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/169635_200w.jpg",
  gw_product_code: "99120108019",
  gw_short_code: "54-17",
  product_gtin: "5011921098484",
  tcgcsv_product_id: "169635",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/KSm2",
  release_date: null,
  discontinued_date: null,
};


export const ImperialKnightsKnightCastellanKit: KitConfig = {
  id: kitId("imperial_knights_knight_castellan"),
  kit_slug: "imperial-knights-knight-castellan",
  kit_name: "Imperial Knights - Knight Castellan",
  display_name: "Imperial Knights - Knight Castellan",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/169620_200w.jpg",
  gw_product_code: "99120108016",
  gw_short_code: "54-16",
  product_gtin: "5011921095681",
  tcgcsv_product_id: "169620",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/qSm2",
  release_date: null,
  discontinued_date: null,
};


export const ImperialKnightsKnightPreceptorCanisRexKit: KitConfig = {
  id: kitId("imperial_knights_knight_preceptor_canis_rex"),
  kit_slug: "imperial-knights-knight-preceptor-canis-rex",
  kit_name: "Imperial Knights - Knight Preceptor Canis Rex",
  display_name: "Imperial Knights - Knight Preceptor Canis Rex",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/178736_200w.jpg",
  gw_product_code: "99120108017",
  gw_short_code: "54-15",
  product_gtin: "501192109569-8",
  tcgcsv_product_id: "178736",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/Lvr2",
  release_date: null,
  discontinued_date: null,
};


export const ImperialKnightsKnightValiantKit: KitConfig = {
  id: kitId("imperial_knights_knight_valiant"),
  kit_slug: "imperial-knights-knight-valiant",
  kit_name: "Imperial Knights - Knight Valiant",
  display_name: "Imperial Knights - Knight Valiant",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/169621_200w.jpg",
  gw_product_code: "99120108018",
  gw_short_code: "54-14",
  product_gtin: "5011921095704",
  tcgcsv_product_id: "169621",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/rSm2",
  release_date: null,
  discontinued_date: null,
};


export const ImperialKnightsRenegadeKit: KitConfig = {
  id: kitId("imperial_knights_renegade"),
  kit_slug: "imperial-knights-renegade",
  kit_name: "Imperial Knights: Renegade",
  display_name: "Imperial Knights: Renegade",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/169618_200w.jpg",
  gw_product_code: "60010699011",
  gw_short_code: "REN-60",
  product_gtin: "5011921100293",
  tcgcsv_product_id: "169618",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/nSm2",
  release_date: null,
  discontinued_date: null,
};


export const SectorMechanicusSacristanForgeshrineKit: KitConfig = {
  id: kitId("sector_mechanicus_sacristan_forgeshrine"),
  kit_slug: "sector-mechanicus-sacristan-forgeshrine",
  kit_name: "Sector Mechanicus - Sacristan Forgeshrine",
  display_name: "Sector Mechanicus - Sacristan Forgeshrine",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/169630_200w.jpg",
  gw_product_code: "99120199066",
  gw_short_code: "64-74",
  product_gtin: "5011921098606",
  tcgcsv_product_id: "169630",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/DSm2",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsImperialKnightsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    ApocalypseImperialKnightsSuperHeavyDetachmentKit,
    ImperialKnightsArmigerHelverinsKit,
    ImperialKnightsArmigerWarglaivesKit,
    ImperialKnightsKnightCastellanKit,
    ImperialKnightsKnightPreceptorCanisRexKit,
    ImperialKnightsKnightValiantKit,
    ImperialKnightsRenegadeKit,
    SectorMechanicusSacristanForgeshrineKit,
  ] satisfies KitConfig[],
};
