import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for imperial_fists.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceImperialFistsSupremacyForceKit: KitConfig = {
  id: kitId("battleforce_imperial_fists_supremacy_force"),
  kit_slug: "battleforce-imperial-fists-supremacy-force",
  kit_name: "Battleforce: Imperial Fists Supremacy Force",
  display_name: "Battleforce: Imperial Fists Supremacy Force",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/182572_200w.jpg",
  gw_product_code: "99120101241",
  gw_short_code: "71-57",
  product_gtin: "5011921105274",
  tcgcsv_product_id: "182572",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/s2t2",
  release_date: null,
  discontinued_date: null,
};


export const ImperialFistsPrimarisUpgradesTransferssalamandersAdraxAgatoneKit: KitConfig = {
  id: kitId("imperial_fists_primaris_upgrades_transferssalamanders_adrax_agatone"),
  kit_slug: "imperial-fists-primaris-upgrades-transferssalamanders-adrax-agatone",
  kit_name: "Imperial Fists: Primaris Upgrades & TransfersSalamanders: Adrax Agatone",
  display_name: "Imperial Fists: Primaris Upgrades & TransfersSalamanders: Adrax Agatone",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279416_200w.jpg",
  gw_product_code: null,
  gw_short_code: "48-58",
  product_gtin: null,
  tcgcsv_product_id: "279416",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/lNf3",
  release_date: null,
  discontinued_date: null,
};


export const ImperialFistsTorGaradonKit: KitConfig = {
  id: kitId("imperial_fists_tor_garadon"),
  kit_slug: "imperial-fists-tor-garadon",
  kit_name: "Imperial Fists: Tor Garadon",
  display_name: "Imperial Fists: Tor Garadon",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279414_200w.jpg",
  gw_product_code: null,
  gw_short_code: "48-91",
  product_gtin: null,
  tcgcsv_product_id: "279414",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/jNf3",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsImperialFistsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    BattleforceImperialFistsSupremacyForceKit,
    ImperialFistsPrimarisUpgradesTransferssalamandersAdraxAgatoneKit,
    ImperialFistsTorGaradonKit,
  ] satisfies KitConfig[],
};
