import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for imperial_agents.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const EphraelSternKyganilKit: KitConfig = {
  id: kitId("ephrael_stern_kyganil"),
  kit_slug: "ephrael-stern-kyganil",
  kit_name: "Ephrael Stern & Kyganil",
  display_name: "Ephrael Stern & Kyganil",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/454287_200w.jpg",
  gw_product_code: "99120199073",
  gw_short_code: "40-50",
  product_gtin: "5011921135783",
  tcgcsv_product_id: "454287",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/MKF5",
  release_date: null,
  discontinued_date: null,
};


export const LordInquisitorKyriaDraxusKit: KitConfig = {
  id: kitId("lord_inquisitor_kyria_draxus"),
  kit_slug: "lord-inquisitor-kyria-draxus",
  kit_name: "Lord Inquisitor Kyria Draxus",
  display_name: "Lord Inquisitor Kyria Draxus",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/454286_200w.jpg",
  gw_product_code: "99120108043",
  gw_short_code: "52-42",
  product_gtin: "5011921136971",
  tcgcsv_product_id: "454286",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/LKF5",
  release_date: null,
  discontinued_date: null,
};


export const OfficioAssassinorumCallidusAssassinKit: KitConfig = {
  id: kitId("officio_assassinorum_callidus_assassin"),
  kit_slug: "officio-assassinorum-callidus-assassin",
  kit_name: "Officio Assassinorum Callidus Assassin",
  display_name: "Officio Assassinorum Callidus Assassin",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141061_200w.jpg",
  gw_product_code: "99070108003",
  gw_short_code: "52-12",
  product_gtin: "5011921066476",
  tcgcsv_product_id: "141061",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/fr82",
  release_date: null,
  discontinued_date: null,
};


export const OfficioAssassinorumCulexusAssassinKit: KitConfig = {
  id: kitId("officio_assassinorum_culexus_assassin"),
  kit_slug: "officio-assassinorum-culexus-assassin",
  kit_name: "Officio Assassinorum Culexus Assassin",
  display_name: "Officio Assassinorum Culexus Assassin",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141062_200w.jpg",
  gw_product_code: "99070108002",
  gw_short_code: "52-11",
  product_gtin: "5011921066469",
  tcgcsv_product_id: "141062",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/gr82",
  release_date: null,
  discontinued_date: null,
};


export const OfficioAssassinorumEversorAssassinKit: KitConfig = {
  id: kitId("officio_assassinorum_eversor_assassin"),
  kit_slug: "officio-assassinorum-eversor-assassin",
  kit_name: "Officio Assassinorum Eversor Assassin",
  display_name: "Officio Assassinorum Eversor Assassin",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141063_200w.jpg",
  gw_product_code: "99070108004",
  gw_short_code: "52-13",
  product_gtin: "5011921066483",
  tcgcsv_product_id: "141063",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/hr82",
  release_date: null,
  discontinued_date: null,
};


export const OfficioAssassinorumVindicareAssassinKit: KitConfig = {
  id: kitId("officio_assassinorum_vindicare_assassin"),
  kit_slug: "officio-assassinorum-vindicare-assassin",
  kit_name: "Officio Assassinorum Vindicare Assassin",
  display_name: "Officio Assassinorum Vindicare Assassin",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141064_200w.jpg",
  gw_product_code: "99070108001",
  gw_short_code: "52-10",
  product_gtin: "5011921987924",
  tcgcsv_product_id: "141064",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/jr82",
  release_date: null,
  discontinued_date: null,
};


export const OfficioPrefectusCommissarKit: KitConfig = {
  id: kitId("officio_prefectus_commissar"),
  kit_slug: "officio-prefectus-commissar",
  kit_name: "Officio Prefectus Commissar",
  display_name: "Officio Prefectus Commissar",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141065_200w.jpg",
  gw_product_code: "99070105001",
  gw_short_code: "47-20",
  product_gtin: "5011921997640",
  tcgcsv_product_id: "141065",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/kr82",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsImperialAgentsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    EphraelSternKyganilKit,
    LordInquisitorKyriaDraxusKit,
    OfficioAssassinorumCallidusAssassinKit,
    OfficioAssassinorumCulexusAssassinKit,
    OfficioAssassinorumEversorAssassinKit,
    OfficioAssassinorumVindicareAssassinKit,
    OfficioPrefectusCommissarKit,
  ] satisfies KitConfig[],
};
