import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for ultramarines.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const UltramarinesChiefLibrarianTiguriusKit: KitConfig = {
  id: kitId("ultramarines_chief_librarian_tigurius"),
  kit_slug: "ultramarines-chief-librarian-tigurius",
  kit_name: "Ultramarines Chief Librarian Tigurius",
  display_name: "Ultramarines Chief Librarian Tigurius",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279754_200w.jpg",
  gw_product_code: "99120101254",
  gw_short_code: "48-100",
  product_gtin: "5011921119776",
  tcgcsv_product_id: "279754",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/6Wf3",
  release_date: null,
  discontinued_date: null,
};


export const UltramarinesUpgradesKit: KitConfig = {
  id: kitId("ultramarines_upgrades"),
  kit_slug: "ultramarines-upgrades",
  kit_name: "Ultramarines Upgrades",
  display_name: "Ultramarines Upgrades",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/141073_200w.jpg",
  gw_product_code: "99070101015",
  gw_short_code: "48-80",
  product_gtin: "5011921060177",
  tcgcsv_product_id: "141073",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/tr82",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsUltramarinesDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    UltramarinesChiefLibrarianTiguriusKit,
    UltramarinesUpgradesKit,
  ] satisfies KitConfig[],
};
