import type {
  KitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitTypeId } from "../../../ids";

/**
 * Imported purchasable kit rows from TCGCSV catalog data for white_scars.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const WhiteScarsKorsarroKhanKit: KitConfig = {
  id: kitId("white_scars_korsarro_khan"),
  kit_slug: "white-scars-korsarro-khan",
  kit_name: "White Scars Kor'sarro Khan",
  display_name: "White Scars Kor'sarro Khan",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279755_200w.jpg",
  gw_product_code: "99120101255",
  gw_short_code: "48-88",
  product_gtin: "5011921119868",
  tcgcsv_product_id: "279755",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/7Wf3",
  release_date: null,
  discontinued_date: null,
};


export const WhiteScarsPrimarisUpgradesTransfersKit: KitConfig = {
  id: kitId("white_scars_primaris_upgrades_transfers"),
  kit_slug: "white-scars-primaris-upgrades-transfers",
  kit_name: "White Scars Primaris Upgrades & Transfers",
  display_name: "White Scars Primaris Upgrades & Transfers",
  gw_slug: null,
  gw_short_slug: null,
  gw_year: null,
  model_count: null,
  kit_type_id: kitTypeId("catalog_product_unknown_contents"),
  gw_product_url: null,
  gw_image_url: "https://tcgplayer-cdn.tcgplayer.com/product/279761_200w.jpg",
  gw_product_code: "99070101040",
  gw_short_code: "48-54",
  product_gtin: "5011921118618",
  tcgcsv_product_id: "279761",
  tcgcsv_product_url: "https://cpt.tcgcsv.com/fWf3",
  release_date: null,
  discontinued_date: null,
};


export const tcgCsvImportedKitsWhiteScarsDataset: SeedDataset<"kits"> = {
  table: "kits",
  records: [
    WhiteScarsKorsarroKhanKit,
    WhiteScarsPrimarisUpgradesTransfersKit,
  ] satisfies KitConfig[],
};
