import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { tcgCsvImportedKitPricesAdeptaSororitasDataset } from "./adepta_sororitas.data";
import { tcgCsvImportedKitPricesAdeptusCustodesDataset } from "./adeptus_custodes.data";
import { tcgCsvImportedKitPricesAdeptusMechanicusDataset } from "./adeptus_mechanicus.data";
import { tcgCsvImportedKitPricesAeldariDataset } from "./aeldari.data";
import { tcgCsvImportedKitPricesAstraMilitarumDataset } from "./astra_militarum.data";
import { tcgCsvImportedKitPricesBloodAngelsDataset } from "./blood_angels.data";
import { tcgCsvImportedKitPricesChaosDaemonsDataset } from "./chaos_daemons.data";
import { tcgCsvImportedKitPricesChaosKnightsDataset } from "./chaos_knights.data";
import { tcgCsvImportedKitPricesChaosSpaceMarinesDataset } from "./chaos_space_marines.data";
import { tcgCsvImportedKitPricesDarkAngelsDataset } from "./dark_angels.data";
import { tcgCsvImportedKitPricesDeathGuardDataset } from "./death_guard.data";
import { tcgCsvImportedKitPricesDeathwatchDataset } from "./deathwatch.data";
import { tcgCsvImportedKitPricesDrukhariDataset } from "./drukhari.data";
import { tcgCsvImportedKitPricesGenestealerCultsDataset } from "./genestealer_cults.data";
import { tcgCsvImportedKitPricesGreyKnightsDataset } from "./grey_knights.data";
import { tcgCsvImportedKitPricesImperialAgentsDataset } from "./imperial_agents.data";
import { tcgCsvImportedKitPricesImperialFistsDataset } from "./imperial_fists.data";
import { tcgCsvImportedKitPricesImperialKnightsDataset } from "./imperial_knights.data";
import { tcgCsvImportedKitPricesNecronsDataset } from "./necrons.data";
import { tcgCsvImportedKitPricesOrksDataset } from "./orks.data";
import { tcgCsvImportedKitPricesSpaceMarinesDataset } from "./space_marines.data";
import { tcgCsvImportedKitPricesSpaceWolvesDataset } from "./space_wolves.data";
import { tcgCsvImportedKitPricesTauEmpireDataset } from "./tau_empire.data";
import { tcgCsvImportedKitPricesThousandSonsDataset } from "./thousand_sons.data";
import { tcgCsvImportedKitPricesTyranidsDataset } from "./tyranids.data";
import { tcgCsvImportedKitPricesUltramarinesDataset } from "./ultramarines.data";
import { tcgCsvImportedKitPricesUnassignedDataset } from "./unassigned.data";
import { tcgCsvImportedKitPricesWhiteScarsDataset } from "./white_scars.data";

/**
 * Aggregates generated source-backed seed shards.
 * Generated by scripts/kit_content_importer/applyer.py.
 */
export const tcgCsvImportedKitPricesDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ...tcgCsvImportedKitPricesAdeptaSororitasDataset.records,
    ...tcgCsvImportedKitPricesAdeptusCustodesDataset.records,
    ...tcgCsvImportedKitPricesAdeptusMechanicusDataset.records,
    ...tcgCsvImportedKitPricesAeldariDataset.records,
    ...tcgCsvImportedKitPricesAstraMilitarumDataset.records,
    ...tcgCsvImportedKitPricesBloodAngelsDataset.records,
    ...tcgCsvImportedKitPricesChaosDaemonsDataset.records,
    ...tcgCsvImportedKitPricesChaosKnightsDataset.records,
    ...tcgCsvImportedKitPricesChaosSpaceMarinesDataset.records,
    ...tcgCsvImportedKitPricesDarkAngelsDataset.records,
    ...tcgCsvImportedKitPricesDeathGuardDataset.records,
    ...tcgCsvImportedKitPricesDeathwatchDataset.records,
    ...tcgCsvImportedKitPricesDrukhariDataset.records,
    ...tcgCsvImportedKitPricesGenestealerCultsDataset.records,
    ...tcgCsvImportedKitPricesGreyKnightsDataset.records,
    ...tcgCsvImportedKitPricesImperialAgentsDataset.records,
    ...tcgCsvImportedKitPricesImperialFistsDataset.records,
    ...tcgCsvImportedKitPricesImperialKnightsDataset.records,
    ...tcgCsvImportedKitPricesNecronsDataset.records,
    ...tcgCsvImportedKitPricesOrksDataset.records,
    ...tcgCsvImportedKitPricesSpaceMarinesDataset.records,
    ...tcgCsvImportedKitPricesSpaceWolvesDataset.records,
    ...tcgCsvImportedKitPricesTauEmpireDataset.records,
    ...tcgCsvImportedKitPricesThousandSonsDataset.records,
    ...tcgCsvImportedKitPricesTyranidsDataset.records,
    ...tcgCsvImportedKitPricesUltramarinesDataset.records,
    ...tcgCsvImportedKitPricesUnassignedDataset.records,
    ...tcgCsvImportedKitPricesWhiteScarsDataset.records,
  ] satisfies KitPriceConfig[],
};
