import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for adeptus_custodes.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AdeptusCustodesCaptainGeneralTrajannValorisTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_custodes_captain_general_trajann_valoris__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_custodes_captain_general_trajann_valoris"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6fh2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusCustodesCustodianWardensTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_custodes_custodian_wardens__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_custodes_custodian_wardens"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wnh2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusCustodesCustodianWardensTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_custodes_custodian_wardens__tcgcsv_low_usd"),
  kit_id: kitId("adeptus_custodes_custodian_wardens"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wnh2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusCustodesCustodianWardensTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_custodes_custodian_wardens__tcgcsv_mid_usd"),
  kit_id: kitId("adeptus_custodes_custodian_wardens"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wnh2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusCustodesCustodianWardensTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_custodes_custodian_wardens__tcgcsv_high_usd"),
  kit_id: kitId("adeptus_custodes_custodian_wardens"),
  currency: "usd",
  price: "69.99",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wnh2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusCustodesVertusPraetorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_custodes_vertus_praetors__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_custodes_vertus_praetors"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vnh2",
  observed_date: null,
  superseded_date: null,
};


export const TalonsOfTheEmperorValerianAndAleyaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("talons_of_the_emperor_valerian_and_aleya__tcgcsv_msrp_usd"),
  kit_id: kitId("talons_of_the_emperor_valerian_and_aleya"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/H_f3",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesAdeptusCustodesDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AdeptusCustodesCaptainGeneralTrajannValorisTcgcsvMsrpUsdKitPrice,
    AdeptusCustodesCustodianWardensTcgcsvMsrpUsdKitPrice,
    AdeptusCustodesCustodianWardensTcgcsvLowUsdKitPrice,
    AdeptusCustodesCustodianWardensTcgcsvMidUsdKitPrice,
    AdeptusCustodesCustodianWardensTcgcsvHighUsdKitPrice,
    AdeptusCustodesVertusPraetorsTcgcsvMsrpUsdKitPrice,
    TalonsOfTheEmperorValerianAndAleyaTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
