import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for adepta_sororitas.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AdeptaSororitasArcoFlagellantsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_arco_flagellants__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_arco_flagellants"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasBattleSanctumTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_battle_sanctum__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_battle_sanctum"),
  currency: "usd",
  price: "110.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Svg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasBattleSistersSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_battle_sisters_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_battle_sisters_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/d-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasBattleSistersSquadTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_battle_sisters_squad__tcgcsv_low_usd"),
  kit_id: kitId("adepta_sororitas_battle_sisters_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/d-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasBattleSistersSquadTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_battle_sisters_squad__tcgcsv_mid_usd"),
  kit_id: kitId("adepta_sororitas_battle_sisters_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/d-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasBattleSistersSquadTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_battle_sisters_squad__tcgcsv_high_usd"),
  kit_id: kitId("adepta_sororitas_battle_sisters_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/d-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasCanonessTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_canoness__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_canoness"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lvg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasCelestineTheLivingSaintTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_celestine_the_living_saint__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_celestine_the_living_saint"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8fh2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasDialogusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_dialogus__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_dialogus"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Pvg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasExorcistTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_exorcist__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_exorcist"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasHospitallerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_hospitaller__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_hospitaller"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasImmolatorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_immolator__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_immolator"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hvg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasJunithEruitaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_junith_eruita__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_junith_eruita"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasPenitentEnginesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_penitent_engines__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_penitent_engines"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasRepentiaSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_repentia_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_repentia_squad"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Fvg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasRetributorSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_retributor_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_retributor_squad"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/f-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasRetributorSquadTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_retributor_squad__tcgcsv_low_usd"),
  kit_id: kitId("adepta_sororitas_retributor_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/f-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasRetributorSquadTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_retributor_squad__tcgcsv_mid_usd"),
  kit_id: kitId("adepta_sororitas_retributor_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/f-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasRetributorSquadTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_retributor_squad__tcgcsv_high_usd"),
  kit_id: kitId("adepta_sororitas_retributor_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/f-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasRhinoTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_rhino__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_rhino"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vvg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasSeraphimSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_seraphim_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_seraphim_squad"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Bvg3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasSisterSuperiorAmaliaNovenaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_sister_superior_amalia_novena__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_sister_superior_amalia_novena"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/c3B2",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasSistersOfBattleTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_sisters_of_battle__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_sisters_of_battle"),
  currency: "usd",
  price: "210.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/WPf3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptaSororitasTheTriumphOfStKatherineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adepta_sororitas_the_triumph_of_st_katherine__tcgcsv_msrp_usd"),
  kit_id: kitId("adepta_sororitas_the_triumph_of_st_katherine"),
  currency: "usd",
  price: "110.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/g-f3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusSororitasImagifierTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_sororitas_imagifier__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_sororitas_imagifier"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Qvg3",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesAdeptaSororitasDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AdeptaSororitasArcoFlagellantsTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasBattleSanctumTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasBattleSistersSquadTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasBattleSistersSquadTcgcsvLowUsdKitPrice,
    AdeptaSororitasBattleSistersSquadTcgcsvMidUsdKitPrice,
    AdeptaSororitasBattleSistersSquadTcgcsvHighUsdKitPrice,
    AdeptaSororitasCanonessTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasCelestineTheLivingSaintTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasDialogusTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasExorcistTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasHospitallerTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasImmolatorTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasJunithEruitaTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasPenitentEnginesTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasRepentiaSquadTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasRetributorSquadTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasRetributorSquadTcgcsvLowUsdKitPrice,
    AdeptaSororitasRetributorSquadTcgcsvMidUsdKitPrice,
    AdeptaSororitasRetributorSquadTcgcsvHighUsdKitPrice,
    AdeptaSororitasRhinoTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasSeraphimSquadTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasSisterSuperiorAmaliaNovenaTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasSistersOfBattleTcgcsvMsrpUsdKitPrice,
    AdeptaSororitasTheTriumphOfStKatherineTcgcsvMsrpUsdKitPrice,
    AdeptusSororitasImagifierTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
