import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for adeptus_mechanicus.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AdeptusMechanicusArchaeopterTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_archaeopter__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_archaeopter"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "100.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8HF5",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusElectroPriestsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_electro_priests__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_electro_priests"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "41.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Sg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusIronstriderTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_ironstrider__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_ironstrider"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "49.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Tg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusKastelanRobotsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_kastelan_robots__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_kastelan_robots"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "69.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusKastelanRobotsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_kastelan_robots__tcgcsv_low_usd"),
  kit_id: kitId("adeptus_mechanicus_kastelan_robots"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "69.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusKastelanRobotsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_kastelan_robots__tcgcsv_mid_usd"),
  kit_id: kitId("adeptus_mechanicus_kastelan_robots"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "69.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusKastelanRobotsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_kastelan_robots__tcgcsv_high_usd"),
  kit_id: kitId("adeptus_mechanicus_kastelan_robots"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "69.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusKataphronBattleServitorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_kataphron_battle_servitors__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_kataphron_battle_servitors"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "58.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusOnagerDunecrawlerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_onager_dunecrawler__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_onager_dunecrawler"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "66.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusPteraxiiTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_pteraxii__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_pteraxii"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6HF5",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSerberysRaidersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_serberys_raiders__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_serberys_raiders"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7HF5",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSicariansTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_sicarians__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_sicarians"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "46.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Zg82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSkitariiTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_skitarii__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_skitarii"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "39.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-g82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSkitariiTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_skitarii__tcgcsv_low_usd"),
  kit_id: kitId("adeptus_mechanicus_skitarii"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "39.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/-g82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSkitariiTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_skitarii__tcgcsv_mid_usd"),
  kit_id: kitId("adeptus_mechanicus_skitarii"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/-g82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSkitariiTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_skitarii__tcgcsv_high_usd"),
  kit_id: kitId("adeptus_mechanicus_skitarii"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "48.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/-g82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusSkorpiusDisintegratorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_skorpius_disintegrator__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_skorpius_disintegrator"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rSf3",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusTechPriestDominusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_tech_priest_dominus__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_tech_priest_dominus"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "36.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Qq82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusMechanicusTechPriestManipulusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_mechanicus_tech_priest_manipulus__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_mechanicus_tech_priest_manipulus"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9HF5",
  observed_date: null,
  superseded_date: null,
};


export const ApocalypseAdeptusMechanicusVanguardDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_adeptus_mechanicus_vanguard_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_adeptus_mechanicus_vanguard_detachment"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/PTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceAdeptusMechanicusFistOfTheOmnissianTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_adeptus_mechanicus_fist_of_the_omnissian__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_adeptus_mechanicus_fist_of_the_omnissian"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/v2t2",
  observed_date: null,
  superseded_date: null,
};


export const CustodianGuardSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("custodian_guard_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("custodian_guard_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Rh82",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTheta7AquisitusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_theta_7_aquisitus__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_theta_7_aquisitus"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xlw2",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingAdeptusMechanicusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_adeptus_mechanicus__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_adeptus_mechanicus"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "95.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/2HF5",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesAdeptusMechanicusDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AdeptusMechanicusArchaeopterTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusElectroPriestsTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusIronstriderTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusKastelanRobotsTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusKastelanRobotsTcgcsvLowUsdKitPrice,
    AdeptusMechanicusKastelanRobotsTcgcsvMidUsdKitPrice,
    AdeptusMechanicusKastelanRobotsTcgcsvHighUsdKitPrice,
    AdeptusMechanicusKataphronBattleServitorsTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusOnagerDunecrawlerTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusPteraxiiTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusSerberysRaidersTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusSicariansTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusSkitariiTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusSkitariiTcgcsvLowUsdKitPrice,
    AdeptusMechanicusSkitariiTcgcsvMidUsdKitPrice,
    AdeptusMechanicusSkitariiTcgcsvHighUsdKitPrice,
    AdeptusMechanicusSkorpiusDisintegratorTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusTechPriestDominusTcgcsvMsrpUsdKitPrice,
    AdeptusMechanicusTechPriestManipulusTcgcsvMsrpUsdKitPrice,
    ApocalypseAdeptusMechanicusVanguardDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceAdeptusMechanicusFistOfTheOmnissianTcgcsvMsrpUsdKitPrice,
    CustodianGuardSquadTcgcsvMsrpUsdKitPrice,
    KillTeamTheta7AquisitusTcgcsvMsrpUsdKitPrice,
    StartCollectingAdeptusMechanicusTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
