import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for aeldari.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AeldariWebwayGateTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("aeldari_webway_gate__tcgcsv_msrp_usd"),
  kit_id: kitId("aeldari_webway_gate"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0mm2",
  observed_date: null,
  superseded_date: null,
};


export const ApocalypseCraftworldsVanguardDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_craftworlds_vanguard_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_craftworlds_vanguard_detachment"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceCraftworldsAsuryaniBladehostTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_craftworlds_asuryani_bladehost__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_craftworlds_asuryani_bladehost"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/B2t2",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceCraftworldsSpiritseerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_craftworlds_spiritseer__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_craftworlds_spiritseer"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mVf3",
  observed_date: null,
  superseded_date: null,
};


export const CraftworldsEldradUlthranTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("craftworlds_eldrad_ulthran__tcgcsv_msrp_usd"),
  kit_id: kitId("craftworlds_eldrad_ulthran"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/32m2",
  observed_date: null,
  superseded_date: null,
};


export const CraftworldsFarseerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("craftworlds_farseer__tcgcsv_msrp_usd"),
  kit_id: kitId("craftworlds_farseer"),
  currency: "usd",
  price: "20.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/52m2",
  observed_date: null,
  superseded_date: null,
};


export const CraftworldsHowlingBansheesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("craftworlds_howling_banshees__tcgcsv_msrp_usd"),
  kit_id: kitId("craftworlds_howling_banshees"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/M_f3",
  observed_date: null,
  superseded_date: null,
};


export const CraftworldsJainZarTheStormOfSilenceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("craftworlds_jain_zar_the_storm_of_silence__tcgcsv_msrp_usd"),
  kit_id: kitId("craftworlds_jain_zar_the_storm_of_silence"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0vg3",
  observed_date: null,
  superseded_date: null,
};


export const EldarDireAvengersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_dire_avengers__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_dire_avengers"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarFarseerSkyrunnerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_farseer_skyrunner__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_farseer_skyrunner"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7r82",
  observed_date: null,
  superseded_date: null,
};


export const EldarGuardiansTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_guardians__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_guardians"),
  currency: "usd",
  price: "36.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarHemlockWraithfighterTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_hemlock_wraithfighter__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_hemlock_wraithfighter"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/kj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWarWalkerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_war_walker__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_war_walker"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWindridersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_windriders__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_windriders"),
  currency: "usd",
  price: "41.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWraithguardTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_wraithguard__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_wraithguard"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWraithguardTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_wraithguard__tcgcsv_low_usd"),
  kit_id: kitId("eldar_wraithguard"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/rj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWraithguardTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_wraithguard__tcgcsv_mid_usd"),
  kit_id: kitId("eldar_wraithguard"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/rj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWraithguardTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_wraithguard__tcgcsv_high_usd"),
  kit_id: kitId("eldar_wraithguard"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/rj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWraithknightTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_wraithknight__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_wraithknight"),
  currency: "usd",
  price: "115.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sj82",
  observed_date: null,
  superseded_date: null,
};


export const EldarWraithlordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("eldar_wraithlord__tcgcsv_msrp_usd"),
  kit_id: kitId("eldar_wraithlord"),
  currency: "usd",
  price: "46.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/tj82",
  observed_date: null,
  superseded_date: null,
};


export const HarlequinDeathJesterTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("harlequin_death_jester__tcgcsv_msrp_usd"),
  kit_id: kitId("harlequin_death_jester"),
  currency: "usd",
  price: "26.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/br82",
  observed_date: null,
  superseded_date: null,
};


export const HarlequinShadowseerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("harlequin_shadowseer__tcgcsv_msrp_usd"),
  kit_id: kitId("harlequin_shadowseer"),
  currency: "usd",
  price: "26.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cr82",
  observed_date: null,
  superseded_date: null,
};


export const HarlequinSkyweaversTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("harlequin_skyweavers__tcgcsv_msrp_usd"),
  kit_id: kitId("harlequin_skyweavers"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lj82",
  observed_date: null,
  superseded_date: null,
};


export const HarlequinStarweaverTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("harlequin_starweaver__tcgcsv_msrp_usd"),
  kit_id: kitId("harlequin_starweaver"),
  currency: "usd",
  price: "41.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Mj82",
  observed_date: null,
  superseded_date: null,
};


export const HarlequinTroupeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("harlequin_troupe__tcgcsv_msrp_usd"),
  kit_id: kitId("harlequin_troupe"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Nj82",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingEldarTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_eldar__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_eldar"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Ml82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesAeldariDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AeldariWebwayGateTcgcsvMsrpUsdKitPrice,
    ApocalypseCraftworldsVanguardDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceCraftworldsAsuryaniBladehostTcgcsvMsrpUsdKitPrice,
    BattleforceCraftworldsSpiritseerTcgcsvMsrpUsdKitPrice,
    CraftworldsEldradUlthranTcgcsvMsrpUsdKitPrice,
    CraftworldsFarseerTcgcsvMsrpUsdKitPrice,
    CraftworldsHowlingBansheesTcgcsvMsrpUsdKitPrice,
    CraftworldsJainZarTheStormOfSilenceTcgcsvMsrpUsdKitPrice,
    EldarDireAvengersTcgcsvMsrpUsdKitPrice,
    EldarFarseerSkyrunnerTcgcsvMsrpUsdKitPrice,
    EldarGuardiansTcgcsvMsrpUsdKitPrice,
    EldarHemlockWraithfighterTcgcsvMsrpUsdKitPrice,
    EldarWarWalkerTcgcsvMsrpUsdKitPrice,
    EldarWindridersTcgcsvMsrpUsdKitPrice,
    EldarWraithguardTcgcsvMsrpUsdKitPrice,
    EldarWraithguardTcgcsvLowUsdKitPrice,
    EldarWraithguardTcgcsvMidUsdKitPrice,
    EldarWraithguardTcgcsvHighUsdKitPrice,
    EldarWraithknightTcgcsvMsrpUsdKitPrice,
    EldarWraithlordTcgcsvMsrpUsdKitPrice,
    HarlequinDeathJesterTcgcsvMsrpUsdKitPrice,
    HarlequinShadowseerTcgcsvMsrpUsdKitPrice,
    HarlequinSkyweaversTcgcsvMsrpUsdKitPrice,
    HarlequinStarweaverTcgcsvMsrpUsdKitPrice,
    HarlequinTroupeTcgcsvMsrpUsdKitPrice,
    StartCollectingEldarTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
