import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for astra_militarum.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseAstraMilitarumSpearheadDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_astra_militarum_spearhead_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_astra_militarum_spearhead_detachment"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xTf3",
  observed_date: null,
  superseded_date: null,
};


export const ApocalypseSpaceMarinesBattalionDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_space_marines_battalion_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_space_marines_battalion_detachment"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zTf3",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumBanebladeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_baneblade__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_baneblade"),
  currency: "usd",
  price: "140.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/HSf3",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumBattleforceBastionPlatoonTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_battleforce_bastion_platoon__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_battleforce_bastion_platoon"),
  currency: "usd",
  price: "200.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ZmV5",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumCadianArmouredFistTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_cadian_armoured_fist__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_cadian_armoured_fist"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/2h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumCadianShockTroopsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_cadian_shock_troops__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_cadian_shock_troops"),
  currency: "usd",
  price: "29.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumCadianShockTroopsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_cadian_shock_troops__tcgcsv_low_usd"),
  kit_id: kitId("astra_militarum_cadian_shock_troops"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/3h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumCadianShockTroopsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_cadian_shock_troops__tcgcsv_mid_usd"),
  kit_id: kitId("astra_militarum_cadian_shock_troops"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/3h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumCadianShockTroopsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_cadian_shock_troops__tcgcsv_high_usd"),
  kit_id: kitId("astra_militarum_cadian_shock_troops"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/3h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumCadiansTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_cadians__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_cadians"),
  currency: "usd",
  price: "10.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumHydraTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_hydra__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_hydra"),
  currency: "usd",
  price: "56.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumImperialGuardChimeraTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_imperial_guard_chimera__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_imperial_guard_chimera"),
  currency: "usd",
  price: "37.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_imperial_guard_leman_russ_battle_tank__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_imperial_guard_leman_russ_battle_tank"),
  currency: "usd",
  price: "49.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_imperial_guard_leman_russ_battle_tank__tcgcsv_low_usd"),
  kit_id: kitId("astra_militarum_imperial_guard_leman_russ_battle_tank"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/8h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_imperial_guard_leman_russ_battle_tank__tcgcsv_mid_usd"),
  kit_id: kitId("astra_militarum_imperial_guard_leman_russ_battle_tank"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/8h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_imperial_guard_leman_russ_battle_tank__tcgcsv_high_usd"),
  kit_id: kitId("astra_militarum_imperial_guard_leman_russ_battle_tank"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/8h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumLemanRussDemolisherTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_leman_russ_demolisher__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_leman_russ_demolisher"),
  currency: "usd",
  price: "49.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9h82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumLemanRussTechCommandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_leman_russ_tech_command__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_leman_russ_tech_command"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bh82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumSentinelTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_sentinel__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_sentinel"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ch82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumStarterSetKillTeamDropForceImperatorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_starter_set_kill_team_drop_force_imperator__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_starter_set_kill_team_drop_force_imperator"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_tp2",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumTechPriestEnginseerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_tech_priest_enginseer__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_tech_priest_enginseer"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Rq82",
  observed_date: null,
  superseded_date: null,
};


export const AstraMilitarumValkyrieTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_militarum_valkyrie__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_militarum_valkyrie"),
  currency: "usd",
  price: "66.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dh82",
  observed_date: null,
  superseded_date: null,
};


export const AstraTelepathicaSistersOfSilenceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("astra_telepathica_sisters_of_silence__tcgcsv_msrp_usd"),
  kit_id: kitId("astra_telepathica_sisters_of_silence"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fh82",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceAstraMilitarumBattlegroupTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_astra_militarum_battlegroup__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_astra_militarum_battlegroup"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/pQf2",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceAstraMilitarumSeverinaRaineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_astra_militarum_severina_raine__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_astra_militarum_severina_raine"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rRx2",
  observed_date: null,
  superseded_date: null,
};


export const CadianCommandSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("cadian_command_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("cadian_command_squad"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vh82",
  observed_date: null,
  superseded_date: null,
};


export const CadianHeavyWeaponSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("cadian_heavy_weapon_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("cadian_heavy_weapon_squad"),
  currency: "usd",
  price: "39.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wh82",
  observed_date: null,
  superseded_date: null,
};


export const MilitarumAuxillaBullgrynsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("militarum_auxilla_bullgryns__tcgcsv_msrp_usd"),
  kit_id: kitId("militarum_auxilla_bullgryns"),
  currency: "usd",
  price: "47.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lm82",
  observed_date: null,
  superseded_date: null,
};


export const MilitarumAuxillaBullgrynsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("militarum_auxilla_bullgryns__tcgcsv_low_usd"),
  kit_id: kitId("militarum_auxilla_bullgryns"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lm82",
  observed_date: null,
  superseded_date: null,
};


export const MilitarumAuxillaBullgrynsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("militarum_auxilla_bullgryns__tcgcsv_mid_usd"),
  kit_id: kitId("militarum_auxilla_bullgryns"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lm82",
  observed_date: null,
  superseded_date: null,
};


export const MilitarumAuxillaBullgrynsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("militarum_auxilla_bullgryns__tcgcsv_high_usd"),
  kit_id: kitId("militarum_auxilla_bullgryns"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lm82",
  observed_date: null,
  superseded_date: null,
};


export const MilitarumTempestusScionsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("militarum_tempestus_scions__tcgcsv_msrp_usd"),
  kit_id: kitId("militarum_tempestus_scions"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Mm82",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingAstraMilitarumTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_astra_militarum__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_astra_militarum"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hl82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesAstraMilitarumDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseAstraMilitarumSpearheadDetachmentTcgcsvMsrpUsdKitPrice,
    ApocalypseSpaceMarinesBattalionDetachmentTcgcsvMsrpUsdKitPrice,
    AstraMilitarumBanebladeTcgcsvMsrpUsdKitPrice,
    AstraMilitarumBattleforceBastionPlatoonTcgcsvMsrpUsdKitPrice,
    AstraMilitarumCadianArmouredFistTcgcsvMsrpUsdKitPrice,
    AstraMilitarumCadianShockTroopsTcgcsvMsrpUsdKitPrice,
    AstraMilitarumCadianShockTroopsTcgcsvLowUsdKitPrice,
    AstraMilitarumCadianShockTroopsTcgcsvMidUsdKitPrice,
    AstraMilitarumCadianShockTroopsTcgcsvHighUsdKitPrice,
    AstraMilitarumCadiansTcgcsvMsrpUsdKitPrice,
    AstraMilitarumHydraTcgcsvMsrpUsdKitPrice,
    AstraMilitarumImperialGuardChimeraTcgcsvMsrpUsdKitPrice,
    AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvMsrpUsdKitPrice,
    AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvLowUsdKitPrice,
    AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvMidUsdKitPrice,
    AstraMilitarumImperialGuardLemanRussBattleTankTcgcsvHighUsdKitPrice,
    AstraMilitarumLemanRussDemolisherTcgcsvMsrpUsdKitPrice,
    AstraMilitarumLemanRussTechCommandTcgcsvMsrpUsdKitPrice,
    AstraMilitarumSentinelTcgcsvMsrpUsdKitPrice,
    AstraMilitarumStarterSetKillTeamDropForceImperatorTcgcsvMsrpUsdKitPrice,
    AstraMilitarumTechPriestEnginseerTcgcsvMsrpUsdKitPrice,
    AstraMilitarumValkyrieTcgcsvMsrpUsdKitPrice,
    AstraTelepathicaSistersOfSilenceTcgcsvMsrpUsdKitPrice,
    BattleforceAstraMilitarumBattlegroupTcgcsvMsrpUsdKitPrice,
    BattleforceAstraMilitarumSeverinaRaineTcgcsvMsrpUsdKitPrice,
    CadianCommandSquadTcgcsvMsrpUsdKitPrice,
    CadianHeavyWeaponSquadTcgcsvMsrpUsdKitPrice,
    MilitarumAuxillaBullgrynsTcgcsvMsrpUsdKitPrice,
    MilitarumAuxillaBullgrynsTcgcsvLowUsdKitPrice,
    MilitarumAuxillaBullgrynsTcgcsvMidUsdKitPrice,
    MilitarumAuxillaBullgrynsTcgcsvHighUsdKitPrice,
    MilitarumTempestusScionsTcgcsvMsrpUsdKitPrice,
    StartCollectingAstraMilitarumTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
