import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for blood_angels.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceBloodAngelsCrimsonSpearStrikeForceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_blood_angels_crimson_spear_strike_force__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_blood_angels_crimson_spear_strike_force"),
  currency: "usd",
  price: "185.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8Qf3",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsAssaultSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_assault_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_assault_squad"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsCaptainTerminatorArmourTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_captain_terminator_armour__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_captain_terminator_armour"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Sq82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsChaplainWithJumpPackTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_chaplain_with_jump_pack__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_chaplain_with_jump_pack"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Tq82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsChapterAncientsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_chapter_ancients__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_chapter_ancients"),
  currency: "usd",
  price: "105.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsCompanyCommandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_company_command__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_company_command"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/kh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsDeathCompanyTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_death_company__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_death_company"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsDeathCompanyIntercessorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_death_company_intercessors__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_death_company_intercessors"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/TmV5",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsDeathCompanyStrikeForceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_death_company_strike_force__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_death_company_strike_force"),
  currency: "usd",
  price: "135.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsFuriosoDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_furioso_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_furioso_dreadnought"),
  currency: "usd",
  price: "46.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsMephistonLordOfDeathTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_mephiston_lord_of_death__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_mephiston_lord_of_death"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7Qf3",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsPrimarisAggressorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_primaris_aggressors__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_primaris_aggressors"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/MZf2",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsPrimarisHellblastersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_primaris_hellblasters__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_primaris_hellblasters"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/LZf2",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsPrimarisIntercessorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_primaris_intercessors__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_primaris_intercessors"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/KZf2",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsPrimarisUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_primaris_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_primaris_upgrades"),
  currency: "usd",
  price: "12.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/PZf2",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsSanguinaryGuardTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_sanguinary_guard__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_sanguinary_guard"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ph82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsSanguinaryPriestTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_sanguinary_priest__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_sanguinary_priest"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vq82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsSternguardVeteranSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_sternguard_veteran_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_sternguard_veteran_squad"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsTacticalSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_tactical_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_tactical_squad"),
  currency: "usd",
  price: "43.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsTerminatorAssaultSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_terminator_assault_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_terminator_assault_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sh82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_upgrades"),
  currency: "usd",
  price: "13.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wq82",
  observed_date: null,
  superseded_date: null,
};


export const BloodAngelsVanguardVeteranSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_angels_vanguard_veteran_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_angels_vanguard_veteran_squad"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/th82",
  observed_date: null,
  superseded_date: null,
};


export const CombatPatrolBloodAngelsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("combat_patrol_blood_angels__tcgcsv_msrp_usd"),
  kit_id: kitId("combat_patrol_blood_angels"),
  currency: "usd",
  price: "140.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/SmV5",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingBloodAngelsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_blood_angels__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_blood_angels"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Jl82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesBloodAngelsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    BattleforceBloodAngelsCrimsonSpearStrikeForceTcgcsvMsrpUsdKitPrice,
    BloodAngelsAssaultSquadTcgcsvMsrpUsdKitPrice,
    BloodAngelsCaptainTerminatorArmourTcgcsvMsrpUsdKitPrice,
    BloodAngelsChaplainWithJumpPackTcgcsvMsrpUsdKitPrice,
    BloodAngelsChapterAncientsTcgcsvMsrpUsdKitPrice,
    BloodAngelsCompanyCommandTcgcsvMsrpUsdKitPrice,
    BloodAngelsDeathCompanyTcgcsvMsrpUsdKitPrice,
    BloodAngelsDeathCompanyIntercessorsTcgcsvMsrpUsdKitPrice,
    BloodAngelsDeathCompanyStrikeForceTcgcsvMsrpUsdKitPrice,
    BloodAngelsFuriosoDreadnoughtTcgcsvMsrpUsdKitPrice,
    BloodAngelsMephistonLordOfDeathTcgcsvMsrpUsdKitPrice,
    BloodAngelsPrimarisAggressorsTcgcsvMsrpUsdKitPrice,
    BloodAngelsPrimarisHellblastersTcgcsvMsrpUsdKitPrice,
    BloodAngelsPrimarisIntercessorsTcgcsvMsrpUsdKitPrice,
    BloodAngelsPrimarisUpgradesTcgcsvMsrpUsdKitPrice,
    BloodAngelsSanguinaryGuardTcgcsvMsrpUsdKitPrice,
    BloodAngelsSanguinaryPriestTcgcsvMsrpUsdKitPrice,
    BloodAngelsSternguardVeteranSquadTcgcsvMsrpUsdKitPrice,
    BloodAngelsTacticalSquadTcgcsvMsrpUsdKitPrice,
    BloodAngelsTerminatorAssaultSquadTcgcsvMsrpUsdKitPrice,
    BloodAngelsUpgradesTcgcsvMsrpUsdKitPrice,
    BloodAngelsVanguardVeteranSquadTcgcsvMsrpUsdKitPrice,
    CombatPatrolBloodAngelsTcgcsvMsrpUsdKitPrice,
    StartCollectingBloodAngelsTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
