import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for chaos_space_marines.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseChaosSpaceMarinesBattalionDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_chaos_space_marines_battalion_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_chaos_space_marines_battalion_detachment"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceChaosSpaceMarinesVengeanceWarbandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_chaos_space_marines_vengeance_warband__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_chaos_space_marines_vengeance_warband"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bQf3",
  observed_date: null,
  superseded_date: null,
};


export const ChaosBikersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_bikers__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_bikers"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosCultistsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_cultists__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_cultists"),
  currency: "usd",
  price: "10.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosCultistsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_cultists__tcgcsv_low_usd"),
  kit_id: kitId("chaos_cultists"),
  currency: "usd",
  price: "59.99",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/zh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosCultistsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_cultists__tcgcsv_mid_usd"),
  kit_id: kitId("chaos_cultists"),
  currency: "usd",
  price: "59.99",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/zh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosCultistsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_cultists__tcgcsv_high_usd"),
  kit_id: kitId("chaos_cultists"),
  currency: "usd",
  price: "59.99",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/zh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine"),
  currency: "usd",
  price: "10.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Ch82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineAspiringChampionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_aspiring_champion__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_aspiring_champion"),
  currency: "usd",
  price: "20.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Zq82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineChaosLordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_chaos_lord__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_chaos_lord"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/X-x2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineCultistAssaultTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_cultist_assault__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_cultist_assault"),
  currency: "usd",
  price: "48.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Dh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineForgefiendTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_forgefiend__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_forgefiend"),
  currency: "usd",
  price: "68.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Fh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineHelbruteTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_helbrute__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_helbrute"),
  currency: "usd",
  price: "54.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Gh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineHeldrakeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_heldrake__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_heldrake"),
  currency: "usd",
  price: "74.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineKharnTheBetrayerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_kharn_the_betrayer__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_kharn_the_betrayer"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Jh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineMasterOfExecutionsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_master_of_executions__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_master_of_executions"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/V-x2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinePossessedTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_possessed__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_possessed"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Kh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineRaptorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_raptors__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_raptors"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineRaptorsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_raptors__tcgcsv_low_usd"),
  kit_id: kitId("chaos_space_marine_raptors"),
  currency: "usd",
  price: "59.99",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineRaptorsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_raptors__tcgcsv_mid_usd"),
  kit_id: kitId("chaos_space_marine_raptors"),
  currency: "usd",
  price: "59.99",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineRaptorsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_raptors__tcgcsv_high_usd"),
  kit_id: kitId("chaos_space_marine_raptors"),
  currency: "usd",
  price: "59.99",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_squad"),
  currency: "usd",
  price: "39.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Mh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineTerminatorLordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_terminator_lord__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_terminator_lord"),
  currency: "usd",
  price: "24.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Nh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarineTerminatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marine_terminators__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marine_terminators"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Qh82",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_Vx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesAbaddonTheDespoilerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_abaddon_the_despoiler__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_abaddon_the_despoiler"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-Vx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesBattleforceDecimationWarbandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_battleforce_decimation_warband__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_battleforce_decimation_warband"),
  currency: "usd",
  price: "200.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/XmV5",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesDarkApostleTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_dark_apostle__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_dark_apostle"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesDarkApostleTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_dark_apostle__tcgcsv_low_usd"),
  kit_id: kitId("chaos_space_marines_dark_apostle"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/jXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesDarkApostleTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_dark_apostle__tcgcsv_mid_usd"),
  kit_id: kitId("chaos_space_marines_dark_apostle"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/jXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesDarkApostleTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_dark_apostle__tcgcsv_high_usd"),
  kit_id: kitId("chaos_space_marines_dark_apostle"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/jXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesFabiusBileTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_fabius_bile__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_fabius_bile"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nGF5",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesHaarkenWorldclaimerHeraldOfTheApocalypseTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_haarken_worldclaimer_herald_of_the_apocalypse__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_haarken_worldclaimer_herald_of_the_apocalypse"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/d3t2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesHavocsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_havocs__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_havocs"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesNoctilithCrownTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_noctilith_crown__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_noctilith_crown"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0Wx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesNoiseMarineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_noise_marine__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_noise_marine"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/x3t2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesSorcererTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_sorcerer__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_sorcerer"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ZPf3",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesTerminatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_terminators__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_terminators"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesTerminatorsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_terminators__tcgcsv_low_usd"),
  kit_id: kitId("chaos_space_marines_terminators"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/fXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesTerminatorsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_terminators__tcgcsv_mid_usd"),
  kit_id: kitId("chaos_space_marines_terminators"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/fXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesTerminatorsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_terminators__tcgcsv_high_usd"),
  kit_id: kitId("chaos_space_marines_terminators"),
  currency: "usd",
  price: "69.99",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/fXx2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosSpaceMarinesVexMachinatorArchLordDiscordantTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_space_marines_vex_machinator_arch_lord_discordant__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_space_marines_vex_machinator_arch_lord_discordant"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hXx2",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingChaosSpaceMarinesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_chaos_space_marines__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_chaos_space_marines"),
  currency: "usd",
  price: "95.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_Pf3",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesChaosSpaceMarinesDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseChaosSpaceMarinesBattalionDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceChaosSpaceMarinesVengeanceWarbandTcgcsvMsrpUsdKitPrice,
    ChaosBikersTcgcsvMsrpUsdKitPrice,
    ChaosCultistsTcgcsvMsrpUsdKitPrice,
    ChaosCultistsTcgcsvLowUsdKitPrice,
    ChaosCultistsTcgcsvMidUsdKitPrice,
    ChaosCultistsTcgcsvHighUsdKitPrice,
    ChaosSpaceMarineTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineAspiringChampionTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineChaosLordTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineCultistAssaultTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineForgefiendTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineHelbruteTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineHeldrakeTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineKharnTheBetrayerTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineMasterOfExecutionsTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinePossessedTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineRaptorsTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineRaptorsTcgcsvLowUsdKitPrice,
    ChaosSpaceMarineRaptorsTcgcsvMidUsdKitPrice,
    ChaosSpaceMarineRaptorsTcgcsvHighUsdKitPrice,
    ChaosSpaceMarineSquadTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineTerminatorLordTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarineTerminatorsTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesAbaddonTheDespoilerTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesBattleforceDecimationWarbandTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesDarkApostleTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesDarkApostleTcgcsvLowUsdKitPrice,
    ChaosSpaceMarinesDarkApostleTcgcsvMidUsdKitPrice,
    ChaosSpaceMarinesDarkApostleTcgcsvHighUsdKitPrice,
    ChaosSpaceMarinesFabiusBileTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesHaarkenWorldclaimerHeraldOfTheApocalypseTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesHavocsTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesNoctilithCrownTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesNoiseMarineTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesSorcererTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesTerminatorsTcgcsvMsrpUsdKitPrice,
    ChaosSpaceMarinesTerminatorsTcgcsvLowUsdKitPrice,
    ChaosSpaceMarinesTerminatorsTcgcsvMidUsdKitPrice,
    ChaosSpaceMarinesTerminatorsTcgcsvHighUsdKitPrice,
    ChaosSpaceMarinesVexMachinatorArchLordDiscordantTcgcsvMsrpUsdKitPrice,
    StartCollectingChaosSpaceMarinesTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
