import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for chaos_daemons.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AhrimanArchSorcererOfTzeentchTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ahriman_arch_sorcerer_of_tzeentch__tcgcsv_msrp_usd"),
  kit_id: kitId("ahriman_arch_sorcerer_of_tzeentch"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0h82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesChaosDaemonsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AhrimanArchSorcererOfTzeentchTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
