import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for dark_angels.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const DarkAngelsCompanyVeteransSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_company_veterans_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_company_veterans_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Sh82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsDeathwingCommandSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_deathwing_command_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_deathwing_command_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Th82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsDeathwingCommandSquadTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_deathwing_command_squad__tcgcsv_low_usd"),
  kit_id: kitId("dark_angels_deathwing_command_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Th82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsDeathwingCommandSquadTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_deathwing_command_squad__tcgcsv_mid_usd"),
  kit_id: kitId("dark_angels_deathwing_command_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Th82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsDeathwingCommandSquadTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_deathwing_command_squad__tcgcsv_high_usd"),
  kit_id: kitId("dark_angels_deathwing_command_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Th82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsGauntletTacticalSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_gauntlet_tactical_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_gauntlet_tactical_squad"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vh82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsInterrogatorChaplainTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_interrogator_chaplain__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_interrogator_chaplain"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-q82",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsMasterLazarusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_master_lazarus__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_master_lazarus"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/b-f3",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsPrimarisAggressorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_primaris_aggressors__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_primaris_aggressors"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/X2g2",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsPrimarisHellblastersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_primaris_hellblasters__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_primaris_hellblasters"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/W2g2",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsPrimarisIntercessorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_primaris_intercessors__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_primaris_intercessors"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/V2g2",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsPrimarisLieutenantZakariahTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_primaris_lieutenant_zakariah__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_primaris_lieutenant_zakariah"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/S2g2",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsPrimarisUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_primaris_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_primaris_upgrades"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "12.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/T2g2",
  observed_date: null,
  superseded_date: null,
};


export const DarkAngelsUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_angels_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_angels_upgrades"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "13.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_q82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesDarkAngelsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    DarkAngelsCompanyVeteransSquadTcgcsvMsrpUsdKitPrice,
    DarkAngelsDeathwingCommandSquadTcgcsvMsrpUsdKitPrice,
    DarkAngelsDeathwingCommandSquadTcgcsvLowUsdKitPrice,
    DarkAngelsDeathwingCommandSquadTcgcsvMidUsdKitPrice,
    DarkAngelsDeathwingCommandSquadTcgcsvHighUsdKitPrice,
    DarkAngelsGauntletTacticalSquadTcgcsvMsrpUsdKitPrice,
    DarkAngelsInterrogatorChaplainTcgcsvMsrpUsdKitPrice,
    DarkAngelsMasterLazarusTcgcsvMsrpUsdKitPrice,
    DarkAngelsPrimarisAggressorsTcgcsvMsrpUsdKitPrice,
    DarkAngelsPrimarisHellblastersTcgcsvMsrpUsdKitPrice,
    DarkAngelsPrimarisIntercessorsTcgcsvMsrpUsdKitPrice,
    DarkAngelsPrimarisLieutenantZakariahTcgcsvMsrpUsdKitPrice,
    DarkAngelsPrimarisUpgradesTcgcsvMsrpUsdKitPrice,
    DarkAngelsUpgradesTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
