import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for deathwatch.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const CombatPatrolDeathwatchTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("combat_patrol_deathwatch__tcgcsv_msrp_usd"),
  kit_id: kitId("combat_patrol_deathwatch"),
  currency: "usd",
  price: "140.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/FgV5",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchCorvusBlackstarTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_corvus_blackstar__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_corvus_blackstar"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5j82",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchKillTeamTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_kill_team__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_kill_team"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6j82",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchKillTeamCassiusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_kill_team_cassius__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_kill_team_cassius"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7j82",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_upgrades"),
  currency: "usd",
  price: "12.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3r82",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchVenerableDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_venerable_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_venerable_dreadnought"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8j82",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchWatchCaptTerminatorArmourTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_watch_capt_terminator_armour__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_watch_capt_terminator_armour"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5r82",
  observed_date: null,
  superseded_date: null,
};


export const DeathwatchWatchMasterTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deathwatch_watch_master__tcgcsv_msrp_usd"),
  kit_id: kitId("deathwatch_watch_master"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6r82",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamAdvanceTeamStarpulseTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_advance_team_starpulse__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_advance_team_starpulse"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/p5s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderAnkraTheColossusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_ankra_the_colossus__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_ankra_the_colossus"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/36s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderFeodorLaskoTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_feodor_lasko__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_feodor_lasko"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/56s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderFirebladeTwinflameTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_fireblade_twinflame__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_fireblade_twinflame"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/76s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderGaiusAcastianTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_gaius_acastian__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_gaius_acastian"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/06s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderGitzogWurldkillaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_gitzog_wurldkilla__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_gitzog_wurldkilla"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/66s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderMagosDalathrustTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_magos_dalathrust__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_magos_dalathrust"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-5s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderTorrvaldOrksbaneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_torrvald_orksbane__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_torrvald_orksbane"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_5s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommanderVysaKharavyxisTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commander_vysa_kharavyxis__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commander_vysa_kharavyxis"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/26s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamCommandersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_commanders__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_commanders"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Z5s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamGenestealerCultsCommanderSetCraskerMatterzhekTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_genestealer_cults_commander_set_crasker_matterzhek__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_genestealer_cults_commander_set_crasker_matterzhek"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gks2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamMordelaiTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_mordelai__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_mordelai"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/JKq2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamSectorSanctorisTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_sector_sanctoris__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_sector_sanctoris"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_0B2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTheDolorousStrainTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_the_dolorous_strain__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_the_dolorous_strain"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-0B2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTheExaltedScytheTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_the_exalted_scythe__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_the_exalted_scythe"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/q5s2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTheFractalBladesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_the_fractal_blades__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_the_fractal_blades"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/X0B2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTheSlicingNooseTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_the_slicing_noose__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_the_slicing_noose"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/KKq2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamToofrippasKrewTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_toofrippas_krew__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_toofrippas_krew"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/V0B2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTyranidsCommanderSetNemesis9TyrantisTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_tyranids_commander_set_nemesis_9_tyrantis__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_tyranids_commander_set_nemesis_9_tyrantis"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fks2",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingDeathwatchTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_deathwatch__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_deathwatch"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Ll82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesDeathwatchDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    CombatPatrolDeathwatchTcgcsvMsrpUsdKitPrice,
    DeathwatchCorvusBlackstarTcgcsvMsrpUsdKitPrice,
    DeathwatchKillTeamTcgcsvMsrpUsdKitPrice,
    DeathwatchKillTeamCassiusTcgcsvMsrpUsdKitPrice,
    DeathwatchUpgradesTcgcsvMsrpUsdKitPrice,
    DeathwatchVenerableDreadnoughtTcgcsvMsrpUsdKitPrice,
    DeathwatchWatchCaptTerminatorArmourTcgcsvMsrpUsdKitPrice,
    DeathwatchWatchMasterTcgcsvMsrpUsdKitPrice,
    KillTeamAdvanceTeamStarpulseTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderAnkraTheColossusTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderFeodorLaskoTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderFirebladeTwinflameTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderGaiusAcastianTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderGitzogWurldkillaTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderMagosDalathrustTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderTorrvaldOrksbaneTcgcsvMsrpUsdKitPrice,
    KillTeamCommanderVysaKharavyxisTcgcsvMsrpUsdKitPrice,
    KillTeamCommandersTcgcsvMsrpUsdKitPrice,
    KillTeamGenestealerCultsCommanderSetCraskerMatterzhekTcgcsvMsrpUsdKitPrice,
    KillTeamMordelaiTcgcsvMsrpUsdKitPrice,
    KillTeamSectorSanctorisTcgcsvMsrpUsdKitPrice,
    KillTeamTheDolorousStrainTcgcsvMsrpUsdKitPrice,
    KillTeamTheExaltedScytheTcgcsvMsrpUsdKitPrice,
    KillTeamTheFractalBladesTcgcsvMsrpUsdKitPrice,
    KillTeamTheSlicingNooseTcgcsvMsrpUsdKitPrice,
    KillTeamToofrippasKrewTcgcsvMsrpUsdKitPrice,
    KillTeamTyranidsCommanderSetNemesis9TyrantisTcgcsvMsrpUsdKitPrice,
    StartCollectingDeathwatchTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
