import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for death_guard.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceDeathGuardInfectionClusterTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_death_guard_infection_cluster__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_death_guard_infection_cluster"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/x2t2",
  observed_date: null,
  superseded_date: null,
};


export const DeathGuardBiologusPutrifierTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("death_guard_biologus_putrifier__tcgcsv_msrp_usd"),
  kit_id: kitId("death_guard_biologus_putrifier"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/62m2",
  observed_date: null,
  superseded_date: null,
};


export const DeathGuardFoulBlightspawnTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("death_guard_foul_blightspawn__tcgcsv_msrp_usd"),
  kit_id: kitId("death_guard_foul_blightspawn"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/72m2",
  observed_date: null,
  superseded_date: null,
};


export const DeathGuardNauseousRotboneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("death_guard_nauseous_rotbone__tcgcsv_msrp_usd"),
  kit_id: kitId("death_guard_nauseous_rotbone"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/82m2",
  observed_date: null,
  superseded_date: null,
};


export const DeathGuardPlagueMarineChampionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("death_guard_plague_marine_champion__tcgcsv_msrp_usd"),
  kit_id: kitId("death_guard_plague_marine_champion"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/92m2",
  observed_date: null,
  superseded_date: null,
};


export const DeathGuardPlagueMarineIconBearerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("death_guard_plague_marine_icon_bearer__tcgcsv_msrp_usd"),
  kit_id: kitId("death_guard_plague_marine_icon_bearer"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/b2m2",
  observed_date: null,
  superseded_date: null,
};


export const DeathGuardScribbusWretchTheTallymanTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("death_guard_scribbus_wretch_the_tallyman__tcgcsv_msrp_usd"),
  kit_id: kitId("death_guard_scribbus_wretch_the_tallyman"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/c2m2",
  observed_date: null,
  superseded_date: null,
};


export const EasyToBuildDeathGuardPlagueMarinesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("easy_to_build_death_guard_plague_marines__tcgcsv_msrp_usd"),
  kit_id: kitId("easy_to_build_death_guard_plague_marines"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "15.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9j82",
  observed_date: null,
  superseded_date: null,
};


export const EasyToBuildDeathGuardPoxwalkersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("easy_to_build_death_guard_poxwalkers__tcgcsv_msrp_usd"),
  kit_id: kitId("easy_to_build_death_guard_poxwalkers"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "15.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bj82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesDeathGuardDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    BattleforceDeathGuardInfectionClusterTcgcsvMsrpUsdKitPrice,
    DeathGuardBiologusPutrifierTcgcsvMsrpUsdKitPrice,
    DeathGuardFoulBlightspawnTcgcsvMsrpUsdKitPrice,
    DeathGuardNauseousRotboneTcgcsvMsrpUsdKitPrice,
    DeathGuardPlagueMarineChampionTcgcsvMsrpUsdKitPrice,
    DeathGuardPlagueMarineIconBearerTcgcsvMsrpUsdKitPrice,
    DeathGuardScribbusWretchTheTallymanTcgcsvMsrpUsdKitPrice,
    EasyToBuildDeathGuardPlagueMarinesTcgcsvMsrpUsdKitPrice,
    EasyToBuildDeathGuardPoxwalkersTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
