import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for genestealer_cults.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceGenestealerCultsInsurrectionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_genestealer_cults_insurrection__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_genestealer_cults_insurrection"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rQf2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsAberrantsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_aberrants__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_aberrants"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/WPx2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsAbominantTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_abominant__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_abominant"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5Qx2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsAchillesRidgerunnerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_achilles_ridgerunner__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_achilles_ridgerunner"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/XPx2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsAcolyteHybridsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_acolyte_hybrids__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_acolyte_hybrids"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsAcolyteIconwardTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_acolyte_iconward__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_acolyte_iconward"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8r82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsAtalanJackalsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_atalan_jackals__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_atalan_jackals"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hlw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsBiophagusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_biophagus__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_biophagus"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3Qx2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsBroodcovenTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_broodcoven__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_broodcoven"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsClamavusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_clamavus__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_clamavus"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Llw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsGoliathTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_goliath__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_goliath"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsJackalAlphusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_jackal_alphus__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_jackal_alphus"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Klw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsKelermorphTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_kelermorph__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_kelermorph"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/V-f3",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsLemanRussTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_leman_russ__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_leman_russ"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsLocusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_locus__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_locus"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Plw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsMagusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_magus__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_magus"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Qlw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsNeophyteHybridArmouredClawTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_neophyte_hybrid_armoured_claw__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_neophyte_hybrid_armoured_claw"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Bj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsNeophyteHybridSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_neophyte_hybrid_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_neophyte_hybrid_squad"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Cj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsNeophyteHybridsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_neophyte_hybrids__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_neophyte_hybrids"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Dj82",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsNexosTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_nexos__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_nexos"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Rlw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsSanctusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_sanctus__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_sanctus"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Slw2",
  observed_date: null,
  superseded_date: null,
};


export const GenestealerCultsUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("genestealer_cults_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("genestealer_cults_upgrades"),
  currency: "usd",
  price: "12.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9r82",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamStarnsDisciplesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_starns_disciples__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_starns_disciples"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zlw2",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingGenestealerCultsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_genestealer_cults__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_genestealer_cults"),
  currency: "usd",
  price: "95.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/T-f3",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesGenestealerCultsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    BattleforceGenestealerCultsInsurrectionTcgcsvMsrpUsdKitPrice,
    GenestealerCultsAberrantsTcgcsvMsrpUsdKitPrice,
    GenestealerCultsAbominantTcgcsvMsrpUsdKitPrice,
    GenestealerCultsAchillesRidgerunnerTcgcsvMsrpUsdKitPrice,
    GenestealerCultsAcolyteHybridsTcgcsvMsrpUsdKitPrice,
    GenestealerCultsAcolyteIconwardTcgcsvMsrpUsdKitPrice,
    GenestealerCultsAtalanJackalsTcgcsvMsrpUsdKitPrice,
    GenestealerCultsBiophagusTcgcsvMsrpUsdKitPrice,
    GenestealerCultsBroodcovenTcgcsvMsrpUsdKitPrice,
    GenestealerCultsClamavusTcgcsvMsrpUsdKitPrice,
    GenestealerCultsGoliathTcgcsvMsrpUsdKitPrice,
    GenestealerCultsJackalAlphusTcgcsvMsrpUsdKitPrice,
    GenestealerCultsKelermorphTcgcsvMsrpUsdKitPrice,
    GenestealerCultsLemanRussTcgcsvMsrpUsdKitPrice,
    GenestealerCultsLocusTcgcsvMsrpUsdKitPrice,
    GenestealerCultsMagusTcgcsvMsrpUsdKitPrice,
    GenestealerCultsNeophyteHybridArmouredClawTcgcsvMsrpUsdKitPrice,
    GenestealerCultsNeophyteHybridSquadTcgcsvMsrpUsdKitPrice,
    GenestealerCultsNeophyteHybridsTcgcsvMsrpUsdKitPrice,
    GenestealerCultsNexosTcgcsvMsrpUsdKitPrice,
    GenestealerCultsSanctusTcgcsvMsrpUsdKitPrice,
    GenestealerCultsUpgradesTcgcsvMsrpUsdKitPrice,
    KillTeamStarnsDisciplesTcgcsvMsrpUsdKitPrice,
    StartCollectingGenestealerCultsTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
