import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for grey_knights.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const GreyKnightsGrandMasterVoldusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("grey_knights_grand_master_voldus__tcgcsv_msrp_usd"),
  kit_id: kitId("grey_knights_grand_master_voldus"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/f2m2",
  observed_date: null,
  superseded_date: null,
};


export const GreyKnightsNemesisDreadknightTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("grey_knights_nemesis_dreadknight__tcgcsv_msrp_usd"),
  kit_id: kitId("grey_knights_nemesis_dreadknight"),
  currency: "usd",
  price: "53.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Fj82",
  observed_date: null,
  superseded_date: null,
};


export const GreyKnightsPaladinSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("grey_knights_paladin_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("grey_knights_paladin_squad"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Gj82",
  observed_date: null,
  superseded_date: null,
};


export const GreyKnightsStrikeSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("grey_knights_strike_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("grey_knights_strike_squad"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hj82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesGreyKnightsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    GreyKnightsGrandMasterVoldusTcgcsvMsrpUsdKitPrice,
    GreyKnightsNemesisDreadknightTcgcsvMsrpUsdKitPrice,
    GreyKnightsPaladinSquadTcgcsvMsrpUsdKitPrice,
    GreyKnightsStrikeSquadTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
