import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for imperial_knights.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseImperialKnightsSuperHeavyDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_imperial_knights_super_heavy_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_imperial_knights_super_heavy_detachment"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/FTf3",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsArmigerHelverinsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_armiger_helverins__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knights_armiger_helverins"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsArmigerHelverinsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_armiger_helverins__tcgcsv_low_usd"),
  kit_id: kitId("imperial_knights_armiger_helverins"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "94.50",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/sSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsArmigerHelverinsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_armiger_helverins__tcgcsv_mid_usd"),
  kit_id: kitId("imperial_knights_armiger_helverins"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "94.50",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/sSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsArmigerHelverinsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_armiger_helverins__tcgcsv_high_usd"),
  kit_id: kitId("imperial_knights_armiger_helverins"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "94.50",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/sSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsArmigerWarglaivesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_armiger_warglaives__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knights_armiger_warglaives"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/KSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsKnightCastellanTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_knight_castellan__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knights_knight_castellan"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsKnightPreceptorCanisRexTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_knight_preceptor_canis_rex__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knights_knight_preceptor_canis_rex"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "157.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lvr2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsKnightValiantTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_knight_valiant__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knights_knight_valiant"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rSm2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightsRenegadeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knights_renegade__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knights_renegade"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "195.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nSm2",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusSacristanForgeshrineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_sacristan_forgeshrine__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_sacristan_forgeshrine"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/DSm2",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesImperialKnightsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseImperialKnightsSuperHeavyDetachmentTcgcsvMsrpUsdKitPrice,
    ImperialKnightsArmigerHelverinsTcgcsvMsrpUsdKitPrice,
    ImperialKnightsArmigerHelverinsTcgcsvLowUsdKitPrice,
    ImperialKnightsArmigerHelverinsTcgcsvMidUsdKitPrice,
    ImperialKnightsArmigerHelverinsTcgcsvHighUsdKitPrice,
    ImperialKnightsArmigerWarglaivesTcgcsvMsrpUsdKitPrice,
    ImperialKnightsKnightCastellanTcgcsvMsrpUsdKitPrice,
    ImperialKnightsKnightPreceptorCanisRexTcgcsvMsrpUsdKitPrice,
    ImperialKnightsKnightValiantTcgcsvMsrpUsdKitPrice,
    ImperialKnightsRenegadeTcgcsvMsrpUsdKitPrice,
    SectorMechanicusSacristanForgeshrineTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
