import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for imperial_fists.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceImperialFistsSupremacyForceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_imperial_fists_supremacy_force__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_imperial_fists_supremacy_force"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/s2t2",
  observed_date: null,
  superseded_date: null,
};


export const ImperialFistsPrimarisUpgradesTransferssalamandersAdraxAgatoneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_fists_primaris_upgrades_transferssalamanders_adrax_agatone__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_fists_primaris_upgrades_transferssalamanders_adrax_agatone"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lNf3",
  observed_date: null,
  superseded_date: null,
};


export const ImperialFistsTorGaradonTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_fists_tor_garadon__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_fists_tor_garadon"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jNf3",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesImperialFistsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    BattleforceImperialFistsSupremacyForceTcgcsvMsrpUsdKitPrice,
    ImperialFistsPrimarisUpgradesTransferssalamandersAdraxAgatoneTcgcsvMsrpUsdKitPrice,
    ImperialFistsTorGaradonTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
