import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for necrons.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseNecronsOutriderDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_necrons_outrider_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_necrons_outrider_detachment"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/BTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceNecronsDominionSpearheadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_necrons_dominion_spearhead__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_necrons_dominion_spearhead"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/z2t2",
  observed_date: null,
  superseded_date: null,
};


export const IlluminorSzerasTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("illuminor_szeras__tcgcsv_msrp_usd"),
  kit_id: kitId("illuminor_szeras"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/KKF5",
  observed_date: null,
  superseded_date: null,
};


export const NecronCanoptekSpyderTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_canoptek_spyder__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_canoptek_spyder"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/2k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronCanoptekWraithsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_canoptek_wraiths__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_canoptek_wraiths"),
  currency: "usd",
  price: "47.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronCanoptekWraithsRepackageTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_canoptek_wraiths_repackage__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_canoptek_wraiths_repackage"),
  currency: "usd",
  price: "47.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ZSk2",
  observed_date: null,
  superseded_date: null,
};


export const NecronCatacombCommmandBargeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_catacomb_commmand_barge__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_catacomb_commmand_barge"),
  currency: "usd",
  price: "37.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronCryptekTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_cryptek__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_cryptek"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/l3t2",
  observed_date: null,
  superseded_date: null,
};


export const NecronDoomScytheNightScytheTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_doom_scythe_night_scythe__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_doom_scythe_night_scythe"),
  currency: "usd",
  price: "45.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronDoomScytheNightScytheRepackageTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_doom_scythe_night_scythe_repackage__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_doom_scythe_night_scythe_repackage"),
  currency: "usd",
  price: "45.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-Sk2",
  observed_date: null,
  superseded_date: null,
};


export const NecronImmortalsDeathmarksTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_immortals_deathmarks__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_immortals_deathmarks"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronImmortalsDeathmarksTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_immortals_deathmarks__tcgcsv_low_usd"),
  kit_id: kitId("necron_immortals_deathmarks"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/7k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronImmortalsDeathmarksTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_immortals_deathmarks__tcgcsv_mid_usd"),
  kit_id: kitId("necron_immortals_deathmarks"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/7k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronImmortalsDeathmarksTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_immortals_deathmarks__tcgcsv_high_usd"),
  kit_id: kitId("necron_immortals_deathmarks"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/7k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronLychguardTriarchPraetoriansTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_lychguard_triarch_praetorians__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_lychguard_triarch_praetorians"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronOverlordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_overlord__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_overlord"),
  currency: "usd",
  price: "28.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dr82",
  observed_date: null,
  superseded_date: null,
};


export const NecronTombBladesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_tomb_blades__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_tomb_blades"),
  currency: "usd",
  price: "41.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9k82",
  observed_date: null,
  superseded_date: null,
};


export const NecronTombBladesRepackageTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_tomb_blades_repackage__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_tomb_blades_repackage"),
  currency: "usd",
  price: "41.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/XSk2",
  observed_date: null,
  superseded_date: null,
};


export const NecronWarriorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necron_warriors__tcgcsv_msrp_usd"),
  kit_id: kitId("necron_warriors"),
  currency: "usd",
  price: "36.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bk82",
  observed_date: null,
  superseded_date: null,
};


export const NecronsBattleforceEradicationLegionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_battleforce_eradication_legion__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_battleforce_eradication_legion"),
  currency: "usd",
  price: "210.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-mV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsCanoptekDoomstalkerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_canoptek_doomstalker__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_canoptek_doomstalker"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5bV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsConvergenceOfDominionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_convergence_of_dominion__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_convergence_of_dominion"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ndV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsCtanShardOfTheVoidDragonTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_ctan_shard_of_the_void_dragon__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_ctan_shard_of_the_void_dragon"),
  currency: "usd",
  price: "110.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cdV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsHexmarkDestroyerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_hexmark_destroyer__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_hexmark_destroyer"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/McV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsLokhustHeavyDestroyerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_lokhust_heavy_destroyer__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_lokhust_heavy_destroyer"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6bV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsLokhustHeavyDestroyerTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_lokhust_heavy_destroyer__tcgcsv_low_usd"),
  kit_id: kitId("necrons_lokhust_heavy_destroyer"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/6bV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsLokhustHeavyDestroyerTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_lokhust_heavy_destroyer__tcgcsv_mid_usd"),
  kit_id: kitId("necrons_lokhust_heavy_destroyer"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/6bV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsLokhustHeavyDestroyerTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_lokhust_heavy_destroyer__tcgcsv_high_usd"),
  kit_id: kitId("necrons_lokhust_heavy_destroyer"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/6bV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsMonolithTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_monolith__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_monolith"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jdV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsOphydianDestroyersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_ophydian_destroyers__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_ophydian_destroyers"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8dV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsSkorpekhDestroyersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_skorpekh_destroyers__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_skorpekh_destroyers"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/LcV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsSzarekhTheSilentKingTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_szarekh_the_silent_king__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_szarekh_the_silent_king"),
  currency: "usd",
  price: "150.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3bV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsWarriorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_warriors__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_warriors"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/GcV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsWarriorsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_warriors__tcgcsv_low_usd"),
  kit_id: kitId("necrons_warriors"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/GcV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsWarriorsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_warriors__tcgcsv_mid_usd"),
  kit_id: kitId("necrons_warriors"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/GcV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsWarriorsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_warriors__tcgcsv_high_usd"),
  kit_id: kitId("necrons_warriors"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/GcV5",
  observed_date: null,
  superseded_date: null,
};


export const NecronsWarriorsPaintsSetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("necrons_warriors_paints_set__tcgcsv_msrp_usd"),
  kit_id: kitId("necrons_warriors_paints_set"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/X5V5",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingNecronsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_necrons__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_necrons"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/WSk2",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesNecronsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseNecronsOutriderDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceNecronsDominionSpearheadTcgcsvMsrpUsdKitPrice,
    IlluminorSzerasTcgcsvMsrpUsdKitPrice,
    NecronCanoptekSpyderTcgcsvMsrpUsdKitPrice,
    NecronCanoptekWraithsTcgcsvMsrpUsdKitPrice,
    NecronCanoptekWraithsRepackageTcgcsvMsrpUsdKitPrice,
    NecronCatacombCommmandBargeTcgcsvMsrpUsdKitPrice,
    NecronCryptekTcgcsvMsrpUsdKitPrice,
    NecronDoomScytheNightScytheTcgcsvMsrpUsdKitPrice,
    NecronDoomScytheNightScytheRepackageTcgcsvMsrpUsdKitPrice,
    NecronImmortalsDeathmarksTcgcsvMsrpUsdKitPrice,
    NecronImmortalsDeathmarksTcgcsvLowUsdKitPrice,
    NecronImmortalsDeathmarksTcgcsvMidUsdKitPrice,
    NecronImmortalsDeathmarksTcgcsvHighUsdKitPrice,
    NecronLychguardTriarchPraetoriansTcgcsvMsrpUsdKitPrice,
    NecronOverlordTcgcsvMsrpUsdKitPrice,
    NecronTombBladesTcgcsvMsrpUsdKitPrice,
    NecronTombBladesRepackageTcgcsvMsrpUsdKitPrice,
    NecronWarriorsTcgcsvMsrpUsdKitPrice,
    NecronsBattleforceEradicationLegionTcgcsvMsrpUsdKitPrice,
    NecronsCanoptekDoomstalkerTcgcsvMsrpUsdKitPrice,
    NecronsConvergenceOfDominionTcgcsvMsrpUsdKitPrice,
    NecronsCtanShardOfTheVoidDragonTcgcsvMsrpUsdKitPrice,
    NecronsHexmarkDestroyerTcgcsvMsrpUsdKitPrice,
    NecronsLokhustHeavyDestroyerTcgcsvMsrpUsdKitPrice,
    NecronsLokhustHeavyDestroyerTcgcsvLowUsdKitPrice,
    NecronsLokhustHeavyDestroyerTcgcsvMidUsdKitPrice,
    NecronsLokhustHeavyDestroyerTcgcsvHighUsdKitPrice,
    NecronsMonolithTcgcsvMsrpUsdKitPrice,
    NecronsOphydianDestroyersTcgcsvMsrpUsdKitPrice,
    NecronsSkorpekhDestroyersTcgcsvMsrpUsdKitPrice,
    NecronsSzarekhTheSilentKingTcgcsvMsrpUsdKitPrice,
    NecronsWarriorsTcgcsvMsrpUsdKitPrice,
    NecronsWarriorsTcgcsvLowUsdKitPrice,
    NecronsWarriorsTcgcsvMidUsdKitPrice,
    NecronsWarriorsTcgcsvHighUsdKitPrice,
    NecronsWarriorsPaintsSetTcgcsvMsrpUsdKitPrice,
    StartCollectingNecronsTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
