import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for orks.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseOrksSpearheadDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_orks_spearhead_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_orks_spearhead_detachment"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/CTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceOrksKultOfSpeedTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_orks_kult_of_speed__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_orks_kult_of_speed"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nQf2",
  observed_date: null,
  superseded_date: null,
};


export const BoomdakkaSnazzwagonTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("boomdakka_snazzwagon__tcgcsv_msrp_usd"),
  kit_id: kitId("boomdakka_snazzwagon"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/t7s2",
  observed_date: null,
  superseded_date: null,
};


export const DeffkillaWartrikeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("deffkilla_wartrike__tcgcsv_msrp_usd"),
  kit_id: kitId("deffkilla_wartrike"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/v7s2",
  observed_date: null,
  superseded_date: null,
};


export const MegatrakkScrapjetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("megatrakk_scrapjet__tcgcsv_msrp_usd"),
  kit_id: kitId("megatrakk_scrapjet"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/w7s2",
  observed_date: null,
  superseded_date: null,
};


export const OrkBattlewagonTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_battlewagon__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_battlewagon"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "66.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ck82",
  observed_date: null,
  superseded_date: null,
};


export const OrkBoyzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_boyz__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_boyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "29.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkBoyzTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_boyz__tcgcsv_low_usd"),
  kit_id: kitId("ork_boyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/dk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkBoyzTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_boyz__tcgcsv_mid_usd"),
  kit_id: kitId("ork_boyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/dk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkBoyzTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_boyz__tcgcsv_high_usd"),
  kit_id: kitId("ork_boyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/dk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkFlashGitzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_flash_gitz__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_flash_gitz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "53.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkGorkanautTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_gorkanaut__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_gorkanaut"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "105.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkGretchinTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_gretchin__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_gretchin"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "16.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkGretchinTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_gretchin__tcgcsv_low_usd"),
  kit_id: kitId("ork_gretchin"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "16.50",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/hk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkGretchinTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_gretchin__tcgcsv_mid_usd"),
  kit_id: kitId("ork_gretchin"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "16.50",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/hk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkGretchinTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_gretchin__tcgcsv_high_usd"),
  kit_id: kitId("ork_gretchin"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "16.50",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/hk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkKillaKansTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_killa_kans__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_killa_kans"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "46.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkLootasBurnasTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_lootas_burnas__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_lootas_burnas"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/kk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkMeganobzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_meganobz__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_meganobz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "63.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkMekGunTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_mek_gun__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_mek_gun"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "46.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkNobzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_nobz__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_nobz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkPainboyTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_painboy__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_painboy"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "26.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lr82",
  observed_date: null,
  superseded_date: null,
};


export const OrkStormboyzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_stormboyz__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_stormboyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/pk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkTrukkTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_trukk__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_trukk"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "37.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkTrukkBoyzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_trukk_boyz__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_trukk_boyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkWarbikerMobTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_warbiker_mob__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_warbiker_mob"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "41.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sk82",
  observed_date: null,
  superseded_date: null,
};


export const OrkWazbomBlastajetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ork_wazbom_blastajet__tcgcsv_msrp_usd"),
  kit_id: kitId("ork_wazbom_blastajet"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/tk82",
  observed_date: null,
  superseded_date: null,
};


export const OrksGhazghkullThrakaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("orks_ghazghkull_thraka__tcgcsv_msrp_usd"),
  kit_id: kitId("orks_ghazghkull_thraka"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vgV5",
  observed_date: null,
  superseded_date: null,
};


export const OrksKustomBoostaBlastaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("orks_kustom_boosta_blasta__tcgcsv_msrp_usd"),
  kit_id: kitId("orks_kustom_boosta_blasta"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/GVx2",
  observed_date: null,
  superseded_date: null,
};


export const OrksShokkjumpDragstaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("orks_shokkjump_dragsta__tcgcsv_msrp_usd"),
  kit_id: kitId("orks_shokkjump_dragsta"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/FVx2",
  observed_date: null,
  superseded_date: null,
};


export const OrksStarterSetKillTeamKrogskullsBoyzTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("orks_starter_set_kill_team_krogskulls_boyz__tcgcsv_msrp_usd"),
  kit_id: kitId("orks_starter_set_kill_team_krogskulls_boyz"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ctp2",
  observed_date: null,
  superseded_date: null,
};


export const RukkatrukkSquigbuggyTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("rukkatrukk_squigbuggy__tcgcsv_msrp_usd"),
  kit_id: kitId("rukkatrukk_squigbuggy"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/x7s2",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesOrksDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseOrksSpearheadDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceOrksKultOfSpeedTcgcsvMsrpUsdKitPrice,
    BoomdakkaSnazzwagonTcgcsvMsrpUsdKitPrice,
    DeffkillaWartrikeTcgcsvMsrpUsdKitPrice,
    MegatrakkScrapjetTcgcsvMsrpUsdKitPrice,
    OrkBattlewagonTcgcsvMsrpUsdKitPrice,
    OrkBoyzTcgcsvMsrpUsdKitPrice,
    OrkBoyzTcgcsvLowUsdKitPrice,
    OrkBoyzTcgcsvMidUsdKitPrice,
    OrkBoyzTcgcsvHighUsdKitPrice,
    OrkFlashGitzTcgcsvMsrpUsdKitPrice,
    OrkGorkanautTcgcsvMsrpUsdKitPrice,
    OrkGretchinTcgcsvMsrpUsdKitPrice,
    OrkGretchinTcgcsvLowUsdKitPrice,
    OrkGretchinTcgcsvMidUsdKitPrice,
    OrkGretchinTcgcsvHighUsdKitPrice,
    OrkKillaKansTcgcsvMsrpUsdKitPrice,
    OrkLootasBurnasTcgcsvMsrpUsdKitPrice,
    OrkMeganobzTcgcsvMsrpUsdKitPrice,
    OrkMekGunTcgcsvMsrpUsdKitPrice,
    OrkNobzTcgcsvMsrpUsdKitPrice,
    OrkPainboyTcgcsvMsrpUsdKitPrice,
    OrkStormboyzTcgcsvMsrpUsdKitPrice,
    OrkTrukkTcgcsvMsrpUsdKitPrice,
    OrkTrukkBoyzTcgcsvMsrpUsdKitPrice,
    OrkWarbikerMobTcgcsvMsrpUsdKitPrice,
    OrkWazbomBlastajetTcgcsvMsrpUsdKitPrice,
    OrksGhazghkullThrakaTcgcsvMsrpUsdKitPrice,
    OrksKustomBoostaBlastaTcgcsvMsrpUsdKitPrice,
    OrksShokkjumpDragstaTcgcsvMsrpUsdKitPrice,
    OrksStarterSetKillTeamKrogskullsBoyzTcgcsvMsrpUsdKitPrice,
    RukkatrukkSquigbuggyTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
