import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for space_wolves.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const BattleforceSpaceWolvesTalonsOfMorkaiTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_space_wolves_talons_of_morkai__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_space_wolves_talons_of_morkai"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9Qf3",
  observed_date: null,
  superseded_date: null,
};


export const CombatPatrolSpaceWolvesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("combat_patrol_space_wolves__tcgcsv_msrp_usd"),
  kit_id: kitId("combat_patrol_space_wolves"),
  currency: "usd",
  price: "140.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/CgV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesFenrisianWolfPackTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_fenrisian_wolf_pack__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_fenrisian_wolf_pack"),
  currency: "usd",
  price: "24.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/tl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesFenrisianWolfPackTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_fenrisian_wolf_pack__tcgcsv_low_usd"),
  kit_id: kitId("space_wolves_fenrisian_wolf_pack"),
  currency: "usd",
  price: "22.99",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/tl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesFenrisianWolfPackTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_fenrisian_wolf_pack__tcgcsv_mid_usd"),
  kit_id: kitId("space_wolves_fenrisian_wolf_pack"),
  currency: "usd",
  price: "22.99",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/tl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesFenrisianWolfPackTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_fenrisian_wolf_pack__tcgcsv_high_usd"),
  kit_id: kitId("space_wolves_fenrisian_wolf_pack"),
  currency: "usd",
  price: "22.99",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/tl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesHoundsOfMorkaiTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_hounds_of_morkai__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_hounds_of_morkai"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/PgV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesIronPriestTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_iron_priest__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_iron_priest"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/pr82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesLongFangsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_long_fangs__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_long_fangs"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesPackTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_pack__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_pack"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesPrimarisUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_primaris_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_primaris_upgrades"),
  currency: "usd",
  price: "12.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/J3q2",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesRagnarBlackmaneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_ragnar_blackmane__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_ragnar_blackmane"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zgV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesSkyhammerWolfPackTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_skyhammer_wolf_pack__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_skyhammer_wolf_pack"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesStormfangGunshipTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_stormfang_gunship__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_stormfang_gunship"),
  currency: "usd",
  price: "81.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesThunderwolfCavalryTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_thunderwolf_cavalry__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_thunderwolf_cavalry"),
  currency: "usd",
  price: "54.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Bl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesUlrikTheSlayerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_ulrik_the_slayer__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_ulrik_the_slayer"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qr82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_upgrades"),
  currency: "usd",
  price: "13.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rr82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesVenerableDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_venerable_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_venerable_dreadnought"),
  currency: "usd",
  price: "54.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Cl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesWolfGuardTerminatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_wolf_guard_terminators__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_wolf_guard_terminators"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Dl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesWolfLordKromTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_wolf_lord_krom__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_wolf_lord_krom"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sr82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceWolvesWulfenTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_wolves_wulfen__tcgcsv_msrp_usd"),
  kit_id: kitId("space_wolves_wulfen"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Fl82",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingPrimarisSpaceWolvesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_primaris_space_wolves__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_primaris_space_wolves"),
  currency: "usd",
  price: "95.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7Vf3",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingSpaceWolvesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_space_wolves__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_space_wolves"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Ql82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesSpaceWolvesDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    BattleforceSpaceWolvesTalonsOfMorkaiTcgcsvMsrpUsdKitPrice,
    CombatPatrolSpaceWolvesTcgcsvMsrpUsdKitPrice,
    SpaceWolvesFenrisianWolfPackTcgcsvMsrpUsdKitPrice,
    SpaceWolvesFenrisianWolfPackTcgcsvLowUsdKitPrice,
    SpaceWolvesFenrisianWolfPackTcgcsvMidUsdKitPrice,
    SpaceWolvesFenrisianWolfPackTcgcsvHighUsdKitPrice,
    SpaceWolvesHoundsOfMorkaiTcgcsvMsrpUsdKitPrice,
    SpaceWolvesIronPriestTcgcsvMsrpUsdKitPrice,
    SpaceWolvesLongFangsTcgcsvMsrpUsdKitPrice,
    SpaceWolvesPackTcgcsvMsrpUsdKitPrice,
    SpaceWolvesPrimarisUpgradesTcgcsvMsrpUsdKitPrice,
    SpaceWolvesRagnarBlackmaneTcgcsvMsrpUsdKitPrice,
    SpaceWolvesSkyhammerWolfPackTcgcsvMsrpUsdKitPrice,
    SpaceWolvesStormfangGunshipTcgcsvMsrpUsdKitPrice,
    SpaceWolvesThunderwolfCavalryTcgcsvMsrpUsdKitPrice,
    SpaceWolvesUlrikTheSlayerTcgcsvMsrpUsdKitPrice,
    SpaceWolvesUpgradesTcgcsvMsrpUsdKitPrice,
    SpaceWolvesVenerableDreadnoughtTcgcsvMsrpUsdKitPrice,
    SpaceWolvesWolfGuardTerminatorsTcgcsvMsrpUsdKitPrice,
    SpaceWolvesWolfLordKromTcgcsvMsrpUsdKitPrice,
    SpaceWolvesWulfenTcgcsvMsrpUsdKitPrice,
    StartCollectingPrimarisSpaceWolvesTcgcsvMsrpUsdKitPrice,
    StartCollectingSpaceWolvesTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
