import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for space_marines.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AdeptusAstartesMarkIiiSpaceMarineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_astartes_mark_iii_space_marine__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_astartes_mark_iii_space_marine"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Jm82",
  observed_date: null,
  superseded_date: null,
};


export const AdeptusAstartesStarterSetKillTeamFangsOfUlfrichTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("adeptus_astartes_starter_set_kill_team_fangs_of_ulfrich__tcgcsv_msrp_usd"),
  kit_id: kitId("adeptus_astartes_starter_set_kill_team_fangs_of_ulfrich"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/btp2",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceSpaceMarinePrimarisInterdictionForceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_space_marine_primaris_interdiction_force__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_space_marine_primaris_interdiction_force"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/q2t2",
  observed_date: null,
  superseded_date: null,
};


export const ChaosRhinoTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("chaos_rhino__tcgcsv_msrp_usd"),
  kit_id: kitId("chaos_rhino"),
  currency: "usd",
  price: "39.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Bh82",
  observed_date: null,
  superseded_date: null,
};


export const EasyToBuildSpaceMarinePrimarisIntercessorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("easy_to_build_space_marine_primaris_intercessors__tcgcsv_msrp_usd"),
  kit_id: kitId("easy_to_build_space_marine_primaris_intercessors"),
  currency: "usd",
  price: "15.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cj82",
  observed_date: null,
  superseded_date: null,
};


export const EasyToBuildSpaceMarinePrimarisRedemptorDeadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("easy_to_build_space_marine_primaris_redemptor_deadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("easy_to_build_space_marine_primaris_redemptor_deadnought"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/q3K2",
  observed_date: null,
  superseded_date: null,
};


export const EasyToBuildSpaceMarinePrimarisReiversTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("easy_to_build_space_marine_primaris_reivers__tcgcsv_msrp_usd"),
  kit_id: kitId("easy_to_build_space_marine_primaris_reivers"),
  currency: "usd",
  price: "15.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dj82",
  observed_date: null,
  superseded_date: null,
};


export const IronHandsFeirrosTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("iron_hands_feirros__tcgcsv_msrp_usd"),
  kit_id: kitId("iron_hands_feirros"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/2Xf3",
  observed_date: null,
  superseded_date: null,
};


export const IronHandsPrimarisUpgradesTransfersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("iron_hands_primaris_upgrades_transfers__tcgcsv_msrp_usd"),
  kit_id: kitId("iron_hands_primaris_upgrades_transfers"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7Xf3",
  observed_date: null,
  superseded_date: null,
};


export const RavenGuardKayvaanShrikeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("raven_guard_kayvaan_shrike__tcgcsv_msrp_usd"),
  kit_id: kitId("raven_guard_kayvaan_shrike"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0Xf3",
  observed_date: null,
  superseded_date: null,
};


export const RavenGuardPrimarisUpgradesTransfersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("raven_guard_primaris_upgrades_transfers__tcgcsv_msrp_usd"),
  kit_id: kitId("raven_guard_primaris_upgrades_transfers"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6Xf3",
  observed_date: null,
  superseded_date: null,
};


export const SMLibrarianInTerminatorArmourTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("s_m_librarian_in_terminator_armour__tcgcsv_msrp_usd"),
  kit_id: kitId("s_m_librarian_in_terminator_armour"),
  currency: "usd",
  price: "31.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mr82",
  observed_date: null,
  superseded_date: null,
};


export const SalamandersAdraxAgatoneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("salamanders_adrax_agatone__tcgcsv_msrp_usd"),
  kit_id: kitId("salamanders_adrax_agatone"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/kNf3",
  observed_date: null,
  superseded_date: null,
};


export const SalamandersPrimarisUpgradesTransferssalamandersAdraxAgatoneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("salamanders_primaris_upgrades_transferssalamanders_adrax_agatone__tcgcsv_msrp_usd"),
  kit_id: kitId("salamanders_primaris_upgrades_transferssalamanders_adrax_agatone"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mNf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine"),
  currency: "usd",
  price: "10.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Mk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineAssaultSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_assault_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_assault_squad"),
  currency: "usd",
  price: "41.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Nk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineAttackBikeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_attack_bike__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_attack_bike"),
  currency: "usd",
  price: "27.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Pk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineBikeSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_bike_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_bike_squad"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Qk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineCenturionDevastatorSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_centurion_devastator_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_centurion_devastator_squad"),
  currency: "usd",
  price: "78.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Rk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineCommandSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_command_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_command_squad"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Sk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineCompanyCommandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_company_command__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_company_command"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Tk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDevastatorSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_devastator_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_devastator_squad"),
  currency: "usd",
  price: "46.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDevastatorSquadTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_devastator_squad__tcgcsv_low_usd"),
  kit_id: kitId("space_marine_devastator_squad"),
  currency: "usd",
  price: "46.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDevastatorSquadTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_devastator_squad__tcgcsv_mid_usd"),
  kit_id: kitId("space_marine_devastator_squad"),
  currency: "usd",
  price: "46.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDevastatorSquadTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_devastator_squad__tcgcsv_high_usd"),
  kit_id: kitId("space_marine_devastator_squad"),
  currency: "usd",
  price: "46.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_dreadnought"),
  currency: "usd",
  price: "46.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDreadnoughtTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_dreadnought__tcgcsv_low_usd"),
  kit_id: kitId("space_marine_dreadnought"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDreadnoughtTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_dreadnought__tcgcsv_mid_usd"),
  kit_id: kitId("space_marine_dreadnought"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDreadnoughtTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_dreadnought__tcgcsv_high_usd"),
  kit_id: kitId("space_marine_dreadnought"),
  currency: "usd",
  price: "70.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineDropPodTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_drop_pod__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_drop_pod"),
  currency: "usd",
  price: "37.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineFavouredOfChaosTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_favoured_of_chaos__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_favoured_of_chaos"),
  currency: "usd",
  price: "105.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Zk82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineHeroesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_heroes__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_heroes"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-k82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineHeroes3DispenserTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_heroes_3_dispenser__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_heroes_3_dispenser"),
  currency: "usd",
  price: "72.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/shV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineHeroesLimitedPrintingTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_heroes_limited_printing__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_heroes_limited_printing"),
  currency: "usd",
  price: "7.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vjs2",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineIroncladDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_ironclad_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_ironclad_dreadnought"),
  currency: "usd",
  price: "46.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_k82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineLandSpeederTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_land_speeder__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_land_speeder"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineLandSpeederStormTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_land_speeder_storm__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_land_speeder_storm"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/2l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineLibrarianTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_librarian__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_librarian"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nr82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePredatorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_predator__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_predator"),
  currency: "usd",
  price: "57.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisAggressorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_aggressors__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_primaris_aggressors"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisCaptainTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_captain__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_primaris_captain"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisLibrarianTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_librarian__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_primaris_librarian"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_redemptor_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_primaris_redemptor_dreadnought"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_redemptor_dreadnought__tcgcsv_low_usd"),
  kit_id: kitId("space_marine_primaris_redemptor_dreadnought"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/8l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_redemptor_dreadnought__tcgcsv_mid_usd"),
  kit_id: kitId("space_marine_primaris_redemptor_dreadnought"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/8l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_redemptor_dreadnought__tcgcsv_high_usd"),
  kit_id: kitId("space_marine_primaris_redemptor_dreadnought"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/8l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinePrimarisReiversTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_primaris_reivers__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_primaris_reivers"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9l82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineRazorbackTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_razorback__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_razorback"),
  currency: "usd",
  price: "41.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineRhinoTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_rhino__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_rhino"),
  currency: "usd",
  price: "37.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineScoutsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_scouts__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_scouts"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineScoutsWithSniperRiflesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_scouts_with_sniper_rifles__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_scouts_with_sniper_rifles"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineStalkerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_stalker__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_stalker"),
  currency: "usd",
  price: "65.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineSternguardVeteranSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_sternguard_veteran_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_sternguard_veteran_squad"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineStormhawkInterceptorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_stormhawk_interceptor__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_stormhawk_interceptor"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineTacticalSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_tactical_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_tactical_squad"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/kl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineTerminatorCloseCombatSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_terminator_close_combat_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_terminator_close_combat_squad"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ml82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineTerminatorCommandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_terminator_command__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_terminator_command"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineTerminatorSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_terminator_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_terminator_squad"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/pl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineVanguardVeteranSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_vanguard_veteran_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_vanguard_veteran_squad"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ql82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineVenerableDreadnoughtTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_venerable_dreadnought__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_venerable_dreadnought"),
  currency: "usd",
  price: "46.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarineVindicatorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marine_vindicator__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marine_vindicator"),
  currency: "usd",
  price: "57.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sl82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesAssaultIntercessorsPaintsSetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_assault_intercessors_paints_set__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_assault_intercessors_paints_set"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/T5V5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesBattleforceInterdictionForceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_battleforce_interdiction_force__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_battleforce_interdiction_force"),
  currency: "usd",
  price: "200.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/knV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesGladiatorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_gladiator__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_gladiator"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/RmV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesHammerfallBunkerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_hammerfall_bunker__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_hammerfall_bunker"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mdV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesMarneusCalgarUltramarinesChapterMasterTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_marneus_calgar_ultramarines_chapter_master__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_marneus_calgar_ultramarines_chapter_master"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/c3t2",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesOutridersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_outriders__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_outriders"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rgV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisCaptainInPhobosArmourTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_captain_in_phobos_armour__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_captain_in_phobos_armour"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jWf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisChaplainOnBikeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_chaplain_on_bike__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_chaplain_on_bike"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7bV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisEliminatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_eliminators__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_eliminators"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3Xf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisEliminatorsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_eliminators__tcgcsv_low_usd"),
  kit_id: kitId("space_marines_primaris_eliminators"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/3Xf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisEliminatorsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_eliminators__tcgcsv_mid_usd"),
  kit_id: kitId("space_marines_primaris_eliminators"),
  currency: "usd",
  price: "57.50",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/3Xf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisEliminatorsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_eliminators__tcgcsv_high_usd"),
  kit_id: kitId("space_marines_primaris_eliminators"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/3Xf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisFirestrikeServoTurretTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_firestrike_servo_turret__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_firestrike_servo_turret"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9bV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisImpulsorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_impulsor__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_impulsor"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gNf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisInfiltratorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_infiltrators__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_infiltrators"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hNf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisInvaderAtvTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_invader_atv__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_invader_atv"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8bV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisInvictorTacticalWarsuitTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_invictor_tactical_warsuit__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_invictor_tactical_warsuit"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gWf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisLibrarianInPhobosArmourTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_librarian_in_phobos_armour__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_librarian_in_phobos_armour"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lWf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisLieutenantInPhobosArmourTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_lieutenant_in_phobos_armour__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_lieutenant_in_phobos_armour"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5Xf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisLieutenantWithPowerSwordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_lieutenant_with_power_sword__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_lieutenant_with_power_sword"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nWf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisRepulsorExecutionerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_repulsor_executioner__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_repulsor_executioner"),
  currency: "usd",
  price: "100.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qSf3",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesPrimarisTechmarineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_primaris_techmarine__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_primaris_techmarine"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hdV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesRobouteGuillimanTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_roboute_guilliman__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_roboute_guilliman"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7fh2",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesTerminatorChaplainTarentusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_terminator_chaplain_tarentus__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_terminator_chaplain_tarentus"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xdV5",
  observed_date: null,
  superseded_date: null,
};


export const SpaceMarinesUltramarinesPrimarisUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_marines_ultramarines_primaris_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("space_marines_ultramarines_primaris_upgrades"),
  currency: "usd",
  price: "15.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/g2m2",
  observed_date: null,
  superseded_date: null,
};


export const SpacemarineLandraiderCrusaderRedeemerTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("spacemarine_landraider_crusader_redeemer__tcgcsv_msrp_usd"),
  kit_id: kitId("spacemarine_landraider_crusader_redeemer"),
  currency: "usd",
  price: "74.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Gl82",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingSpaceMarineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_space_marine__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_space_marine"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Pl82",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingVanguardSpaceMarinesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_vanguard_space_marines__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_vanguard_space_marines"),
  currency: "usd",
  price: "95.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-Pf3",
  observed_date: null,
  superseded_date: null,
};


export const TartarosTerminatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tartaros_terminators__tcgcsv_msrp_usd"),
  kit_id: kitId("tartaros_terminators"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vl82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesSpaceMarinesDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AdeptusAstartesMarkIiiSpaceMarineTcgcsvMsrpUsdKitPrice,
    AdeptusAstartesStarterSetKillTeamFangsOfUlfrichTcgcsvMsrpUsdKitPrice,
    BattleforceSpaceMarinePrimarisInterdictionForceTcgcsvMsrpUsdKitPrice,
    ChaosRhinoTcgcsvMsrpUsdKitPrice,
    EasyToBuildSpaceMarinePrimarisIntercessorsTcgcsvMsrpUsdKitPrice,
    EasyToBuildSpaceMarinePrimarisRedemptorDeadnoughtTcgcsvMsrpUsdKitPrice,
    EasyToBuildSpaceMarinePrimarisReiversTcgcsvMsrpUsdKitPrice,
    IronHandsFeirrosTcgcsvMsrpUsdKitPrice,
    IronHandsPrimarisUpgradesTransfersTcgcsvMsrpUsdKitPrice,
    RavenGuardKayvaanShrikeTcgcsvMsrpUsdKitPrice,
    RavenGuardPrimarisUpgradesTransfersTcgcsvMsrpUsdKitPrice,
    SMLibrarianInTerminatorArmourTcgcsvMsrpUsdKitPrice,
    SalamandersAdraxAgatoneTcgcsvMsrpUsdKitPrice,
    SalamandersPrimarisUpgradesTransferssalamandersAdraxAgatoneTcgcsvMsrpUsdKitPrice,
    SpaceMarineTcgcsvMsrpUsdKitPrice,
    SpaceMarineAssaultSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineAttackBikeTcgcsvMsrpUsdKitPrice,
    SpaceMarineBikeSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineCenturionDevastatorSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineCommandSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineCompanyCommandTcgcsvMsrpUsdKitPrice,
    SpaceMarineDevastatorSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineDevastatorSquadTcgcsvLowUsdKitPrice,
    SpaceMarineDevastatorSquadTcgcsvMidUsdKitPrice,
    SpaceMarineDevastatorSquadTcgcsvHighUsdKitPrice,
    SpaceMarineDreadnoughtTcgcsvMsrpUsdKitPrice,
    SpaceMarineDreadnoughtTcgcsvLowUsdKitPrice,
    SpaceMarineDreadnoughtTcgcsvMidUsdKitPrice,
    SpaceMarineDreadnoughtTcgcsvHighUsdKitPrice,
    SpaceMarineDropPodTcgcsvMsrpUsdKitPrice,
    SpaceMarineFavouredOfChaosTcgcsvMsrpUsdKitPrice,
    SpaceMarineHeroesTcgcsvMsrpUsdKitPrice,
    SpaceMarineHeroes3DispenserTcgcsvMsrpUsdKitPrice,
    SpaceMarineHeroesLimitedPrintingTcgcsvMsrpUsdKitPrice,
    SpaceMarineIroncladDreadnoughtTcgcsvMsrpUsdKitPrice,
    SpaceMarineLandSpeederTcgcsvMsrpUsdKitPrice,
    SpaceMarineLandSpeederStormTcgcsvMsrpUsdKitPrice,
    SpaceMarineLibrarianTcgcsvMsrpUsdKitPrice,
    SpaceMarinePredatorTcgcsvMsrpUsdKitPrice,
    SpaceMarinePrimarisAggressorsTcgcsvMsrpUsdKitPrice,
    SpaceMarinePrimarisCaptainTcgcsvMsrpUsdKitPrice,
    SpaceMarinePrimarisLibrarianTcgcsvMsrpUsdKitPrice,
    SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvMsrpUsdKitPrice,
    SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvLowUsdKitPrice,
    SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvMidUsdKitPrice,
    SpaceMarinePrimarisRedemptorDreadnoughtTcgcsvHighUsdKitPrice,
    SpaceMarinePrimarisReiversTcgcsvMsrpUsdKitPrice,
    SpaceMarineRazorbackTcgcsvMsrpUsdKitPrice,
    SpaceMarineRhinoTcgcsvMsrpUsdKitPrice,
    SpaceMarineScoutsTcgcsvMsrpUsdKitPrice,
    SpaceMarineScoutsWithSniperRiflesTcgcsvMsrpUsdKitPrice,
    SpaceMarineStalkerTcgcsvMsrpUsdKitPrice,
    SpaceMarineSternguardVeteranSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineStormhawkInterceptorTcgcsvMsrpUsdKitPrice,
    SpaceMarineTacticalSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineTerminatorCloseCombatSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineTerminatorCommandTcgcsvMsrpUsdKitPrice,
    SpaceMarineTerminatorSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineVanguardVeteranSquadTcgcsvMsrpUsdKitPrice,
    SpaceMarineVenerableDreadnoughtTcgcsvMsrpUsdKitPrice,
    SpaceMarineVindicatorTcgcsvMsrpUsdKitPrice,
    SpaceMarinesAssaultIntercessorsPaintsSetTcgcsvMsrpUsdKitPrice,
    SpaceMarinesBattleforceInterdictionForceTcgcsvMsrpUsdKitPrice,
    SpaceMarinesGladiatorTcgcsvMsrpUsdKitPrice,
    SpaceMarinesHammerfallBunkerTcgcsvMsrpUsdKitPrice,
    SpaceMarinesMarneusCalgarUltramarinesChapterMasterTcgcsvMsrpUsdKitPrice,
    SpaceMarinesOutridersTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisCaptainInPhobosArmourTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisChaplainOnBikeTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisEliminatorsTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisEliminatorsTcgcsvLowUsdKitPrice,
    SpaceMarinesPrimarisEliminatorsTcgcsvMidUsdKitPrice,
    SpaceMarinesPrimarisEliminatorsTcgcsvHighUsdKitPrice,
    SpaceMarinesPrimarisFirestrikeServoTurretTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisImpulsorTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisInfiltratorsTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisInvaderAtvTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisInvictorTacticalWarsuitTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisLibrarianInPhobosArmourTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisLieutenantInPhobosArmourTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisLieutenantWithPowerSwordTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisRepulsorExecutionerTcgcsvMsrpUsdKitPrice,
    SpaceMarinesPrimarisTechmarineTcgcsvMsrpUsdKitPrice,
    SpaceMarinesRobouteGuillimanTcgcsvMsrpUsdKitPrice,
    SpaceMarinesTerminatorChaplainTarentusTcgcsvMsrpUsdKitPrice,
    SpaceMarinesUltramarinesPrimarisUpgradesTcgcsvMsrpUsdKitPrice,
    SpacemarineLandraiderCrusaderRedeemerTcgcsvMsrpUsdKitPrice,
    StartCollectingSpaceMarineTcgcsvMsrpUsdKitPrice,
    StartCollectingVanguardSpaceMarinesTcgcsvMsrpUsdKitPrice,
    TartarosTerminatorsTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
