import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for tau_empire.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseTauEmpireVanguardDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_tau_empire_vanguard_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_tau_empire_vanguard_detachment"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/HTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceTauEmpireCommanderShadowsunTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_tau_empire_commander_shadowsun__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_tau_empire_commander_shadowsun"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/S-f3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceTauEmpireRapidInsertionCadreTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_tau_empire_rapid_insertion_cadre__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_tau_empire_rapid_insertion_cadre"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qQf2",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceTauEmpireStarclaimerHunterCadreTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_tau_empire_starclaimer_hunter_cadre__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_tau_empire_starclaimer_hunter_cadre"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cQf3",
  observed_date: null,
  superseded_date: null,
};


export const CadreFirebladeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("cadre_fireblade__tcgcsv_msrp_usd"),
  kit_id: kitId("cadre_fireblade"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "20.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xq82",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingTauEmpireTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_tau_empire__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_tau_empire"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Rl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireCoalitionCommandTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_coalition_command__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_coalition_command"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireCommanderTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_commander__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_commander"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireCommanderTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_commander__tcgcsv_low_usd"),
  kit_id: kitId("tau_empire_commander"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "62.50",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireCommanderTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_commander__tcgcsv_mid_usd"),
  kit_id: kitId("tau_empire_commander"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "62.50",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireCommanderTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_commander__tcgcsv_high_usd"),
  kit_id: kitId("tau_empire_commander"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "62.50",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireFireWarriorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_fire_warriors__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_fire_warriors"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Zl82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireKv128StormsurgeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_kv128_stormsurge__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_kv128_stormsurge"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "150.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-l82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpirePathfinderTeamTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_pathfinder_team__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_pathfinder_team"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_l82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpirePathfinderTeamTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_pathfinder_team__tcgcsv_low_usd"),
  kit_id: kitId("tau_empire_pathfinder_team"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/_l82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpirePathfinderTeamTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_pathfinder_team__tcgcsv_mid_usd"),
  kit_id: kitId("tau_empire_pathfinder_team"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/_l82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpirePathfinderTeamTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_pathfinder_team__tcgcsv_high_usd"),
  kit_id: kitId("tau_empire_pathfinder_team"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/_l82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireTidewallDroneportTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_tidewall_droneport__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_tidewall_droneport"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireTidewallRampartTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_tidewall_rampart__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_tidewall_rampart"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "160.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/2m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireTidewallShieldlineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_tidewall_shieldline__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_tidewall_shieldline"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/3m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireTx4PiranhaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_tx4_piranha__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_tx4_piranha"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireTy7DevilfishTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_ty7_devilfish__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_ty7_devilfish"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "38.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv25StealthBattlesuitsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv25_stealth_battlesuits__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_xv25_stealth_battlesuits"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "27.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv25StealthBattlesuitsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv25_stealth_battlesuits__tcgcsv_low_usd"),
  kit_id: kitId("tau_empire_xv25_stealth_battlesuits"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/7m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv25StealthBattlesuitsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv25_stealth_battlesuits__tcgcsv_mid_usd"),
  kit_id: kitId("tau_empire_xv25_stealth_battlesuits"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/7m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv25StealthBattlesuitsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv25_stealth_battlesuits__tcgcsv_high_usd"),
  kit_id: kitId("tau_empire_xv25_stealth_battlesuits"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/7m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv8CrisisBattlesuitsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv8_crisis_battlesuits__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_xv8_crisis_battlesuits"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv88BroadsideBattlesuitTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv88_broadside_battlesuit__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_xv88_broadside_battlesuit"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv88BroadsideBattlesuitTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv88_broadside_battlesuit__tcgcsv_low_usd"),
  kit_id: kitId("tau_empire_xv88_broadside_battlesuit"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "62.50",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/9m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv88BroadsideBattlesuitTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv88_broadside_battlesuit__tcgcsv_mid_usd"),
  kit_id: kitId("tau_empire_xv88_broadside_battlesuit"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "62.50",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/9m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv88BroadsideBattlesuitTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv88_broadside_battlesuit__tcgcsv_high_usd"),
  kit_id: kitId("tau_empire_xv88_broadside_battlesuit"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "62.50",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/9m82",
  observed_date: null,
  superseded_date: null,
};


export const TauEmpireXv95GhostkeelBattlesuitTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tau_empire_xv95_ghostkeel_battlesuit__tcgcsv_msrp_usd"),
  kit_id: kitId("tau_empire_xv95_ghostkeel_battlesuit"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bm82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesTauEmpireDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseTauEmpireVanguardDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceTauEmpireCommanderShadowsunTcgcsvMsrpUsdKitPrice,
    BattleforceTauEmpireRapidInsertionCadreTcgcsvMsrpUsdKitPrice,
    BattleforceTauEmpireStarclaimerHunterCadreTcgcsvMsrpUsdKitPrice,
    CadreFirebladeTcgcsvMsrpUsdKitPrice,
    StartCollectingTauEmpireTcgcsvMsrpUsdKitPrice,
    TauEmpireCoalitionCommandTcgcsvMsrpUsdKitPrice,
    TauEmpireCommanderTcgcsvMsrpUsdKitPrice,
    TauEmpireCommanderTcgcsvLowUsdKitPrice,
    TauEmpireCommanderTcgcsvMidUsdKitPrice,
    TauEmpireCommanderTcgcsvHighUsdKitPrice,
    TauEmpireFireWarriorsTcgcsvMsrpUsdKitPrice,
    TauEmpireKv128StormsurgeTcgcsvMsrpUsdKitPrice,
    TauEmpirePathfinderTeamTcgcsvMsrpUsdKitPrice,
    TauEmpirePathfinderTeamTcgcsvLowUsdKitPrice,
    TauEmpirePathfinderTeamTcgcsvMidUsdKitPrice,
    TauEmpirePathfinderTeamTcgcsvHighUsdKitPrice,
    TauEmpireTidewallDroneportTcgcsvMsrpUsdKitPrice,
    TauEmpireTidewallRampartTcgcsvMsrpUsdKitPrice,
    TauEmpireTidewallShieldlineTcgcsvMsrpUsdKitPrice,
    TauEmpireTx4PiranhaTcgcsvMsrpUsdKitPrice,
    TauEmpireTy7DevilfishTcgcsvMsrpUsdKitPrice,
    TauEmpireXv25StealthBattlesuitsTcgcsvMsrpUsdKitPrice,
    TauEmpireXv25StealthBattlesuitsTcgcsvLowUsdKitPrice,
    TauEmpireXv25StealthBattlesuitsTcgcsvMidUsdKitPrice,
    TauEmpireXv25StealthBattlesuitsTcgcsvHighUsdKitPrice,
    TauEmpireXv8CrisisBattlesuitsTcgcsvMsrpUsdKitPrice,
    TauEmpireXv88BroadsideBattlesuitTcgcsvMsrpUsdKitPrice,
    TauEmpireXv88BroadsideBattlesuitTcgcsvLowUsdKitPrice,
    TauEmpireXv88BroadsideBattlesuitTcgcsvMidUsdKitPrice,
    TauEmpireXv88BroadsideBattlesuitTcgcsvHighUsdKitPrice,
    TauEmpireXv95GhostkeelBattlesuitTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
