import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for thousand_sons.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const StartCollectingThousandSonsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_thousand_sons__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_thousand_sons"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "95.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/8Vf3",
  observed_date: null,
  superseded_date: null,
};


export const ThousandSonsExaltedSorcerersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("thousand_sons_exalted_sorcerers__tcgcsv_msrp_usd"),
  kit_id: kitId("thousand_sons_exalted_sorcerers"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cm82",
  observed_date: null,
  superseded_date: null,
};


export const ThousandSonsMagnusTheRedTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("thousand_sons_magnus_the_red__tcgcsv_msrp_usd"),
  kit_id: kitId("thousand_sons_magnus_the_red"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "130.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dm82",
  observed_date: null,
  superseded_date: null,
};


export const ThousandSonsScarabOccultTerminatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("thousand_sons_scarab_occult_terminators__tcgcsv_msrp_usd"),
  kit_id: kitId("thousand_sons_scarab_occult_terminators"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fm82",
  observed_date: null,
  superseded_date: null,
};


export const ThousandSonsTzaangorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("thousand_sons_tzaangors__tcgcsv_msrp_usd"),
  kit_id: kitId("thousand_sons_tzaangors"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gm82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesThousandSonsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    StartCollectingThousandSonsTcgcsvMsrpUsdKitPrice,
    ThousandSonsExaltedSorcerersTcgcsvMsrpUsdKitPrice,
    ThousandSonsMagnusTheRedTcgcsvMsrpUsdKitPrice,
    ThousandSonsScarabOccultTerminatorsTcgcsvMsrpUsdKitPrice,
    ThousandSonsTzaangorsTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
