import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for tyranids.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const ApocalypseTyranidsSpearheadDetachmentTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse_tyranids_spearhead_detachment__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse_tyranids_spearhead_detachment"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/DTf3",
  observed_date: null,
  superseded_date: null,
};


export const BattleforceTyranidsBioswarmTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battleforce_tyranids_bioswarm__tcgcsv_msrp_usd"),
  kit_id: kitId("battleforce_tyranids_bioswarm"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "185.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/fQf3",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingTyranidsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_tyranids__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_tyranids"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Sl82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidBroodlordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_broodlord__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_broodlord"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidGargoyleBroodTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_gargoyle_brood__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_gargoyle_brood"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "29.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/mm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidGenestealersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_genestealers__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_genestealers"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "30.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHarpyTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_harpy__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_harpy"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/pm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHaruspexTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_haruspex__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_haruspex"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "73.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/qm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHiveTyrantTheSwarmlordTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_hive_tyrant_the_swarmlord__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_hive_tyrant_the_swarmlord"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "53.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/rm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHiveTyrantTheSwarmlordTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_hive_tyrant_the_swarmlord__tcgcsv_low_usd"),
  kit_id: kitId("tyranid_hive_tyrant_the_swarmlord"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/rm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHiveTyrantTheSwarmlordTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_hive_tyrant_the_swarmlord__tcgcsv_mid_usd"),
  kit_id: kitId("tyranid_hive_tyrant_the_swarmlord"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/rm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHiveTyrantTheSwarmlordTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_hive_tyrant_the_swarmlord__tcgcsv_high_usd"),
  kit_id: kitId("tyranid_hive_tyrant_the_swarmlord"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/rm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidHormagauntBroodTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_hormagaunt_brood__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_hormagaunt_brood"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "29.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/sm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidSwarmTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_swarm__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_swarm"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/tm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTermagantBroodTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_termagant_brood__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_termagant_brood"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "29.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTermagantsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_termagants__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_termagants"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "10.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTermagantsTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_termagants__tcgcsv_low_usd"),
  kit_id: kitId("tyranid_termagants"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/wm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTermagantsTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_termagants__tcgcsv_mid_usd"),
  kit_id: kitId("tyranid_termagants"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/wm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTermagantsTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_termagants__tcgcsv_high_usd"),
  kit_id: kitId("tyranid_termagants"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/wm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTrygonMawlocTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_trygon_mawloc__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_trygon_mawloc"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "57.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTyrannocyteTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_tyrannocyte__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_tyrannocyte"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "63.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidTyrannofexTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_tyrannofex__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_tyrannofex"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "57.75",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Bm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidVenomthropesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_venomthropes__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_venomthropes"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "66.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Cm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidWarriorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranid_warriors__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranid_warriors"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "51.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Dm82",
  observed_date: null,
  superseded_date: null,
};


export const TyranidsBattleforceBroodSwarmTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranids_battleforce_brood_swarm__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranids_battleforce_brood_swarm"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "210.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_mV5",
  observed_date: null,
  superseded_date: null,
};


export const TyranidsStarterSetKillTeamTheWrithingShadowTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tyranids_starter_set_kill_team_the_writhing_shadow__tcgcsv_msrp_usd"),
  kit_id: kitId("tyranids_starter_set_kill_team_the_writhing_shadow"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0vp2",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesTyranidsDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    ApocalypseTyranidsSpearheadDetachmentTcgcsvMsrpUsdKitPrice,
    BattleforceTyranidsBioswarmTcgcsvMsrpUsdKitPrice,
    StartCollectingTyranidsTcgcsvMsrpUsdKitPrice,
    TyranidBroodlordTcgcsvMsrpUsdKitPrice,
    TyranidGargoyleBroodTcgcsvMsrpUsdKitPrice,
    TyranidGenestealersTcgcsvMsrpUsdKitPrice,
    TyranidHarpyTcgcsvMsrpUsdKitPrice,
    TyranidHaruspexTcgcsvMsrpUsdKitPrice,
    TyranidHiveTyrantTheSwarmlordTcgcsvMsrpUsdKitPrice,
    TyranidHiveTyrantTheSwarmlordTcgcsvLowUsdKitPrice,
    TyranidHiveTyrantTheSwarmlordTcgcsvMidUsdKitPrice,
    TyranidHiveTyrantTheSwarmlordTcgcsvHighUsdKitPrice,
    TyranidHormagauntBroodTcgcsvMsrpUsdKitPrice,
    TyranidSwarmTcgcsvMsrpUsdKitPrice,
    TyranidTermagantBroodTcgcsvMsrpUsdKitPrice,
    TyranidTermagantsTcgcsvMsrpUsdKitPrice,
    TyranidTermagantsTcgcsvLowUsdKitPrice,
    TyranidTermagantsTcgcsvMidUsdKitPrice,
    TyranidTermagantsTcgcsvHighUsdKitPrice,
    TyranidTrygonMawlocTcgcsvMsrpUsdKitPrice,
    TyranidTyrannocyteTcgcsvMsrpUsdKitPrice,
    TyranidTyrannofexTcgcsvMsrpUsdKitPrice,
    TyranidVenomthropesTcgcsvMsrpUsdKitPrice,
    TyranidWarriorsTcgcsvMsrpUsdKitPrice,
    TyranidsBattleforceBroodSwarmTcgcsvMsrpUsdKitPrice,
    TyranidsStarterSetKillTeamTheWrithingShadowTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
