import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId, priceMarketId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for ultramarines.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const UltramarinesChiefLibrarianTiguriusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ultramarines_chief_librarian_tigurius__tcgcsv_msrp_usd"),
  kit_id: kitId("ultramarines_chief_librarian_tigurius"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6Wf3",
  observed_date: null,
  superseded_date: null,
};


export const UltramarinesUpgradesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ultramarines_upgrades__tcgcsv_msrp_usd"),
  kit_id: kitId("ultramarines_upgrades"),
  price_market_id: priceMarketId("us_en"),
  currency: "usd",
  price: "13.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/tr82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesUltramarinesDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    UltramarinesChiefLibrarianTiguriusTcgcsvMsrpUsdKitPrice,
    UltramarinesUpgradesTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
