import type {
  KitPriceConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitPriceId } from "../../../ids";

/**
 * Imported kit price rows from TCGCSV catalog data for unassigned.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const AegisDefenseLineTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("aegis_defense_line__tcgcsv_msrp_usd"),
  kit_id: kitId("aegis_defense_line"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_g82",
  observed_date: null,
  superseded_date: null,
};


export const ApocalypseTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("apocalypse__tcgcsv_msrp_usd"),
  kit_id: kitId("apocalypse"),
  currency: "usd",
  price: "100.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/lSf3",
  observed_date: null,
  superseded_date: null,
};


export const BasilicaAdministratumTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("basilica_administratum__tcgcsv_msrp_usd"),
  kit_id: kitId("basilica_administratum"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/gh82",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumBattlefieldTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_battlefield__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_battlefield"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/CVM2",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumConservatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_conservators__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_conservators"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0bV5",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumMunitorumArmouredContainersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_munitorum_armoured_containers__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_munitorum_armoured_containers"),
  currency: "usd",
  price: "55.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/K9V5",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumObjectiveSetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_objective_set__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_objective_set"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vVM2",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumSanctumAdministratusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_sanctum_administratus__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_sanctum_administratus"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-9V5",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumSubCloisterAndStorageFaneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_sub_cloister_and_storage_fane__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_sub_cloister_and_storage_fane"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/_9V5",
  observed_date: null,
  superseded_date: null,
};


export const BattlezoneManufactorumVertigusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("battlezone_manufactorum_vertigus__tcgcsv_msrp_usd"),
  kit_id: kitId("battlezone_manufactorum_vertigus"),
  currency: "usd",
  price: "150.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Q9V5",
  observed_date: null,
  superseded_date: null,
};


export const BloodOfThePhoenixTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("blood_of_the_phoenix__tcgcsv_msrp_usd"),
  kit_id: kitId("blood_of_the_phoenix"),
  currency: "usd",
  price: "230.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dNf3",
  observed_date: null,
  superseded_date: null,
};


export const CommandEditionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("command_edition__tcgcsv_msrp_usd"),
  kit_id: kitId("command_edition"),
  currency: "usd",
  price: "165.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/H5V5",
  observed_date: null,
  superseded_date: null,
};


export const CommandEditionBattlefieldExpansionSetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("command_edition_battlefield_expansion_set__tcgcsv_msrp_usd"),
  kit_id: kitId("command_edition_battlefield_expansion_set"),
  currency: "usd",
  price: "90.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/M5V5",
  observed_date: null,
  superseded_date: null,
};


export const CypherTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("cypher__tcgcsv_msrp_usd"),
  kit_id: kitId("cypher"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/cfh2",
  observed_date: null,
  superseded_date: null,
};


export const DaRedGobboTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("da_red_gobbo__tcgcsv_msrp_usd"),
  kit_id: kitId("da_red_gobbo"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9Pf3",
  observed_date: null,
  superseded_date: null,
};


export const DarkImperiumTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("dark_imperium__tcgcsv_msrp_usd"),
  kit_id: kitId("dark_imperium"),
  currency: "usd",
  price: "160.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jd82",
  observed_date: null,
  superseded_date: null,
};


export const EliteEditionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("elite_edition__tcgcsv_msrp_usd"),
  kit_id: kitId("elite_edition"),
  currency: "usd",
  price: "99.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/J5V5",
  observed_date: null,
  superseded_date: null,
};


export const FirstStrikeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("first_strike__tcgcsv_msrp_usd"),
  kit_id: kitId("first_strike"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/kd82",
  observed_date: null,
  superseded_date: null,
};


export const ForgebaneTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("forgebane__tcgcsv_msrp_usd"),
  kit_id: kitId("forgebane"),
  currency: "usd",
  price: "160.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/K0m2",
  observed_date: null,
  superseded_date: null,
};


export const GangsOfCommorraghTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("gangs_of_commorragh__tcgcsv_msrp_usd"),
  kit_id: kitId("gangs_of_commorragh"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/ld82",
  observed_date: null,
  superseded_date: null,
};


export const GettingStartedWithWarhammer40kTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("getting_started_with_warhammer_40k__tcgcsv_msrp_usd"),
  kit_id: kitId("getting_started_with_warhammer_40k"),
  currency: "usd",
  price: "15.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bbV5",
  observed_date: null,
  superseded_date: null,
};


export const GettingStartedWithWarhammer40kTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("getting_started_with_warhammer_40k__tcgcsv_low_usd"),
  kit_id: kitId("getting_started_with_warhammer_40k"),
  currency: "usd",
  price: "29.99",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/bbV5",
  observed_date: null,
  superseded_date: null,
};


export const GettingStartedWithWarhammer40kTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("getting_started_with_warhammer_40k__tcgcsv_mid_usd"),
  kit_id: kitId("getting_started_with_warhammer_40k"),
  currency: "usd",
  price: "29.99",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/bbV5",
  observed_date: null,
  superseded_date: null,
};


export const GettingStartedWithWarhammer40kTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("getting_started_with_warhammer_40k__tcgcsv_high_usd"),
  kit_id: kitId("getting_started_with_warhammer_40k"),
  currency: "usd",
  price: "29.99",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/bbV5",
  observed_date: null,
  superseded_date: null,
};


export const HaemotropeReactorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("haemotrope_reactor__tcgcsv_msrp_usd"),
  kit_id: kitId("haemotrope_reactor"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Jj82",
  observed_date: null,
  superseded_date: null,
};


export const HammerheadGunshipTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("hammerhead_gunship__tcgcsv_msrp_usd"),
  kit_id: kitId("hammerhead_gunship"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Kj82",
  observed_date: null,
  superseded_date: null,
};


export const HeroBasesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("hero_bases__tcgcsv_msrp_usd"),
  kit_id: kitId("hero_bases"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Pj82",
  observed_date: null,
  superseded_date: null,
};


export const ImperialBastionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_bastion__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_bastion"),
  currency: "usd",
  price: "41.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Vj82",
  observed_date: null,
  superseded_date: null,
};


export const ImperialKnightWardenTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_knight_warden__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_knight_warden"),
  currency: "usd",
  price: "157.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Wj82",
  observed_date: null,
  superseded_date: null,
};


export const ImperialSectorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("imperial_sector__tcgcsv_msrp_usd"),
  kit_id: kitId("imperial_sector"),
  currency: "usd",
  price: "120.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Xj82",
  observed_date: null,
  superseded_date: null,
};


export const IndomitusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("indomitus__tcgcsv_msrp_usd"),
  kit_id: kitId("indomitus"),
  currency: "usd",
  price: "199.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/tVM2",
  observed_date: null,
  superseded_date: null,
};


export const InquisitorGreyfaxTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("inquisitor_greyfax__tcgcsv_msrp_usd"),
  kit_id: kitId("inquisitor_greyfax"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/dfh2",
  observed_date: null,
  superseded_date: null,
};


export const KhorneBerzerkersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("khorne_berzerkers__tcgcsv_msrp_usd"),
  kit_id: kitId("khorne_berzerkers"),
  currency: "usd",
  price: "37.25",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Zj82",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team"),
  currency: "usd",
  price: "130.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9tp2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamArenaTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_arena__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_arena"),
  currency: "usd",
  price: "90.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wlw2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamRogueTraderTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_rogue_trader__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_rogue_trader"),
  currency: "usd",
  price: "130.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9Lq2",
  observed_date: null,
  superseded_date: null,
};


export const KillTeamStarterSetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("kill_team_starter_set__tcgcsv_msrp_usd"),
  kit_id: kitId("kill_team_starter_set"),
  currency: "usd",
  price: "160.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vWf3",
  observed_date: null,
  superseded_date: null,
};


export const KillzoneSectorFronterisTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("killzone_sector_fronteris__tcgcsv_msrp_usd"),
  kit_id: kitId("killzone_sector_fronteris"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Blw2",
  observed_date: null,
  superseded_date: null,
};


export const KnowNoFearTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("know_no_fear__tcgcsv_msrp_usd"),
  kit_id: kitId("know_no_fear"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/md82",
  observed_date: null,
  superseded_date: null,
};


export const LoganGrimnarOnStormriderTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("logan_grimnar_on_stormrider__tcgcsv_msrp_usd"),
  kit_id: kitId("logan_grimnar_on_stormrider"),
  currency: "usd",
  price: "59.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Km82",
  observed_date: null,
  superseded_date: null,
};


export const ManufactorumTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("manufactorum__tcgcsv_msrp_usd"),
  kit_id: kitId("manufactorum"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/-j82",
  observed_date: null,
  superseded_date: null,
};


export const MunitoriumArmouredContainersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("munitorium_armoured_containers__tcgcsv_msrp_usd"),
  kit_id: kitId("munitorium_armoured_containers"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/0k82",
  observed_date: null,
  superseded_date: null,
};


export const PaintsToolsSetTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("paints_tools_set__tcgcsv_msrp_usd"),
  kit_id: kitId("paints_tools_set"),
  currency: "usd",
  price: "45.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/R5V5",
  observed_date: null,
  superseded_date: null,
};


export const PromethiumRelayPipesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("promethium_relay_pipes__tcgcsv_msrp_usd"),
  kit_id: kitId("promethium_relay_pipes"),
  currency: "usd",
  price: "37.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/vk82",
  observed_date: null,
  superseded_date: null,
};


export const ProphecyOfTheWolfTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("prophecy_of_the_wolf__tcgcsv_msrp_usd"),
  kit_id: kitId("prophecy_of_the_wolf"),
  currency: "usd",
  price: "170.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/5wg3",
  observed_date: null,
  superseded_date: null,
};


export const RavenwingCommandSquadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("ravenwing_command_squad__tcgcsv_msrp_usd"),
  kit_id: kitId("ravenwing_command_squad"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/wk82",
  observed_date: null,
  superseded_date: null,
};


export const RecruitEditionTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("recruit_edition__tcgcsv_msrp_usd"),
  kit_id: kitId("recruit_edition"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/L5V5",
  observed_date: null,
  superseded_date: null,
};


export const SectorImperialis2540mmRoundBasesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_imperialis_25_40mm_round_bases__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_imperialis_25_40mm_round_bases"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/xk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorImperialis32mmRoundBasesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_imperialis_32mm_round_bases__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_imperialis_32mm_round_bases"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/zk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorImperialis60mmRd7590mmOvalBasesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_imperialis_60mm_rd_75_90mm_oval_bases__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_imperialis_60mm_rd_75_90mm_oval_bases"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Bk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorImperialisLargeBaseDetailKitTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_imperialis_large_base_detail_kit__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_imperialis_large_base_detail_kit"),
  currency: "usd",
  price: "33.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Ck82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusAlchomiteStackTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_alchomite_stack__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_alchomite_stack"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Dk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusFerratonicFurnaceTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_ferratonic_furnace__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_ferratonic_furnace"),
  currency: "usd",
  price: "50.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Fk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusFerratonicIncineratorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_ferratonic_incinerator__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_ferratonic_incinerator"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Gk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusGalvanicMagnaventTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_galvanic_magnavent__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_galvanic_magnavent"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusGalvanicServoHaulersTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_galvanic_servo_haulers__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_galvanic_servo_haulers"),
  currency: "usd",
  price: "40.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Jk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusIndustrialBasesTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_industrial_bases__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_industrial_bases"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Kk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusPromethiumForgeTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_promethium_forge__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_promethium_forge"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Lk82",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusPromethiumRefineryTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_promethium_refinery__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_promethium_refinery"),
  currency: "usd",
  price: "115.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/9kf2",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusTectonicFragdrillTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_tectonic_fragdrill__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_tectonic_fragdrill"),
  currency: "usd",
  price: "60.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Jlw2",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusThermicPlasmaConduitsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_thermic_plasma_conduits__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_thermic_plasma_conduits"),
  currency: "usd",
  price: "35.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/6kf2",
  observed_date: null,
  superseded_date: null,
};


export const SectorMechanicusThermicPlasmaRegulatorsTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("sector_mechanicus_thermic_plasma_regulators__tcgcsv_msrp_usd"),
  kit_id: kitId("sector_mechanicus_thermic_plasma_regulators"),
  currency: "usd",
  price: "25.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/7kf2",
  observed_date: null,
  superseded_date: null,
};


export const ShadowspearTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("shadowspear__tcgcsv_msrp_usd"),
  kit_id: kitId("shadowspear"),
  currency: "usd",
  price: "175.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/NVx2",
  observed_date: null,
  superseded_date: null,
};


export const SpaceHulkTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_hulk__tcgcsv_msrp_usd"),
  kit_id: kitId("space_hulk"),
  currency: "usd",
  price: "125.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/bd82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceHulkTcgcsvLowUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_hulk__tcgcsv_low_usd"),
  kit_id: kitId("space_hulk"),
  currency: "usd",
  price: "500.00",
  price_source: "tcgcsv_low_usd",
  price_source_url: "https://cpt.tcgcsv.com/bd82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceHulkTcgcsvMidUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_hulk__tcgcsv_mid_usd"),
  kit_id: kitId("space_hulk"),
  currency: "usd",
  price: "500.00",
  price_source: "tcgcsv_mid_usd",
  price_source_url: "https://cpt.tcgcsv.com/bd82",
  observed_date: null,
  superseded_date: null,
};


export const SpaceHulkTcgcsvHighUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("space_hulk__tcgcsv_high_usd"),
  kit_id: kitId("space_hulk"),
  currency: "usd",
  price: "500.00",
  price_source: "tcgcsv_high_usd",
  price_source_url: "https://cpt.tcgcsv.com/bd82",
  observed_date: null,
  superseded_date: null,
};


export const SpeedFreeksTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("speed_freeks__tcgcsv_msrp_usd"),
  kit_id: kitId("speed_freeks"),
  currency: "usd",
  price: "150.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/p6s2",
  observed_date: null,
  superseded_date: null,
};


export const StartCollectingMilitarumTempestusTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("start_collecting_militarum_tempestus__tcgcsv_msrp_usd"),
  kit_id: kitId("start_collecting_militarum_tempestus"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Nl82",
  observed_date: null,
  superseded_date: null,
};


export const StormravenGunshipTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("stormraven_gunship__tcgcsv_msrp_usd"),
  kit_id: kitId("stormraven_gunship"),
  currency: "usd",
  price: "82.50",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Tl82",
  observed_date: null,
  superseded_date: null,
};


export const TalonsOfTheEmperorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("talons_of_the_emperor__tcgcsv_msrp_usd"),
  kit_id: kitId("talons_of_the_emperor"),
  currency: "usd",
  price: "160.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/nd82",
  observed_date: null,
  superseded_date: null,
};


export const ToothAndClawTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("tooth_and_claw__tcgcsv_msrp_usd"),
  kit_id: kitId("tooth_and_claw"),
  currency: "usd",
  price: "150.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/K3q2",
  observed_date: null,
  superseded_date: null,
};


export const TriumvirateOfTheImperiumTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("triumvirate_of_the_imperium__tcgcsv_msrp_usd"),
  kit_id: kitId("triumvirate_of_the_imperium"),
  currency: "usd",
  price: "80.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/hm82",
  observed_date: null,
  superseded_date: null,
};


export const TriumvirateOfThePrimarchTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("triumvirate_of_the_primarch__tcgcsv_msrp_usd"),
  kit_id: kitId("triumvirate_of_the_primarch"),
  currency: "usd",
  price: "90.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/jm82",
  observed_date: null,
  superseded_date: null,
};


export const TriumvirateOfYnneadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("triumvirate_of_ynnead__tcgcsv_msrp_usd"),
  kit_id: kitId("triumvirate_of_ynnead"),
  currency: "usd",
  price: "75.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/km82",
  observed_date: null,
  superseded_date: null,
};


export const UrbanConquestTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("urban_conquest__tcgcsv_msrp_usd"),
  kit_id: kitId("urban_conquest"),
  currency: "usd",
  price: "100.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Dst2",
  observed_date: null,
  superseded_date: null,
};


export const VoidshieldGeneratorTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("voidshield_generator__tcgcsv_msrp_usd"),
  kit_id: kitId("voidshield_generator"),
  currency: "usd",
  price: "100.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Fm82",
  observed_date: null,
  superseded_date: null,
};


export const WakeTheDeadTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("wake_the_dead__tcgcsv_msrp_usd"),
  kit_id: kitId("wake_the_dead"),
  currency: "usd",
  price: "150.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/n5s2",
  observed_date: null,
  superseded_date: null,
};


export const Xv104RiptideBattlesuitTcgcsvMsrpUsdKitPrice: KitPriceConfig = {
  id: kitPriceId("xv104_riptide_battlesuit__tcgcsv_msrp_usd"),
  kit_id: kitId("xv104_riptide_battlesuit"),
  currency: "usd",
  price: "85.00",
  price_source: "tcgcsv_msrp_usd",
  price_source_url: "https://cpt.tcgcsv.com/Hm82",
  observed_date: null,
  superseded_date: null,
};


export const tcgCsvImportedKitPricesUnassignedDataset: SeedDataset<"kit_prices"> = {
  table: "kit_prices",
  records: [
    AegisDefenseLineTcgcsvMsrpUsdKitPrice,
    ApocalypseTcgcsvMsrpUsdKitPrice,
    BasilicaAdministratumTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumBattlefieldTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumConservatorsTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumMunitorumArmouredContainersTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumObjectiveSetTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumSanctumAdministratusTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumSubCloisterAndStorageFaneTcgcsvMsrpUsdKitPrice,
    BattlezoneManufactorumVertigusTcgcsvMsrpUsdKitPrice,
    BloodOfThePhoenixTcgcsvMsrpUsdKitPrice,
    CommandEditionTcgcsvMsrpUsdKitPrice,
    CommandEditionBattlefieldExpansionSetTcgcsvMsrpUsdKitPrice,
    CypherTcgcsvMsrpUsdKitPrice,
    DaRedGobboTcgcsvMsrpUsdKitPrice,
    DarkImperiumTcgcsvMsrpUsdKitPrice,
    EliteEditionTcgcsvMsrpUsdKitPrice,
    FirstStrikeTcgcsvMsrpUsdKitPrice,
    ForgebaneTcgcsvMsrpUsdKitPrice,
    GangsOfCommorraghTcgcsvMsrpUsdKitPrice,
    GettingStartedWithWarhammer40kTcgcsvMsrpUsdKitPrice,
    GettingStartedWithWarhammer40kTcgcsvLowUsdKitPrice,
    GettingStartedWithWarhammer40kTcgcsvMidUsdKitPrice,
    GettingStartedWithWarhammer40kTcgcsvHighUsdKitPrice,
    HaemotropeReactorTcgcsvMsrpUsdKitPrice,
    HammerheadGunshipTcgcsvMsrpUsdKitPrice,
    HeroBasesTcgcsvMsrpUsdKitPrice,
    ImperialBastionTcgcsvMsrpUsdKitPrice,
    ImperialKnightWardenTcgcsvMsrpUsdKitPrice,
    ImperialSectorTcgcsvMsrpUsdKitPrice,
    IndomitusTcgcsvMsrpUsdKitPrice,
    InquisitorGreyfaxTcgcsvMsrpUsdKitPrice,
    KhorneBerzerkersTcgcsvMsrpUsdKitPrice,
    KillTeamTcgcsvMsrpUsdKitPrice,
    KillTeamArenaTcgcsvMsrpUsdKitPrice,
    KillTeamRogueTraderTcgcsvMsrpUsdKitPrice,
    KillTeamStarterSetTcgcsvMsrpUsdKitPrice,
    KillzoneSectorFronterisTcgcsvMsrpUsdKitPrice,
    KnowNoFearTcgcsvMsrpUsdKitPrice,
    LoganGrimnarOnStormriderTcgcsvMsrpUsdKitPrice,
    ManufactorumTcgcsvMsrpUsdKitPrice,
    MunitoriumArmouredContainersTcgcsvMsrpUsdKitPrice,
    PaintsToolsSetTcgcsvMsrpUsdKitPrice,
    PromethiumRelayPipesTcgcsvMsrpUsdKitPrice,
    ProphecyOfTheWolfTcgcsvMsrpUsdKitPrice,
    RavenwingCommandSquadTcgcsvMsrpUsdKitPrice,
    RecruitEditionTcgcsvMsrpUsdKitPrice,
    SectorImperialis2540mmRoundBasesTcgcsvMsrpUsdKitPrice,
    SectorImperialis32mmRoundBasesTcgcsvMsrpUsdKitPrice,
    SectorImperialis60mmRd7590mmOvalBasesTcgcsvMsrpUsdKitPrice,
    SectorImperialisLargeBaseDetailKitTcgcsvMsrpUsdKitPrice,
    SectorMechanicusAlchomiteStackTcgcsvMsrpUsdKitPrice,
    SectorMechanicusFerratonicFurnaceTcgcsvMsrpUsdKitPrice,
    SectorMechanicusFerratonicIncineratorTcgcsvMsrpUsdKitPrice,
    SectorMechanicusGalvanicMagnaventTcgcsvMsrpUsdKitPrice,
    SectorMechanicusGalvanicServoHaulersTcgcsvMsrpUsdKitPrice,
    SectorMechanicusIndustrialBasesTcgcsvMsrpUsdKitPrice,
    SectorMechanicusPromethiumForgeTcgcsvMsrpUsdKitPrice,
    SectorMechanicusPromethiumRefineryTcgcsvMsrpUsdKitPrice,
    SectorMechanicusTectonicFragdrillTcgcsvMsrpUsdKitPrice,
    SectorMechanicusThermicPlasmaConduitsTcgcsvMsrpUsdKitPrice,
    SectorMechanicusThermicPlasmaRegulatorsTcgcsvMsrpUsdKitPrice,
    ShadowspearTcgcsvMsrpUsdKitPrice,
    SpaceHulkTcgcsvMsrpUsdKitPrice,
    SpaceHulkTcgcsvLowUsdKitPrice,
    SpaceHulkTcgcsvMidUsdKitPrice,
    SpaceHulkTcgcsvHighUsdKitPrice,
    SpeedFreeksTcgcsvMsrpUsdKitPrice,
    StartCollectingMilitarumTempestusTcgcsvMsrpUsdKitPrice,
    StormravenGunshipTcgcsvMsrpUsdKitPrice,
    TalonsOfTheEmperorTcgcsvMsrpUsdKitPrice,
    ToothAndClawTcgcsvMsrpUsdKitPrice,
    TriumvirateOfTheImperiumTcgcsvMsrpUsdKitPrice,
    TriumvirateOfThePrimarchTcgcsvMsrpUsdKitPrice,
    TriumvirateOfYnneadTcgcsvMsrpUsdKitPrice,
    UrbanConquestTcgcsvMsrpUsdKitPrice,
    VoidshieldGeneratorTcgcsvMsrpUsdKitPrice,
    WakeTheDeadTcgcsvMsrpUsdKitPrice,
    Xv104RiptideBattlesuitTcgcsvMsrpUsdKitPrice,
  ] satisfies KitPriceConfig[],
};
