/**
 * Generates `price_market_countries.data.ts` by mapping every seeded country
 * to its GW price market.
 *
 * Rules:
 *  - Explicit overrides table covers named special cases.
 *  - Everything else defaults to rest_of_world_en.
 *
 * canada_fr shares currency with canada_en; CA maps to canada_en for pricing.
 * canada_fr has no country mappings (it is a locale-only variant).
 *
 * Run:
 *   npx tsx scripts/sync-price-market-countries.ts
 */

import * as fs from "fs";
import * as path from "path";
import { countriesDataset } from "../db/seed_config/seed/data/countries.data";
import { priceMarketId } from "../db/seed_config/seed/ids";

const OUTPUT_PATH = path.resolve(
  __dirname,
  "../db/seed_config/seed/data/price_market_countries.data.ts"
);

// Countries that map to a specific non-default market.
// Key: ISO 3166-1 alpha-2 code.  Value: price market slug.
const MARKET_OVERRIDES: Record<string, string> = {
  // USD — United States
  US: "us_en",

  // CAD — Canada (English is the primary pricing market for CA)
  CA: "canada_en",

  // GBP — United Kingdom and Crown Dependencies
  GB: "uk_en",
  GG: "uk_en", // Guernsey
  JE: "uk_en", // Jersey
  IM: "uk_en", // Isle of Man

  // AUD — Australia and territories
  AU: "australia_en",
  CX: "australia_en", // Christmas Island
  CC: "australia_en", // Cocos (Keeling) Islands
  NF: "australia_en", // Norfolk Island

  // NZD — New Zealand
  NZ: "new_zealand_en",

  // CHF — Switzerland and Liechtenstein
  CH: "switzerland_en",
  LI: "switzerland_en",

  // PLN — Poland
  PL: "poland_pl",

  // JPY — Japan
  JP: "japan_en",

  // EUR — European Union and associated territories
  // EU member states
  AT: "eu_en", // Austria
  BE: "eu_en", // Belgium
  BG: "eu_en", // Bulgaria
  HR: "eu_en", // Croatia
  CY: "eu_en", // Cyprus
  CZ: "eu_en", // Czech Republic
  DK: "eu_en", // Denmark
  EE: "eu_en", // Estonia
  FI: "eu_en", // Finland
  FR: "eu_en", // France
  DE: "eu_en", // Germany
  GR: "eu_en", // Greece
  HU: "eu_en", // Hungary
  IE: "eu_en", // Ireland
  IT: "eu_en", // Italy
  LV: "eu_en", // Latvia
  LT: "eu_en", // Lithuania
  LU: "eu_en", // Luxembourg
  MT: "eu_en", // Malta
  NL: "eu_en", // Netherlands
  PT: "eu_en", // Portugal
  RO: "eu_en", // Romania
  SK: "eu_en", // Slovakia
  SI: "eu_en", // Slovenia
  ES: "eu_en", // Spain
  SE: "eu_en", // Sweden
  // Non-EU European Economic Area / closely tied EUR countries GW typically prices in EUR
  IS: "eu_en", // Iceland
  NO: "eu_en", // Norway
  AD: "eu_en", // Andorra
  MC: "eu_en", // Monaco
  SM: "eu_en", // San Marino
  VA: "eu_en", // Vatican City
};

function main() {
  const allCountryCca2s = countriesDataset.records.map((c) => c.cca2);

  const rows: Array<{ priceMarketId: string; countryCca2: string; marketSlug: string }> = [];

  for (const cca2 of allCountryCca2s) {
    const slug = MARKET_OVERRIDES[cca2] ?? "rest_of_world_en";
    rows.push({
      priceMarketId: priceMarketId(slug as Parameters<typeof priceMarketId>[0]),
      countryCca2: cca2,
      marketSlug: slug,
    });
  }

  // Sort: explicit markets first, then rest_of_world; within each group alphabetically.
  rows.sort((a, b) => {
    if (a.marketSlug === "rest_of_world_en" && b.marketSlug !== "rest_of_world_en") return 1;
    if (a.marketSlug !== "rest_of_world_en" && b.marketSlug === "rest_of_world_en") return -1;
    const mCmp = a.marketSlug.localeCompare(b.marketSlug);
    if (mCmp !== 0) return mCmp;
    return a.countryCca2.localeCompare(b.countryCca2);
  });

  const countsByMarket: Record<string, number> = {};
  for (const r of rows) {
    countsByMarket[r.marketSlug] = (countsByMarket[r.marketSlug] ?? 0) + 1;
  }

  const recordLines = rows
    .map(
      (r) =>
        `    { price_market_id: priceMarketId("${r.marketSlug}"), country_cca2: "${r.countryCca2}" },`
    )
    .join("\n");

  const summaryComment = Object.entries(countsByMarket)
    .sort()
    .map(([slug, count]) => ` * - ${slug}: ${count}`)
    .join("\n");

  const output = `import type {
  PriceMarketCountryConfig,
  SeedDataset,
} from "../../types/_index.types";
import { priceMarketId } from "../ids";

/**
 * Typed seed dataset for the \`price_market_countries\` table.
 *
 * Generated by \`scripts/sync-price-market-countries.ts\`.
 * Maps every seeded ISO country to its GW price market.
 * Re-run the script to regenerate after adding new countries.
 *
 * Market distribution:
${summaryComment}
 */
export const priceMarketCountriesDataset: SeedDataset<"price_market_countries"> = {
  table: "price_market_countries",
  records: [
${recordLines}
  ] satisfies PriceMarketCountryConfig[],
};
`;

  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");
  console.log(`Wrote ${rows.length} country-market rows to ${OUTPUT_PATH}`);
  for (const [slug, count] of Object.entries(countsByMarket).sort()) {
    console.log(`  ${slug}: ${count}`);
  }
}

main();
