/**
 * Aggregated kit_units dataset from docs/kit_unit_status.md (parsed factions).
 * Generated by scripts/parse-kit-unit-status.py.
 */

import { kitUnitsMarkdownAdeptaSororitasDataset } from "./adepta_sororitas.data";
import { kitUnitsMarkdownAdeptusCustodesDataset } from "./adeptus_custodes.data";

export const kitUnitsMarkdownDatasets = [
  kitUnitsMarkdownAdeptaSororitasDataset,
  kitUnitsMarkdownAdeptusCustodesDataset,
];
