import type {
  KitUnitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitUnitId, unitId } from "../../../ids";

/**
 * Kit-to-unit entries parsed from docs/kit_unit_status.md for adepta_sororitas.
 * Generated by scripts/parse-kit-unit-status.py.
 * review_status: "needs_review" — verify model counts, component_type, and unit matches.
 */

export const AdeptaSororitasArcoFlagellantsArcoFlagellantsCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_arco_flagellants__arco_flagellants__complete_unit"),
  kit_id: kitId("adepta_sororitas_arco_flagellants"),
  unit_id: unitId("arco_flagellants"),
  unit_count: 1,
  model_count: 10,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/25ukqjlq",
  source_text: "10x Arco-Flagellants",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasBattleSistersSquadBattleSistersSquadCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_battle_sisters_squad__battle_sisters_squad__complete_unit"),
  kit_id: kitId("adepta_sororitas_battle_sisters_squad"),
  unit_id: unitId("battle_sisters_squad"),
  unit_count: 1,
  model_count: 11,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/289oakcx",
  source_text: "10x Battle Sisters, 1x Incensor Cherub",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasCanonessCanonessCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_canoness__canoness__complete_unit"),
  kit_id: kitId("adepta_sororitas_canoness"),
  unit_id: unitId("canoness"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/28kvmkjr",
  source_text: "1x Canonness",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasDialogusDialogusCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_dialogus__dialogus__complete_unit"),
  kit_id: kitId("adepta_sororitas_dialogus"),
  unit_id: unitId("dialogus"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/237ky9lm",
  source_text: "1x Dialogus",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasExorcistExorcistCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_exorcist__exorcist__complete_unit"),
  kit_id: kitId("adepta_sororitas_exorcist"),
  unit_id: unitId("exorcist"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/2aabmm7y",
  source_text: "1x Exorcist",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasHospitallerHospitallerCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_hospitaller__hospitaller__complete_unit"),
  kit_id: kitId("adepta_sororitas_hospitaller"),
  unit_id: unitId("hospitaller"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/274holqg",
  source_text: "1x Hospitaller",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasImmolatorImmolatorCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_immolator__immolator__complete_unit"),
  kit_id: kitId("adepta_sororitas_immolator"),
  unit_id: unitId("immolator"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/2d8nczkl",
  source_text: "1x Immolator",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasJunithEruitaJunithEruitaCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_junith_eruita__junith_eruita__complete_unit"),
  kit_id: kitId("adepta_sororitas_junith_eruita"),
  unit_id: unitId("junith_eruita"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/2bxclaaj",
  source_text: "1x Junith Eruita",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasPenitentEnginesPenitentEnginesAlternateBuildKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_penitent_engines__penitent_engines__alternate_build"),
  kit_id: kitId("adepta_sororitas_penitent_engines"),
  unit_id: unitId("penitent_engines"),
  unit_count: 1,
  model_count: 2,
  component_type: "alternate_build",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/257ra4s2",
  source_text: "2x Penitent Engines or 2x Mortifiers",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasRepentiaSquadRepentiaSquadCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_repentia_squad__repentia_squad__complete_unit"),
  kit_id: kitId("adepta_sororitas_repentia_squad"),
  unit_id: unitId("repentia_squad"),
  unit_count: 1,
  model_count: 10,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/26u5qvju",
  source_text: "9x Sister Repentia, 1x Repentia Superior",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasRetributorSquadRetributorSquadCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_retributor_squad__retributor_squad__complete_unit"),
  kit_id: kitId("adepta_sororitas_retributor_squad"),
  unit_id: unitId("retributor_squad"),
  unit_count: 1,
  model_count: 7,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/28avkyzr",
  source_text: "4x Retributors, 1x Retributor Superior, 2x Armorium Cherubs",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasRhinoSororitasRhinoCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_rhino__sororitas_rhino__complete_unit"),
  kit_id: kitId("adepta_sororitas_rhino"),
  unit_id: unitId("sororitas_rhino"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/2yplzln6",
  source_text: "1x Sororitas Rhino",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasSeraphimSquadSeraphimSquadAlternateBuildKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_seraphim_squad__seraphim_squad__alternate_build"),
  kit_id: kitId("adepta_sororitas_seraphim_squad"),
  unit_id: unitId("seraphim_squad"),
  unit_count: 1,
  model_count: 5,
  component_type: "alternate_build",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/28on6esc",
  source_text: "4x Seraphim, 1x Seraphim Superior",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasTheTriumphOfStKatherineTriumphOfSaintKatherineCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_the_triumph_of_st_katherine__triumph_of_saint_katherine__complete_unit"),
  kit_id: kitId("adepta_sororitas_the_triumph_of_st_katherine"),
  unit_id: unitId("triumph_of_saint_katherine"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/2a9ckvr6",
  source_text: "1x Triumph of Saint Katherine",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptaSororitasCelestineTheLivingSaintSaintCelestineCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adepta_sororitas_celestine_the_living_saint__saint_celestine__complete_unit"),
  kit_id: kitId("adepta_sororitas_celestine_the_living_saint"),
  unit_id: unitId("saint_celestine"),
  unit_count: 1,
  model_count: 3,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/26axvq82",
  source_text: "1x Celestine, 2x Geminae Superia",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptusSororitasImagifierImagifierCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adeptus_sororitas_imagifier__imagifier__complete_unit"),
  kit_id: kitId("adeptus_sororitas_imagifier"),
  unit_id: unitId("imagifier"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/28a5ojb6",
  source_text: "1x Imagifier",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const kitUnitsMarkdownAdeptaSororitasDataset: SeedDataset<"kit_units"> = {
  table: "kit_units",
  records: [
    AdeptaSororitasArcoFlagellantsArcoFlagellantsCompleteUnitKitUnit,
    AdeptaSororitasBattleSistersSquadBattleSistersSquadCompleteUnitKitUnit,
    AdeptaSororitasCanonessCanonessCompleteUnitKitUnit,
    AdeptaSororitasDialogusDialogusCompleteUnitKitUnit,
    AdeptaSororitasExorcistExorcistCompleteUnitKitUnit,
    AdeptaSororitasHospitallerHospitallerCompleteUnitKitUnit,
    AdeptaSororitasImmolatorImmolatorCompleteUnitKitUnit,
    AdeptaSororitasJunithEruitaJunithEruitaCompleteUnitKitUnit,
    AdeptaSororitasPenitentEnginesPenitentEnginesAlternateBuildKitUnit,
    AdeptaSororitasRepentiaSquadRepentiaSquadCompleteUnitKitUnit,
    AdeptaSororitasRetributorSquadRetributorSquadCompleteUnitKitUnit,
    AdeptaSororitasRhinoSororitasRhinoCompleteUnitKitUnit,
    AdeptaSororitasSeraphimSquadSeraphimSquadAlternateBuildKitUnit,
    AdeptaSororitasTheTriumphOfStKatherineTriumphOfSaintKatherineCompleteUnitKitUnit,
    AdeptaSororitasCelestineTheLivingSaintSaintCelestineCompleteUnitKitUnit,
    AdeptusSororitasImagifierImagifierCompleteUnitKitUnit,
  ] satisfies KitUnitConfig[],
};
