import type {
  KitUnitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitId, kitUnitId, unitId } from "../../../ids";

/**
 * Kit-to-unit entries parsed from docs/kit_unit_status.md for adeptus_custodes.
 * Generated by scripts/parse-kit-unit-status.py.
 * review_status: "needs_review" — verify model counts, component_type, and unit matches.
 */

export const AdeptusCustodesCaptainGeneralTrajannValorisTrajannValorisCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adeptus_custodes_captain_general_trajann_valoris__trajann_valoris__complete_unit"),
  kit_id: kitId("adeptus_custodes_captain_general_trajann_valoris"),
  unit_id: unitId("trajann_valoris"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/27t76v7s",
  source_text: "1x Captain-General Trajann Valoris",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptusCustodesCustodianWardensCustodianWardensCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adeptus_custodes_custodian_wardens__custodian_wardens__complete_unit"),
  kit_id: kitId("adeptus_custodes_custodian_wardens"),
  unit_id: unitId("custodian_wardens"),
  unit_count: 1,
  model_count: 5,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/2bfjjxsn",
  source_text: "5x Custodian Wardens",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const AdeptusCustodesVertusPraetorsVertusPraetorsCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("adeptus_custodes_vertus_praetors__vertus_praetors__complete_unit"),
  kit_id: kitId("adeptus_custodes_vertus_praetors"),
  unit_id: unitId("vertus_praetors"),
  unit_count: 1,
  model_count: 3,
  component_type: "complete_unit",
  source_kind: "games_workshop_product_page",
  source_url: "https://tinyurl.com/26gpao8q",
  source_text: "3x Vertus Praetors",
  review_status: "needs_review",
  effective_date: null,
  superseded_date: null,
};

export const kitUnitsMarkdownAdeptusCustodesDataset: SeedDataset<"kit_units"> = {
  table: "kit_units",
  records: [
    AdeptusCustodesCaptainGeneralTrajannValorisTrajannValorisCompleteUnitKitUnit,
    AdeptusCustodesCustodianWardensCustodianWardensCompleteUnitKitUnit,
    AdeptusCustodesVertusPraetorsVertusPraetorsCompleteUnitKitUnit,
  ] satisfies KitUnitConfig[],
};
