import type {
  KitUnitConfig,
  SeedDataset,
} from "../../../../types/_index.types";
import { kitContentImportedKitUnitsMinisetBlackTemplarsDataset } from "./miniset/black_templars.data";

/**
 * Aggregates generated source-backed seed shards.
 * Generated by scripts/kit_content_importer/applyer.py.
 */
export const kitContentImportedKitUnitsDataset: SeedDataset<"kit_units"> = {
  table: "kit_units",
  records: [
    ...kitContentImportedKitUnitsMinisetBlackTemplarsDataset.records,
  ] satisfies KitUnitConfig[],
};
