import type {
  KitUnitConfig,
  SeedDataset,
} from "../../../../../types/_index.types";
import { kitId, kitUnitId, unitId } from "../../../../ids";

/**
 * Imported kit-to-unit rows from miniset kit content pages for black_templars.
 * Generated by scripts/kit_content_importer/applyer.py.
 */

export const CombatPatrolBlackTemplars2025EmperorsChampionCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("combat_patrol_black_templars_2025__emperors_champion__complete_unit"),
  kit_id: kitId("combat_patrol_black_templars_2025"),
  unit_id: unitId("emperors_champion"),
  unit_count: 1,
  model_count: 1,
  component_type: "complete_unit",
  source_kind: "miniset",
  source_url: "https://miniset.net/sets/gw-99120101428?language=en",
  source_text: "1x Emperor's Champion",
  review_status: "approved",
  effective_date: null,
  superseded_date: null,
};


export const CombatPatrolBlackTemplars2025BladeguardVeteranSquadCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("combat_patrol_black_templars_2025__bladeguard_veteran_squad__complete_unit"),
  kit_id: kitId("combat_patrol_black_templars_2025"),
  unit_id: unitId("bladeguard_veteran_squad"),
  unit_count: 1,
  model_count: 3,
  component_type: "complete_unit",
  source_kind: "miniset",
  source_url: "https://miniset.net/sets/gw-99120101428?language=en",
  source_text: "3x Bladeguard Veterans",
  review_status: "approved",
  effective_date: null,
  superseded_date: null,
};


export const CombatPatrolBlackTemplars2025SwordBrethrenSquadCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("combat_patrol_black_templars_2025__sword_brethren_squad__complete_unit"),
  kit_id: kitId("combat_patrol_black_templars_2025"),
  unit_id: unitId("sword_brethren_squad"),
  unit_count: 1,
  model_count: 5,
  component_type: "complete_unit",
  source_kind: "miniset",
  source_url: "https://miniset.net/sets/gw-99120101428?language=en",
  source_text: "5x Sword Brethren",
  review_status: "approved",
  effective_date: null,
  superseded_date: null,
};


export const CombatPatrolBlackTemplars2025CrusaderSquadCompleteUnitKitUnit: KitUnitConfig = {
  id: kitUnitId("combat_patrol_black_templars_2025__crusader_squad__complete_unit"),
  kit_id: kitId("combat_patrol_black_templars_2025"),
  unit_id: unitId("crusader_squad"),
  unit_count: 1,
  model_count: 10,
  component_type: "complete_unit",
  source_kind: "miniset",
  source_url: "https://miniset.net/sets/gw-99120101428?language=en",
  source_text: "10x Crusaders",
  review_status: "approved",
  effective_date: null,
  superseded_date: null,
};


export const kitContentImportedKitUnitsMinisetBlackTemplarsDataset: SeedDataset<"kit_units"> = {
  table: "kit_units",
  records: [
    CombatPatrolBlackTemplars2025EmperorsChampionCompleteUnitKitUnit,
    CombatPatrolBlackTemplars2025BladeguardVeteranSquadCompleteUnitKitUnit,
    CombatPatrolBlackTemplars2025SwordBrethrenSquadCompleteUnitKitUnit,
    CombatPatrolBlackTemplars2025CrusaderSquadCompleteUnitKitUnit,
  ] satisfies KitUnitConfig[],
};
